// Auto-generated by scripts/extract_tck.py --gen-cpp
// DO NOT EDIT MANUALLY
//
// Generated 69 test suite registrations
//

#ifndef CORRECTNESS_JSON_DIR
#define CORRECTNESS_JSON_DIR "tests/correctness"
#endif

// Match1 (86 scenarios)
static auto __cases_clauses_match_Match1 = LoadCasesFromJSON(std::string(CORRECTNESS_JSON_DIR) + "/clauses/match/Match1.json");
INSTANTIATE_TEST_SUITE_P(
    clauses_match_Match1,
    CorrectnessTest,
    ::testing::ValuesIn(__cases_clauses_match_Match1));

// Match2 (86 scenarios)
static auto __cases_clauses_match_Match2 = LoadCasesFromJSON(std::string(CORRECTNESS_JSON_DIR) + "/clauses/match/Match2.json");
INSTANTIATE_TEST_SUITE_P(
    clauses_match_Match2,
    CorrectnessTest,
    ::testing::ValuesIn(__cases_clauses_match_Match2));

// Match3 (30 scenarios)
static auto __cases_clauses_match_Match3 = LoadCasesFromJSON(std::string(CORRECTNESS_JSON_DIR) + "/clauses/match/Match3.json");
INSTANTIATE_TEST_SUITE_P(
    clauses_match_Match3,
    CorrectnessTest,
    ::testing::ValuesIn(__cases_clauses_match_Match3));

// Match4 (10 scenarios)
static auto __cases_clauses_match_Match4 = LoadCasesFromJSON(std::string(CORRECTNESS_JSON_DIR) + "/clauses/match/Match4.json");
INSTANTIATE_TEST_SUITE_P(
    clauses_match_Match4,
    CorrectnessTest,
    ::testing::ValuesIn(__cases_clauses_match_Match4));

// Match5 (29 scenarios)
static auto __cases_clauses_match_Match5 = LoadCasesFromJSON(std::string(CORRECTNESS_JSON_DIR) + "/clauses/match/Match5.json");
INSTANTIATE_TEST_SUITE_P(
    clauses_match_Match5,
    CorrectnessTest,
    ::testing::ValuesIn(__cases_clauses_match_Match5));

// Match6 (97 scenarios)
static auto __cases_clauses_match_Match6 = LoadCasesFromJSON(std::string(CORRECTNESS_JSON_DIR) + "/clauses/match/Match6.json");
INSTANTIATE_TEST_SUITE_P(
    clauses_match_Match6,
    CorrectnessTest,
    ::testing::ValuesIn(__cases_clauses_match_Match6));

// Match7 (31 scenarios)
static auto __cases_clauses_match_Match7 = LoadCasesFromJSON(std::string(CORRECTNESS_JSON_DIR) + "/clauses/match/Match7.json");
INSTANTIATE_TEST_SUITE_P(
    clauses_match_Match7,
    CorrectnessTest,
    ::testing::ValuesIn(__cases_clauses_match_Match7));

// Match8 (3 scenarios)
static auto __cases_clauses_match_Match8 = LoadCasesFromJSON(std::string(CORRECTNESS_JSON_DIR) + "/clauses/match/Match8.json");
INSTANTIATE_TEST_SUITE_P(
    clauses_match_Match8,
    CorrectnessTest,
    ::testing::ValuesIn(__cases_clauses_match_Match8));

// Match9 (9 scenarios)
static auto __cases_clauses_match_Match9 = LoadCasesFromJSON(std::string(CORRECTNESS_JSON_DIR) + "/clauses/match/Match9.json");
INSTANTIATE_TEST_SUITE_P(
    clauses_match_Match9,
    CorrectnessTest,
    ::testing::ValuesIn(__cases_clauses_match_Match9));

// MatchWhere1 (15 scenarios)
static auto __cases_clauses_match_where_MatchWhere1 = LoadCasesFromJSON(std::string(CORRECTNESS_JSON_DIR) + "/clauses/match-where/MatchWhere1.json");
INSTANTIATE_TEST_SUITE_P(
    clauses_match_where_MatchWhere1,
    CorrectnessTest,
    ::testing::ValuesIn(__cases_clauses_match_where_MatchWhere1));

// MatchWhere2 (2 scenarios)
static auto __cases_clauses_match_where_MatchWhere2 = LoadCasesFromJSON(std::string(CORRECTNESS_JSON_DIR) + "/clauses/match-where/MatchWhere2.json");
INSTANTIATE_TEST_SUITE_P(
    clauses_match_where_MatchWhere2,
    CorrectnessTest,
    ::testing::ValuesIn(__cases_clauses_match_where_MatchWhere2));

// MatchWhere3 (3 scenarios)
static auto __cases_clauses_match_where_MatchWhere3 = LoadCasesFromJSON(std::string(CORRECTNESS_JSON_DIR) + "/clauses/match-where/MatchWhere3.json");
INSTANTIATE_TEST_SUITE_P(
    clauses_match_where_MatchWhere3,
    CorrectnessTest,
    ::testing::ValuesIn(__cases_clauses_match_where_MatchWhere3));

// MatchWhere4 (2 scenarios)
static auto __cases_clauses_match_where_MatchWhere4 = LoadCasesFromJSON(std::string(CORRECTNESS_JSON_DIR) + "/clauses/match-where/MatchWhere4.json");
INSTANTIATE_TEST_SUITE_P(
    clauses_match_where_MatchWhere4,
    CorrectnessTest,
    ::testing::ValuesIn(__cases_clauses_match_where_MatchWhere4));

// MatchWhere5 (4 scenarios)
static auto __cases_clauses_match_where_MatchWhere5 = LoadCasesFromJSON(std::string(CORRECTNESS_JSON_DIR) + "/clauses/match-where/MatchWhere5.json");
INSTANTIATE_TEST_SUITE_P(
    clauses_match_where_MatchWhere5,
    CorrectnessTest,
    ::testing::ValuesIn(__cases_clauses_match_where_MatchWhere5));

// MatchWhere6 (8 scenarios)
static auto __cases_clauses_match_where_MatchWhere6 = LoadCasesFromJSON(std::string(CORRECTNESS_JSON_DIR) + "/clauses/match-where/MatchWhere6.json");
INSTANTIATE_TEST_SUITE_P(
    clauses_match_where_MatchWhere6,
    CorrectnessTest,
    ::testing::ValuesIn(__cases_clauses_match_where_MatchWhere6));

// Return1 (2 scenarios)
static auto __cases_clauses_return_Return1 = LoadCasesFromJSON(std::string(CORRECTNESS_JSON_DIR) + "/clauses/return/Return1.json");
INSTANTIATE_TEST_SUITE_P(
    clauses_return_Return1,
    CorrectnessTest,
    ::testing::ValuesIn(__cases_clauses_return_Return1));

// Return2 (18 scenarios)
static auto __cases_clauses_return_Return2 = LoadCasesFromJSON(std::string(CORRECTNESS_JSON_DIR) + "/clauses/return/Return2.json");
INSTANTIATE_TEST_SUITE_P(
    clauses_return_Return2,
    CorrectnessTest,
    ::testing::ValuesIn(__cases_clauses_return_Return2));

// Return3 (3 scenarios)
static auto __cases_clauses_return_Return3 = LoadCasesFromJSON(std::string(CORRECTNESS_JSON_DIR) + "/clauses/return/Return3.json");
INSTANTIATE_TEST_SUITE_P(
    clauses_return_Return3,
    CorrectnessTest,
    ::testing::ValuesIn(__cases_clauses_return_Return3));

// Return4 (11 scenarios)
static auto __cases_clauses_return_Return4 = LoadCasesFromJSON(std::string(CORRECTNESS_JSON_DIR) + "/clauses/return/Return4.json");
INSTANTIATE_TEST_SUITE_P(
    clauses_return_Return4,
    CorrectnessTest,
    ::testing::ValuesIn(__cases_clauses_return_Return4));

// Return5 (5 scenarios)
static auto __cases_clauses_return_Return5 = LoadCasesFromJSON(std::string(CORRECTNESS_JSON_DIR) + "/clauses/return/Return5.json");
INSTANTIATE_TEST_SUITE_P(
    clauses_return_Return5,
    CorrectnessTest,
    ::testing::ValuesIn(__cases_clauses_return_Return5));

// Return6 (21 scenarios)
static auto __cases_clauses_return_Return6 = LoadCasesFromJSON(std::string(CORRECTNESS_JSON_DIR) + "/clauses/return/Return6.json");
INSTANTIATE_TEST_SUITE_P(
    clauses_return_Return6,
    CorrectnessTest,
    ::testing::ValuesIn(__cases_clauses_return_Return6));

// Return7 (2 scenarios)
static auto __cases_clauses_return_Return7 = LoadCasesFromJSON(std::string(CORRECTNESS_JSON_DIR) + "/clauses/return/Return7.json");
INSTANTIATE_TEST_SUITE_P(
    clauses_return_Return7,
    CorrectnessTest,
    ::testing::ValuesIn(__cases_clauses_return_Return7));

// Return8 (1 scenarios)
static auto __cases_clauses_return_Return8 = LoadCasesFromJSON(std::string(CORRECTNESS_JSON_DIR) + "/clauses/return/Return8.json");
INSTANTIATE_TEST_SUITE_P(
    clauses_return_Return8,
    CorrectnessTest,
    ::testing::ValuesIn(__cases_clauses_return_Return8));

// ReturnOrderBy1 (12 scenarios)
static auto __cases_clauses_return_orderby_ReturnOrderBy1 = LoadCasesFromJSON(std::string(CORRECTNESS_JSON_DIR) + "/clauses/return-orderby/ReturnOrderBy1.json");
INSTANTIATE_TEST_SUITE_P(
    clauses_return_orderby_ReturnOrderBy1,
    CorrectnessTest,
    ::testing::ValuesIn(__cases_clauses_return_orderby_ReturnOrderBy1));

// ReturnOrderBy2 (14 scenarios)
static auto __cases_clauses_return_orderby_ReturnOrderBy2 = LoadCasesFromJSON(std::string(CORRECTNESS_JSON_DIR) + "/clauses/return-orderby/ReturnOrderBy2.json");
INSTANTIATE_TEST_SUITE_P(
    clauses_return_orderby_ReturnOrderBy2,
    CorrectnessTest,
    ::testing::ValuesIn(__cases_clauses_return_orderby_ReturnOrderBy2));

// ReturnOrderBy3 (1 scenarios)
static auto __cases_clauses_return_orderby_ReturnOrderBy3 = LoadCasesFromJSON(std::string(CORRECTNESS_JSON_DIR) + "/clauses/return-orderby/ReturnOrderBy3.json");
INSTANTIATE_TEST_SUITE_P(
    clauses_return_orderby_ReturnOrderBy3,
    CorrectnessTest,
    ::testing::ValuesIn(__cases_clauses_return_orderby_ReturnOrderBy3));

// ReturnOrderBy4 (2 scenarios)
static auto __cases_clauses_return_orderby_ReturnOrderBy4 = LoadCasesFromJSON(std::string(CORRECTNESS_JSON_DIR) + "/clauses/return-orderby/ReturnOrderBy4.json");
INSTANTIATE_TEST_SUITE_P(
    clauses_return_orderby_ReturnOrderBy4,
    CorrectnessTest,
    ::testing::ValuesIn(__cases_clauses_return_orderby_ReturnOrderBy4));

// ReturnOrderBy5 (1 scenarios)
static auto __cases_clauses_return_orderby_ReturnOrderBy5 = LoadCasesFromJSON(std::string(CORRECTNESS_JSON_DIR) + "/clauses/return-orderby/ReturnOrderBy5.json");
INSTANTIATE_TEST_SUITE_P(
    clauses_return_orderby_ReturnOrderBy5,
    CorrectnessTest,
    ::testing::ValuesIn(__cases_clauses_return_orderby_ReturnOrderBy5));

// ReturnOrderBy6 (5 scenarios)
static auto __cases_clauses_return_orderby_ReturnOrderBy6 = LoadCasesFromJSON(std::string(CORRECTNESS_JSON_DIR) + "/clauses/return-orderby/ReturnOrderBy6.json");
INSTANTIATE_TEST_SUITE_P(
    clauses_return_orderby_ReturnOrderBy6,
    CorrectnessTest,
    ::testing::ValuesIn(__cases_clauses_return_orderby_ReturnOrderBy6));

// ReturnSkipLimit1 (11 scenarios)
static auto __cases_clauses_return_skip_limit_ReturnSkipLimit1 = LoadCasesFromJSON(std::string(CORRECTNESS_JSON_DIR) + "/clauses/return-skip-limit/ReturnSkipLimit1.json");
INSTANTIATE_TEST_SUITE_P(
    clauses_return_skip_limit_ReturnSkipLimit1,
    CorrectnessTest,
    ::testing::ValuesIn(__cases_clauses_return_skip_limit_ReturnSkipLimit1));

// ReturnSkipLimit2 (17 scenarios)
static auto __cases_clauses_return_skip_limit_ReturnSkipLimit2 = LoadCasesFromJSON(std::string(CORRECTNESS_JSON_DIR) + "/clauses/return-skip-limit/ReturnSkipLimit2.json");
INSTANTIATE_TEST_SUITE_P(
    clauses_return_skip_limit_ReturnSkipLimit2,
    CorrectnessTest,
    ::testing::ValuesIn(__cases_clauses_return_skip_limit_ReturnSkipLimit2));

// ReturnSkipLimit3 (3 scenarios)
static auto __cases_clauses_return_skip_limit_ReturnSkipLimit3 = LoadCasesFromJSON(std::string(CORRECTNESS_JSON_DIR) + "/clauses/return-skip-limit/ReturnSkipLimit3.json");
INSTANTIATE_TEST_SUITE_P(
    clauses_return_skip_limit_ReturnSkipLimit3,
    CorrectnessTest,
    ::testing::ValuesIn(__cases_clauses_return_skip_limit_ReturnSkipLimit3));

// Aggregation1 (2 scenarios)
static auto __cases_expressions_aggregation_Aggregation1 = LoadCasesFromJSON(std::string(CORRECTNESS_JSON_DIR) + "/expressions/aggregation/Aggregation1.json");
INSTANTIATE_TEST_SUITE_P(
    expressions_aggregation_Aggregation1,
    CorrectnessTest,
    ::testing::ValuesIn(__cases_expressions_aggregation_Aggregation1));

// Aggregation2 (12 scenarios)
static auto __cases_expressions_aggregation_Aggregation2 = LoadCasesFromJSON(std::string(CORRECTNESS_JSON_DIR) + "/expressions/aggregation/Aggregation2.json");
INSTANTIATE_TEST_SUITE_P(
    expressions_aggregation_Aggregation2,
    CorrectnessTest,
    ::testing::ValuesIn(__cases_expressions_aggregation_Aggregation2));

// Aggregation3 (2 scenarios)
static auto __cases_expressions_aggregation_Aggregation3 = LoadCasesFromJSON(std::string(CORRECTNESS_JSON_DIR) + "/expressions/aggregation/Aggregation3.json");
INSTANTIATE_TEST_SUITE_P(
    expressions_aggregation_Aggregation3,
    CorrectnessTest,
    ::testing::ValuesIn(__cases_expressions_aggregation_Aggregation3));

// Aggregation5 (2 scenarios)
static auto __cases_expressions_aggregation_Aggregation5 = LoadCasesFromJSON(std::string(CORRECTNESS_JSON_DIR) + "/expressions/aggregation/Aggregation5.json");
INSTANTIATE_TEST_SUITE_P(
    expressions_aggregation_Aggregation5,
    CorrectnessTest,
    ::testing::ValuesIn(__cases_expressions_aggregation_Aggregation5));

// Aggregation6 (13 scenarios)
static auto __cases_expressions_aggregation_Aggregation6 = LoadCasesFromJSON(std::string(CORRECTNESS_JSON_DIR) + "/expressions/aggregation/Aggregation6.json");
INSTANTIATE_TEST_SUITE_P(
    expressions_aggregation_Aggregation6,
    CorrectnessTest,
    ::testing::ValuesIn(__cases_expressions_aggregation_Aggregation6));

// Aggregation8 (4 scenarios)
static auto __cases_expressions_aggregation_Aggregation8 = LoadCasesFromJSON(std::string(CORRECTNESS_JSON_DIR) + "/expressions/aggregation/Aggregation8.json");
INSTANTIATE_TEST_SUITE_P(
    expressions_aggregation_Aggregation8,
    CorrectnessTest,
    ::testing::ValuesIn(__cases_expressions_aggregation_Aggregation8));

// Boolean1 (30 scenarios)
static auto __cases_expressions_boolean_Boolean1 = LoadCasesFromJSON(std::string(CORRECTNESS_JSON_DIR) + "/expressions/boolean/Boolean1.json");
INSTANTIATE_TEST_SUITE_P(
    expressions_boolean_Boolean1,
    CorrectnessTest,
    ::testing::ValuesIn(__cases_expressions_boolean_Boolean1));

// Boolean2 (30 scenarios)
static auto __cases_expressions_boolean_Boolean2 = LoadCasesFromJSON(std::string(CORRECTNESS_JSON_DIR) + "/expressions/boolean/Boolean2.json");
INSTANTIATE_TEST_SUITE_P(
    expressions_boolean_Boolean2,
    CorrectnessTest,
    ::testing::ValuesIn(__cases_expressions_boolean_Boolean2));

// Boolean3 (30 scenarios)
static auto __cases_expressions_boolean_Boolean3 = LoadCasesFromJSON(std::string(CORRECTNESS_JSON_DIR) + "/expressions/boolean/Boolean3.json");
INSTANTIATE_TEST_SUITE_P(
    expressions_boolean_Boolean3,
    CorrectnessTest,
    ::testing::ValuesIn(__cases_expressions_boolean_Boolean3));

// Boolean4 (52 scenarios)
static auto __cases_expressions_boolean_Boolean4 = LoadCasesFromJSON(std::string(CORRECTNESS_JSON_DIR) + "/expressions/boolean/Boolean4.json");
INSTANTIATE_TEST_SUITE_P(
    expressions_boolean_Boolean4,
    CorrectnessTest,
    ::testing::ValuesIn(__cases_expressions_boolean_Boolean4));

// Boolean5 (8 scenarios)
static auto __cases_expressions_boolean_Boolean5 = LoadCasesFromJSON(std::string(CORRECTNESS_JSON_DIR) + "/expressions/boolean/Boolean5.json");
INSTANTIATE_TEST_SUITE_P(
    expressions_boolean_Boolean5,
    CorrectnessTest,
    ::testing::ValuesIn(__cases_expressions_boolean_Boolean5));

// Comparison1 (43 scenarios)
static auto __cases_expressions_comparison_Comparison1 = LoadCasesFromJSON(std::string(CORRECTNESS_JSON_DIR) + "/expressions/comparison/Comparison1.json");
INSTANTIATE_TEST_SUITE_P(
    expressions_comparison_Comparison1,
    CorrectnessTest,
    ::testing::ValuesIn(__cases_expressions_comparison_Comparison1));

// Comparison2 (19 scenarios)
static auto __cases_expressions_comparison_Comparison2 = LoadCasesFromJSON(std::string(CORRECTNESS_JSON_DIR) + "/expressions/comparison/Comparison2.json");
INSTANTIATE_TEST_SUITE_P(
    expressions_comparison_Comparison2,
    CorrectnessTest,
    ::testing::ValuesIn(__cases_expressions_comparison_Comparison2));

// Comparison3 (9 scenarios)
static auto __cases_expressions_comparison_Comparison3 = LoadCasesFromJSON(std::string(CORRECTNESS_JSON_DIR) + "/expressions/comparison/Comparison3.json");
INSTANTIATE_TEST_SUITE_P(
    expressions_comparison_Comparison3,
    CorrectnessTest,
    ::testing::ValuesIn(__cases_expressions_comparison_Comparison3));

// Comparison4 (1 scenarios)
static auto __cases_expressions_comparison_Comparison4 = LoadCasesFromJSON(std::string(CORRECTNESS_JSON_DIR) + "/expressions/comparison/Comparison4.json");
INSTANTIATE_TEST_SUITE_P(
    expressions_comparison_Comparison4,
    CorrectnessTest,
    ::testing::ValuesIn(__cases_expressions_comparison_Comparison4));

// Literals1 (6 scenarios)
static auto __cases_expressions_literals_Literals1 = LoadCasesFromJSON(std::string(CORRECTNESS_JSON_DIR) + "/expressions/literals/Literals1.json");
INSTANTIATE_TEST_SUITE_P(
    expressions_literals_Literals1,
    CorrectnessTest,
    ::testing::ValuesIn(__cases_expressions_literals_Literals1));

// Literals2 (12 scenarios)
static auto __cases_expressions_literals_Literals2 = LoadCasesFromJSON(std::string(CORRECTNESS_JSON_DIR) + "/expressions/literals/Literals2.json");
INSTANTIATE_TEST_SUITE_P(
    expressions_literals_Literals2,
    CorrectnessTest,
    ::testing::ValuesIn(__cases_expressions_literals_Literals2));

// Literals3 (16 scenarios)
static auto __cases_expressions_literals_Literals3 = LoadCasesFromJSON(std::string(CORRECTNESS_JSON_DIR) + "/expressions/literals/Literals3.json");
INSTANTIATE_TEST_SUITE_P(
    expressions_literals_Literals3,
    CorrectnessTest,
    ::testing::ValuesIn(__cases_expressions_literals_Literals3));

// Literals4 (10 scenarios)
static auto __cases_expressions_literals_Literals4 = LoadCasesFromJSON(std::string(CORRECTNESS_JSON_DIR) + "/expressions/literals/Literals4.json");
INSTANTIATE_TEST_SUITE_P(
    expressions_literals_Literals4,
    CorrectnessTest,
    ::testing::ValuesIn(__cases_expressions_literals_Literals4));

// Literals5 (27 scenarios)
static auto __cases_expressions_literals_Literals5 = LoadCasesFromJSON(std::string(CORRECTNESS_JSON_DIR) + "/expressions/literals/Literals5.json");
INSTANTIATE_TEST_SUITE_P(
    expressions_literals_Literals5,
    CorrectnessTest,
    ::testing::ValuesIn(__cases_expressions_literals_Literals5));

// Literals6 (13 scenarios)
static auto __cases_expressions_literals_Literals6 = LoadCasesFromJSON(std::string(CORRECTNESS_JSON_DIR) + "/expressions/literals/Literals6.json");
INSTANTIATE_TEST_SUITE_P(
    expressions_literals_Literals6,
    CorrectnessTest,
    ::testing::ValuesIn(__cases_expressions_literals_Literals6));

// Literals7 (20 scenarios)
static auto __cases_expressions_literals_Literals7 = LoadCasesFromJSON(std::string(CORRECTNESS_JSON_DIR) + "/expressions/literals/Literals7.json");
INSTANTIATE_TEST_SUITE_P(
    expressions_literals_Literals7,
    CorrectnessTest,
    ::testing::ValuesIn(__cases_expressions_literals_Literals7));

// Literals8 (27 scenarios)
static auto __cases_expressions_literals_Literals8 = LoadCasesFromJSON(std::string(CORRECTNESS_JSON_DIR) + "/expressions/literals/Literals8.json");
INSTANTIATE_TEST_SUITE_P(
    expressions_literals_Literals8,
    CorrectnessTest,
    ::testing::ValuesIn(__cases_expressions_literals_Literals8));

// Mathematical11 (1 scenarios)
static auto __cases_expressions_mathematical_Mathematical11 = LoadCasesFromJSON(std::string(CORRECTNESS_JSON_DIR) + "/expressions/mathematical/Mathematical11.json");
INSTANTIATE_TEST_SUITE_P(
    expressions_mathematical_Mathematical11,
    CorrectnessTest,
    ::testing::ValuesIn(__cases_expressions_mathematical_Mathematical11));

// Mathematical13 (1 scenarios)
static auto __cases_expressions_mathematical_Mathematical13 = LoadCasesFromJSON(std::string(CORRECTNESS_JSON_DIR) + "/expressions/mathematical/Mathematical13.json");
INSTANTIATE_TEST_SUITE_P(
    expressions_mathematical_Mathematical13,
    CorrectnessTest,
    ::testing::ValuesIn(__cases_expressions_mathematical_Mathematical13));

// Mathematical2 (1 scenarios)
static auto __cases_expressions_mathematical_Mathematical2 = LoadCasesFromJSON(std::string(CORRECTNESS_JSON_DIR) + "/expressions/mathematical/Mathematical2.json");
INSTANTIATE_TEST_SUITE_P(
    expressions_mathematical_Mathematical2,
    CorrectnessTest,
    ::testing::ValuesIn(__cases_expressions_mathematical_Mathematical2));

// Mathematical3 (1 scenarios)
static auto __cases_expressions_mathematical_Mathematical3 = LoadCasesFromJSON(std::string(CORRECTNESS_JSON_DIR) + "/expressions/mathematical/Mathematical3.json");
INSTANTIATE_TEST_SUITE_P(
    expressions_mathematical_Mathematical3,
    CorrectnessTest,
    ::testing::ValuesIn(__cases_expressions_mathematical_Mathematical3));

// Mathematical8 (2 scenarios)
static auto __cases_expressions_mathematical_Mathematical8 = LoadCasesFromJSON(std::string(CORRECTNESS_JSON_DIR) + "/expressions/mathematical/Mathematical8.json");
INSTANTIATE_TEST_SUITE_P(
    expressions_mathematical_Mathematical8,
    CorrectnessTest,
    ::testing::ValuesIn(__cases_expressions_mathematical_Mathematical8));

// Null1 (17 scenarios)
static auto __cases_expressions_null_Null1 = LoadCasesFromJSON(std::string(CORRECTNESS_JSON_DIR) + "/expressions/null/Null1.json");
INSTANTIATE_TEST_SUITE_P(
    expressions_null_Null1,
    CorrectnessTest,
    ::testing::ValuesIn(__cases_expressions_null_Null1));

// Null2 (17 scenarios)
static auto __cases_expressions_null_Null2 = LoadCasesFromJSON(std::string(CORRECTNESS_JSON_DIR) + "/expressions/null/Null2.json");
INSTANTIATE_TEST_SUITE_P(
    expressions_null_Null2,
    CorrectnessTest,
    ::testing::ValuesIn(__cases_expressions_null_Null2));

// Null3 (10 scenarios)
static auto __cases_expressions_null_Null3 = LoadCasesFromJSON(std::string(CORRECTNESS_JSON_DIR) + "/expressions/null/Null3.json");
INSTANTIATE_TEST_SUITE_P(
    expressions_null_Null3,
    CorrectnessTest,
    ::testing::ValuesIn(__cases_expressions_null_Null3));

// Pattern1 (39 scenarios)
static auto __cases_expressions_pattern_Pattern1 = LoadCasesFromJSON(std::string(CORRECTNESS_JSON_DIR) + "/expressions/pattern/Pattern1.json");
INSTANTIATE_TEST_SUITE_P(
    expressions_pattern_Pattern1,
    CorrectnessTest,
    ::testing::ValuesIn(__cases_expressions_pattern_Pattern1));

// Pattern2 (11 scenarios)
static auto __cases_expressions_pattern_Pattern2 = LoadCasesFromJSON(std::string(CORRECTNESS_JSON_DIR) + "/expressions/pattern/Pattern2.json");
INSTANTIATE_TEST_SUITE_P(
    expressions_pattern_Pattern2,
    CorrectnessTest,
    ::testing::ValuesIn(__cases_expressions_pattern_Pattern2));

// Precedence1 (72 scenarios)
static auto __cases_expressions_precedence_Precedence1 = LoadCasesFromJSON(std::string(CORRECTNESS_JSON_DIR) + "/expressions/precedence/Precedence1.json");
INSTANTIATE_TEST_SUITE_P(
    expressions_precedence_Precedence1,
    CorrectnessTest,
    ::testing::ValuesIn(__cases_expressions_precedence_Precedence1));

// Precedence2 (26 scenarios)
static auto __cases_expressions_precedence_Precedence2 = LoadCasesFromJSON(std::string(CORRECTNESS_JSON_DIR) + "/expressions/precedence/Precedence2.json");
INSTANTIATE_TEST_SUITE_P(
    expressions_precedence_Precedence2,
    CorrectnessTest,
    ::testing::ValuesIn(__cases_expressions_precedence_Precedence2));

// Precedence3 (11 scenarios)
static auto __cases_expressions_precedence_Precedence3 = LoadCasesFromJSON(std::string(CORRECTNESS_JSON_DIR) + "/expressions/precedence/Precedence3.json");
INSTANTIATE_TEST_SUITE_P(
    expressions_precedence_Precedence3,
    CorrectnessTest,
    ::testing::ValuesIn(__cases_expressions_precedence_Precedence3));

// Precedence4 (12 scenarios)
static auto __cases_expressions_precedence_Precedence4 = LoadCasesFromJSON(std::string(CORRECTNESS_JSON_DIR) + "/expressions/precedence/Precedence4.json");
INSTANTIATE_TEST_SUITE_P(
    expressions_precedence_Precedence4,
    CorrectnessTest,
    ::testing::ValuesIn(__cases_expressions_precedence_Precedence4));

