// TCK-based Cypher correctness tests.
// Loads JSON test case files generated by scripts/extract_tck.py
// and executes them against the query engine.
//
// Registration file: tests/correctness_registration.cpp (auto-generated
// by scripts/extract_tck.py --gen-cpp)

#include <filesystem>
#include <fstream>
#include <sstream>
#include <string>

#include <folly/coro/BlockingWait.h>
#include <folly/coro/Task.h>
#include <folly/executors/InlineExecutor.h>

#include "gtest/gtest.h"
#include "json_parser.h"

#include "storage/io_scheduler.hpp"
#include "query/executor/query_executor.hpp"
#include "query/executor/row.hpp"
#include "storage/data/async_graph_data_store.hpp"
#include "storage/data/sync_graph_data_store.hpp"
#include "storage/meta/async_graph_meta_store.hpp"
#include "storage/meta/sync_graph_meta_store.hpp"

using namespace eugraph;
using namespace eugraph::compute;
using namespace folly::coro;
namespace fs = std::filesystem;

// ── Test case data structure ──────────────────────────────────────

struct CorrectnessCase {
    std::string id;
    std::string description;
    std::vector<std::string> setup;
    std::string query;
    std::vector<std::string> expectColumns;
    std::vector<std::vector<std::string>> expectRows;
    bool ordered = false;
    std::vector<std::string> requiresFeatures;
    bool isError = false;
    std::string errorType;
    std::string errorContains;
    std::string sourceFile;
    std::string skipReason;
};

// ── JSON loading ──────────────────────────────────────────────────

static std::string extractArrayContent(const std::string& json,
                                       const std::string& key) {
    std::string search = "\"" + key + "\"";
    size_t pos = json.find(search);
    if (pos == std::string::npos) return "";
    pos = json.find('[', pos + search.size());
    if (pos == std::string::npos) return "";
    int depth = 1;
    size_t end = pos + 1;
    bool inString = false;
    while (end < json.size() && depth > 0) {
        char c = json[end];
        if (c == '"' && (end == 0 || json[end - 1] != '\\'))
            inString = !inString;
        else if (!inString) {
            if (c == '[') depth++;
            else if (c == ']') depth--;
        }
        end++;
    }
    return json.substr(pos, end - pos);
}

std::vector<CorrectnessCase> LoadCasesFromJSON(const std::string& path) {
    std::vector<CorrectnessCase> cases;
    std::ifstream file(path);
    if (!file.is_open()) return cases;
    std::stringstream buf;
    buf << file.rdbuf();
    std::string content = buf.str();
    std::string sourceFile = fs::path(path).filename().string();

    std::string arrStr = extractArrayContent(content, "scenarios");
    if (arrStr.empty()) return cases;

    size_t pos = 1;
    while (pos < arrStr.size()) {
        while (pos < arrStr.size() && std::isspace(arrStr[pos])) pos++;
        if (pos >= arrStr.size() || arrStr[pos] == ']') break;

        int depth = 0;
        size_t start = pos;
        bool inStr = false;
        while (pos < arrStr.size()) {
            char c = arrStr[pos];
            if (c == '"' && (pos == 0 || arrStr[pos - 1] != '\\'))
                inStr = !inStr;
            else if (!inStr) {
                if (c == '{') depth++;
                else if (c == '}') {
                    depth--;
                    if (depth == 0) { pos++; break; }
                }
            }
            pos++;
        }
        std::string objStr = arrStr.substr(start, pos - start);

        try {
            json::Parser p(objStr);
            json::Object obj = p.parseObject();
            CorrectnessCase tc;
            tc.sourceFile = sourceFile;
            tc.id = obj.getString("id").value_or("");
            tc.description = obj.getString("description").value_or("");
            tc.setup = obj.getStringArray("setup")
                           .value_or(std::vector<std::string>{});
            tc.query = obj.getString("query").value_or("");
            tc.expectColumns = obj.getStringArray("expect_columns")
                                   .value_or(std::vector<std::string>{});
            tc.expectRows = obj.getStringMatrix("expect_rows")
                                .value_or(std::vector<std::vector<std::string>>{});
            tc.ordered = obj.getBool("ordered").value_or(false);
            tc.requiresFeatures = obj.getStringArray("requires")
                                      .value_or(std::vector<std::string>{});
            tc.isError = obj.getBool("is_error").value_or(false);
            tc.errorType = obj.getString("error_type").value_or("");
            tc.errorContains = obj.getString("error_contains").value_or("");
            tc.skipReason = obj.getString("skip_reason").value_or("");
            if (!tc.query.empty()) cases.push_back(std::move(tc));
        } catch (const json::ParseError&) {
            // Skip malformed scenarios
        }
        while (pos < arrStr.size() && std::isspace(arrStr[pos])) pos++;
        if (pos < arrStr.size() && arrStr[pos] == ',') pos++;
    }
    return cases;
}

// ── Value conversion helpers ──────────────────────────────────────

static std::string valueToString(const Value& v) {
    return std::visit(
        [](const auto& arg) -> std::string {
            using T = std::decay_t<decltype(arg)>;
            if constexpr (std::is_same_v<T, std::monostate>)
                return "null";
            else if constexpr (std::is_same_v<T, bool>)
                return arg ? "true" : "false";
            else if constexpr (std::is_same_v<T, int64_t>)
                return std::to_string(arg);
            else if constexpr (std::is_same_v<T, double>) {
                if (arg == static_cast<int64_t>(arg))
                    return std::to_string(static_cast<int64_t>(arg));
                return std::to_string(arg);
            }
            else if constexpr (std::is_same_v<T, std::string>)
                return arg;
            else if constexpr (std::is_same_v<T, VertexValue>) {
                // Simplified: VertexValue uses LabelIds and Properties,
                // not human-readable names. Full comparison needs catalog.
                std::string s = "(:vertex";
                if (arg.labels && !arg.labels->empty())
                    s += " labels=" + std::to_string(arg.labels->size());
                if (!arg.properties.empty())
                    s += " props=" + std::to_string(arg.properties.size());
                return s + ")";
            }
            else if constexpr (std::is_same_v<T, EdgeValue>)
                return "[:EDGE]";
            else if constexpr (std::is_same_v<T, PathValue>)
                return "[:PATH]";
            else if constexpr (std::is_same_v<T, ListValue>)
                return "[:LIST]";
            return "?";
        },
        v);
}

// ── Test Fixture ──────────────────────────────────────────────────

class CorrectnessTest : public ::testing::TestWithParam<CorrectnessCase> {
protected:
    void SetUp() override {
        dbPath_ = "/tmp/eugraph_correctness_" +
                  std::to_string(getpid()) + "_" +
                  std::to_string(testCounter_++);

        syncData_ = std::make_unique<SyncGraphDataStore>();
        syncMeta_ = std::make_unique<SyncGraphMetaStore>();
        ASSERT_TRUE(syncData_->open(dbPath_ + "/data"));
        ASSERT_TRUE(syncMeta_->open(dbPath_ + "/meta"));

        scheduler_ = std::make_shared<IoScheduler>(2);
        asyncData_ = std::make_unique<AsyncGraphDataStore>(*syncData_, *scheduler_);
        asyncMeta_ = std::make_unique<AsyncGraphMetaStore>();
        bool opened = folly::coro::blockingWait(
            asyncMeta_->open(*syncMeta_, *scheduler_));
        ASSERT_TRUE(opened);

        executor_ = std::make_unique<QueryExecutor>(
            *asyncData_, *asyncMeta_, QueryExecutor::Config{});
    }

    void TearDown() override {
        executor_.reset();
        asyncData_.reset();
        asyncMeta_.reset();
        scheduler_.reset();
        syncData_.reset();
        syncMeta_.reset();
        if (!dbPath_.empty())
            std::filesystem::remove_all(dbPath_);
    }

    ExecutionResult execSync(const std::string& query) {
        auto ctx = blockingWait(executor_->prepareStream(query));
        ExecutionResult result;
        if (!ctx->error.empty()) {
            result.error = std::move(ctx->error);
            return result;
        }
        result.columns = std::move(ctx->columns);
        auto gen = std::move(ctx->gen);
        blockingWait(co_invoke([&]() -> Task<void> {
            while (auto chunk = co_await gen.next()) {
                auto rows = chunk->toRows();
                for (auto& row : rows)
                    result.rows.push_back(std::move(row));
            }
            if (ctx->should_commit)
                co_await ctx->store.commitTran(ctx->txn);
        }));
        return result;
    }

    std::string dbPath_;
    std::unique_ptr<SyncGraphDataStore> syncData_;
    std::unique_ptr<SyncGraphMetaStore> syncMeta_;
    std::shared_ptr<IoScheduler> scheduler_;
    std::unique_ptr<AsyncGraphMetaStore> asyncMeta_;
    std::unique_ptr<AsyncGraphDataStore> asyncData_;
    std::unique_ptr<QueryExecutor> executor_;
    static inline int testCounter_ = 0;
};

// ── Per-scenario test ─────────────────────────────────────────────

TEST_P(CorrectnessTest, Run) {
    const auto& tc = GetParam();

    // Honor skip_reason from JSON
    if (!tc.skipReason.empty()) {
        GTEST_SKIP() << "skip: " << tc.skipReason;
    }

    // Execute setup statements
    for (const auto& stmt : tc.setup) {
        auto result = execSync(stmt);
        if (!result.error.empty()) {
            GTEST_SKIP() << "Setup failed: " << result.error;
            return;
        }
    }

    auto result = execSync(tc.query);

    if (tc.isError) {
        if (result.error.empty()) {
            FAIL() << "Expected error (" << tc.errorType
                   << ": " << tc.errorContains
                   << ") but query succeeded";
            return;
        }
        if (!tc.errorContains.empty()) {
            bool found =
                result.error.find(tc.errorContains) != std::string::npos;
            EXPECT_TRUE(found)
                << "Error mismatch.\n"
                << "  Expected to contain: " << tc.errorContains << "\n"
                << "  Actual: " << result.error;
        }
        return;
    }

    if (!result.error.empty()) {
        FAIL() << "Query failed: " << result.error;
        return;
    }

    // Compare columns
    if (!tc.expectColumns.empty()) {
        EXPECT_EQ(result.columns.size(), tc.expectColumns.size())
            << "Column count mismatch";
    }

    // Compare rows
    EXPECT_EQ(result.rows.size(), tc.expectRows.size())
        << "Row count mismatch";

    size_t nRows = std::min(result.rows.size(), tc.expectRows.size());
    for (size_t r = 0; r < nRows; r++) {
        const auto& actualRow = result.rows[r];
        const auto& expectRow = tc.expectRows[r];
        EXPECT_EQ(actualRow.size(), expectRow.size())
            << "Row " << r << " column count";
        size_t nCols = std::min(actualRow.size(), expectRow.size());
        for (size_t c = 0; c < nCols; c++) {
            std::string actualStr = valueToString(actualRow[c]);
            EXPECT_EQ(actualStr, expectRow[c])
                << "Row " << r << " Col " << c;
        }
    }
}

// ── Include auto-generated registration ───────────────────────────
#include "correctness_registration.cpp"
