/**
 * Autogenerated by Thrift for /mnt/f/code/eugraph/proto/eugraph.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated @nocommit
 */
#include "gen-cpp2/eugraph_types.tcc"

namespace eugraph::thrift {

template void PropertyDefThrift::readNoXfer<>(apache::thrift::CompactProtocolReader*);
template uint32_t PropertyDefThrift::write<>(apache::thrift::CompactProtocolWriter*) const;
template uint32_t PropertyDefThrift::serializedSize<>(apache::thrift::CompactProtocolWriter const*) const;
template uint32_t PropertyDefThrift::serializedSizeZC<>(apache::thrift::CompactProtocolWriter const*) const;

template void PropertyValueThrift::readNoXfer<>(apache::thrift::CompactProtocolReader*);
template uint32_t PropertyValueThrift::write<>(apache::thrift::CompactProtocolWriter*) const;
template uint32_t PropertyValueThrift::serializedSize<>(apache::thrift::CompactProtocolWriter const*) const;
template uint32_t PropertyValueThrift::serializedSizeZC<>(apache::thrift::CompactProtocolWriter const*) const;

template void LabelInfo::readNoXfer<>(apache::thrift::CompactProtocolReader*);
template uint32_t LabelInfo::write<>(apache::thrift::CompactProtocolWriter*) const;
template uint32_t LabelInfo::serializedSize<>(apache::thrift::CompactProtocolWriter const*) const;
template uint32_t LabelInfo::serializedSizeZC<>(apache::thrift::CompactProtocolWriter const*) const;

template void EdgeLabelInfo::readNoXfer<>(apache::thrift::CompactProtocolReader*);
template uint32_t EdgeLabelInfo::write<>(apache::thrift::CompactProtocolWriter*) const;
template uint32_t EdgeLabelInfo::serializedSize<>(apache::thrift::CompactProtocolWriter const*) const;
template uint32_t EdgeLabelInfo::serializedSizeZC<>(apache::thrift::CompactProtocolWriter const*) const;

template void ResultValue::readNoXfer<>(apache::thrift::CompactProtocolReader*);
template uint32_t ResultValue::write<>(apache::thrift::CompactProtocolWriter*) const;
template uint32_t ResultValue::serializedSize<>(apache::thrift::CompactProtocolWriter const*) const;
template uint32_t ResultValue::serializedSizeZC<>(apache::thrift::CompactProtocolWriter const*) const;

template void ResultRow::readNoXfer<>(apache::thrift::CompactProtocolReader*);
template uint32_t ResultRow::write<>(apache::thrift::CompactProtocolWriter*) const;
template uint32_t ResultRow::serializedSize<>(apache::thrift::CompactProtocolWriter const*) const;
template uint32_t ResultRow::serializedSizeZC<>(apache::thrift::CompactProtocolWriter const*) const;

template void QueryResult::readNoXfer<>(apache::thrift::CompactProtocolReader*);
template uint32_t QueryResult::write<>(apache::thrift::CompactProtocolWriter*) const;
template uint32_t QueryResult::serializedSize<>(apache::thrift::CompactProtocolWriter const*) const;
template uint32_t QueryResult::serializedSizeZC<>(apache::thrift::CompactProtocolWriter const*) const;

} // namespace eugraph::thrift
