/**
 * Autogenerated by Thrift for proto/eugraph.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated @nocommit
 */
#pragma once

#include "gen-cpp2/eugraph_metadata.h"
#include <thrift/lib/cpp2/visitation/for_each.h>

namespace apache {
namespace thrift {
namespace detail {

template <>
struct ForEachField<::eugraph::thrift::PropertyDefThrift> {
  template <typename F, typename... T>
  void operator()([[maybe_unused]] F&& f, [[maybe_unused]] T&&... t) const {
    f(0, static_cast<T&&>(t).name_ref()...);
    f(1, static_cast<T&&>(t).type_ref()...);
    f(2, static_cast<T&&>(t).is_required_ref()...);
  }
};

template <>
struct ForEachField<::eugraph::thrift::PropertyValueThrift> {
  template <typename F, typename... T>
  void operator()([[maybe_unused]] F&& f, [[maybe_unused]] T&&... t) const {
    f(0, static_cast<T&&>(t).bool_val_ref()...);
    f(1, static_cast<T&&>(t).int_val_ref()...);
    f(2, static_cast<T&&>(t).double_val_ref()...);
    f(3, static_cast<T&&>(t).string_val_ref()...);
    f(4, static_cast<T&&>(t).int_array_ref()...);
    f(5, static_cast<T&&>(t).double_array_ref()...);
    f(6, static_cast<T&&>(t).string_array_ref()...);
  }
};

template <>
struct ForEachField<::eugraph::thrift::LabelInfo> {
  template <typename F, typename... T>
  void operator()([[maybe_unused]] F&& f, [[maybe_unused]] T&&... t) const {
    f(0, static_cast<T&&>(t).id_ref()...);
    f(1, static_cast<T&&>(t).name_ref()...);
    f(2, static_cast<T&&>(t).properties_ref()...);
  }
};

template <>
struct ForEachField<::eugraph::thrift::EdgeLabelInfo> {
  template <typename F, typename... T>
  void operator()([[maybe_unused]] F&& f, [[maybe_unused]] T&&... t) const {
    f(0, static_cast<T&&>(t).id_ref()...);
    f(1, static_cast<T&&>(t).name_ref()...);
    f(2, static_cast<T&&>(t).properties_ref()...);
    f(3, static_cast<T&&>(t).directed_ref()...);
  }
};

template <>
struct ForEachField<::eugraph::thrift::VertexRecord> {
  template <typename F, typename... T>
  void operator()([[maybe_unused]] F&& f, [[maybe_unused]] T&&... t) const {
    f(0, static_cast<T&&>(t).pk_value_ref()...);
    f(1, static_cast<T&&>(t).properties_ref()...);
  }
};

template <>
struct ForEachField<::eugraph::thrift::EdgeRecord> {
  template <typename F, typename... T>
  void operator()([[maybe_unused]] F&& f, [[maybe_unused]] T&&... t) const {
    f(0, static_cast<T&&>(t).src_vertex_id_ref()...);
    f(1, static_cast<T&&>(t).dst_vertex_id_ref()...);
    f(2, static_cast<T&&>(t).properties_ref()...);
  }
};

template <>
struct ForEachField<::eugraph::thrift::BatchInsertVerticesResult> {
  template <typename F, typename... T>
  void operator()([[maybe_unused]] F&& f, [[maybe_unused]] T&&... t) const {
    f(0, static_cast<T&&>(t).vertex_ids_ref()...);
    f(1, static_cast<T&&>(t).count_ref()...);
  }
};

template <>
struct ForEachField<::eugraph::thrift::ResultValue> {
  template <typename F, typename... T>
  void operator()([[maybe_unused]] F&& f, [[maybe_unused]] T&&... t) const {
    f(0, static_cast<T&&>(t).bool_val_ref()...);
    f(1, static_cast<T&&>(t).int_val_ref()...);
    f(2, static_cast<T&&>(t).double_val_ref()...);
    f(3, static_cast<T&&>(t).string_val_ref()...);
    f(4, static_cast<T&&>(t).vertex_json_ref()...);
    f(5, static_cast<T&&>(t).edge_json_ref()...);
  }
};

template <>
struct ForEachField<::eugraph::thrift::ResultRow> {
  template <typename F, typename... T>
  void operator()([[maybe_unused]] F&& f, [[maybe_unused]] T&&... t) const {
    f(0, static_cast<T&&>(t).values_ref()...);
  }
};

template <>
struct ForEachField<::eugraph::thrift::QueryResult> {
  template <typename F, typename... T>
  void operator()([[maybe_unused]] F&& f, [[maybe_unused]] T&&... t) const {
    f(0, static_cast<T&&>(t).columns_ref()...);
    f(1, static_cast<T&&>(t).rows_ref()...);
    f(2, static_cast<T&&>(t).rows_affected_ref()...);
    f(3, static_cast<T&&>(t).error_ref()...);
  }
};
} // namespace detail
} // namespace thrift
} // namespace apache
