/**
 * Autogenerated by Thrift for proto/eugraph.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated @nocommit
 */
#include <thrift/lib/cpp2/gen/module_metadata_cpp.h>
#include "gen-cpp2/eugraph_metadata.h"

// some of these functions can be so large that the compiler gives up optimizing
// them - and issues a warning which may be treated as an error!
//
// these functions are so rarely called that it is probably okay for them not to
// be optimized in practice
FOLLY_CLANG_DISABLE_WARNING("-Wignored-optimization-argument")

namespace apache {
namespace thrift {
namespace detail {
namespace md {
using ThriftMetadata = ::apache::thrift::metadata::ThriftMetadata;
using ThriftPrimitiveType = ::apache::thrift::metadata::ThriftPrimitiveType;
using ThriftType = ::apache::thrift::metadata::ThriftType;
using ThriftService = ::apache::thrift::metadata::ThriftService;
using ThriftServiceContext = ::apache::thrift::metadata::ThriftServiceContext;
using ThriftFunctionGenerator = void (*)(ThriftMetadata&, ThriftService&);

void EnumMetadata<::eugraph::thrift::PropertyType>::gen(ThriftMetadata& metadata) {
  auto res = metadata.enums()->emplace("eugraph.PropertyType", ::apache::thrift::metadata::ThriftEnum{});
  if (!res.second) {
    return;
  }
  ::apache::thrift::metadata::ThriftEnum& enum_metadata = res.first->second;
  enum_metadata.name() = "eugraph.PropertyType";
  using EnumTraits = TEnumTraits<::eugraph::thrift::PropertyType>;
  for (std::size_t i = 0; i != EnumTraits::size; ++i) {
    enum_metadata.elements()->emplace(static_cast<int32_t>(EnumTraits::values[i]), EnumTraits::names[i]);
  }
}

const ::apache::thrift::metadata::ThriftStruct&
StructMetadata<::eugraph::thrift::PropertyDefThrift>::gen(ThriftMetadata& metadata) {
  auto res = metadata.structs()->emplace("eugraph.PropertyDefThrift", ::apache::thrift::metadata::ThriftStruct{});
  if (!res.second) {
    return res.first->second;
  }
  ::apache::thrift::metadata::ThriftStruct& eugraph_PropertyDefThrift = res.first->second;
  eugraph_PropertyDefThrift.name() = "eugraph.PropertyDefThrift";
  eugraph_PropertyDefThrift.is_union() = false;
  static const auto* const
  eugraph_PropertyDefThrift_fields = new std::array<EncodedThriftField, 3>{ {
    { 1, "name", false, std::make_unique<Primitive>(ThriftPrimitiveType::THRIFT_STRING_TYPE), std::vector<ThriftConstStruct>{ }},    { 2, "type", false, std::make_unique<Enum<::eugraph::thrift::PropertyType>>("eugraph.PropertyType"), std::vector<ThriftConstStruct>{ }},    { 3, "is_required", false, std::make_unique<Primitive>(ThriftPrimitiveType::THRIFT_BOOL_TYPE), std::vector<ThriftConstStruct>{ }},  }};
  for (const auto& f : *eugraph_PropertyDefThrift_fields) {
    ::apache::thrift::metadata::ThriftField field;
    field.id() = f.id;
    field.name() = f.name;
    field.is_optional() = f.is_optional;
    f.metadata_type_interface->writeAndGenType(*field.type(), metadata);
    field.structured_annotations() = f.structured_annotations;
    eugraph_PropertyDefThrift.fields()->push_back(std::move(field));
  }
  return res.first->second;
}
const ::apache::thrift::metadata::ThriftStruct&
StructMetadata<::eugraph::thrift::PropertyValueThrift>::gen(ThriftMetadata& metadata) {
  auto res = metadata.structs()->emplace("eugraph.PropertyValueThrift", ::apache::thrift::metadata::ThriftStruct{});
  if (!res.second) {
    return res.first->second;
  }
  ::apache::thrift::metadata::ThriftStruct& eugraph_PropertyValueThrift = res.first->second;
  eugraph_PropertyValueThrift.name() = "eugraph.PropertyValueThrift";
  eugraph_PropertyValueThrift.is_union() = true;
  static const auto* const
  eugraph_PropertyValueThrift_fields = new std::array<EncodedThriftField, 7>{ {
    { 1, "bool_val", false, std::make_unique<Primitive>(ThriftPrimitiveType::THRIFT_BOOL_TYPE), std::vector<ThriftConstStruct>{ }},    { 2, "int_val", false, std::make_unique<Primitive>(ThriftPrimitiveType::THRIFT_I64_TYPE), std::vector<ThriftConstStruct>{ }},    { 3, "double_val", false, std::make_unique<Primitive>(ThriftPrimitiveType::THRIFT_DOUBLE_TYPE), std::vector<ThriftConstStruct>{ }},    { 4, "string_val", false, std::make_unique<Primitive>(ThriftPrimitiveType::THRIFT_STRING_TYPE), std::vector<ThriftConstStruct>{ }},    { 5, "int_array", false, std::make_unique<List>(std::make_unique<Primitive>(ThriftPrimitiveType::THRIFT_I64_TYPE)), std::vector<ThriftConstStruct>{ }},    { 6, "double_array", false, std::make_unique<List>(std::make_unique<Primitive>(ThriftPrimitiveType::THRIFT_DOUBLE_TYPE)), std::vector<ThriftConstStruct>{ }},    { 7, "string_array", false, std::make_unique<List>(std::make_unique<Primitive>(ThriftPrimitiveType::THRIFT_STRING_TYPE)), std::vector<ThriftConstStruct>{ }},  }};
  for (const auto& f : *eugraph_PropertyValueThrift_fields) {
    ::apache::thrift::metadata::ThriftField field;
    field.id() = f.id;
    field.name() = f.name;
    field.is_optional() = f.is_optional;
    f.metadata_type_interface->writeAndGenType(*field.type(), metadata);
    field.structured_annotations() = f.structured_annotations;
    eugraph_PropertyValueThrift.fields()->push_back(std::move(field));
  }
  return res.first->second;
}
const ::apache::thrift::metadata::ThriftStruct&
StructMetadata<::eugraph::thrift::LabelInfo>::gen(ThriftMetadata& metadata) {
  auto res = metadata.structs()->emplace("eugraph.LabelInfo", ::apache::thrift::metadata::ThriftStruct{});
  if (!res.second) {
    return res.first->second;
  }
  ::apache::thrift::metadata::ThriftStruct& eugraph_LabelInfo = res.first->second;
  eugraph_LabelInfo.name() = "eugraph.LabelInfo";
  eugraph_LabelInfo.is_union() = false;
  static const auto* const
  eugraph_LabelInfo_fields = new std::array<EncodedThriftField, 3>{ {
    { 1, "id", false, std::make_unique<Primitive>(ThriftPrimitiveType::THRIFT_I16_TYPE), std::vector<ThriftConstStruct>{ }},    { 2, "name", false, std::make_unique<Primitive>(ThriftPrimitiveType::THRIFT_STRING_TYPE), std::vector<ThriftConstStruct>{ }},    { 3, "properties", false, std::make_unique<List>(std::make_unique<Struct<::eugraph::thrift::PropertyDefThrift>>("eugraph.PropertyDefThrift")), std::vector<ThriftConstStruct>{ }},  }};
  for (const auto& f : *eugraph_LabelInfo_fields) {
    ::apache::thrift::metadata::ThriftField field;
    field.id() = f.id;
    field.name() = f.name;
    field.is_optional() = f.is_optional;
    f.metadata_type_interface->writeAndGenType(*field.type(), metadata);
    field.structured_annotations() = f.structured_annotations;
    eugraph_LabelInfo.fields()->push_back(std::move(field));
  }
  return res.first->second;
}
const ::apache::thrift::metadata::ThriftStruct&
StructMetadata<::eugraph::thrift::EdgeLabelInfo>::gen(ThriftMetadata& metadata) {
  auto res = metadata.structs()->emplace("eugraph.EdgeLabelInfo", ::apache::thrift::metadata::ThriftStruct{});
  if (!res.second) {
    return res.first->second;
  }
  ::apache::thrift::metadata::ThriftStruct& eugraph_EdgeLabelInfo = res.first->second;
  eugraph_EdgeLabelInfo.name() = "eugraph.EdgeLabelInfo";
  eugraph_EdgeLabelInfo.is_union() = false;
  static const auto* const
  eugraph_EdgeLabelInfo_fields = new std::array<EncodedThriftField, 4>{ {
    { 1, "id", false, std::make_unique<Primitive>(ThriftPrimitiveType::THRIFT_I16_TYPE), std::vector<ThriftConstStruct>{ }},    { 2, "name", false, std::make_unique<Primitive>(ThriftPrimitiveType::THRIFT_STRING_TYPE), std::vector<ThriftConstStruct>{ }},    { 3, "properties", false, std::make_unique<List>(std::make_unique<Struct<::eugraph::thrift::PropertyDefThrift>>("eugraph.PropertyDefThrift")), std::vector<ThriftConstStruct>{ }},    { 4, "directed", false, std::make_unique<Primitive>(ThriftPrimitiveType::THRIFT_BOOL_TYPE), std::vector<ThriftConstStruct>{ }},  }};
  for (const auto& f : *eugraph_EdgeLabelInfo_fields) {
    ::apache::thrift::metadata::ThriftField field;
    field.id() = f.id;
    field.name() = f.name;
    field.is_optional() = f.is_optional;
    f.metadata_type_interface->writeAndGenType(*field.type(), metadata);
    field.structured_annotations() = f.structured_annotations;
    eugraph_EdgeLabelInfo.fields()->push_back(std::move(field));
  }
  return res.first->second;
}
const ::apache::thrift::metadata::ThriftStruct&
StructMetadata<::eugraph::thrift::VertexRecord>::gen(ThriftMetadata& metadata) {
  auto res = metadata.structs()->emplace("eugraph.VertexRecord", ::apache::thrift::metadata::ThriftStruct{});
  if (!res.second) {
    return res.first->second;
  }
  ::apache::thrift::metadata::ThriftStruct& eugraph_VertexRecord = res.first->second;
  eugraph_VertexRecord.name() = "eugraph.VertexRecord";
  eugraph_VertexRecord.is_union() = false;
  static const auto* const
  eugraph_VertexRecord_fields = new std::array<EncodedThriftField, 2>{ {
    { 1, "pk_value", false, std::make_unique<Union<::eugraph::thrift::PropertyValueThrift>>("eugraph.PropertyValueThrift"), std::vector<ThriftConstStruct>{ }},    { 2, "properties", false, std::make_unique<List>(std::make_unique<Union<::eugraph::thrift::PropertyValueThrift>>("eugraph.PropertyValueThrift")), std::vector<ThriftConstStruct>{ }},  }};
  for (const auto& f : *eugraph_VertexRecord_fields) {
    ::apache::thrift::metadata::ThriftField field;
    field.id() = f.id;
    field.name() = f.name;
    field.is_optional() = f.is_optional;
    f.metadata_type_interface->writeAndGenType(*field.type(), metadata);
    field.structured_annotations() = f.structured_annotations;
    eugraph_VertexRecord.fields()->push_back(std::move(field));
  }
  return res.first->second;
}
const ::apache::thrift::metadata::ThriftStruct&
StructMetadata<::eugraph::thrift::EdgeRecord>::gen(ThriftMetadata& metadata) {
  auto res = metadata.structs()->emplace("eugraph.EdgeRecord", ::apache::thrift::metadata::ThriftStruct{});
  if (!res.second) {
    return res.first->second;
  }
  ::apache::thrift::metadata::ThriftStruct& eugraph_EdgeRecord = res.first->second;
  eugraph_EdgeRecord.name() = "eugraph.EdgeRecord";
  eugraph_EdgeRecord.is_union() = false;
  static const auto* const
  eugraph_EdgeRecord_fields = new std::array<EncodedThriftField, 3>{ {
    { 1, "src_vertex_id", false, std::make_unique<Primitive>(ThriftPrimitiveType::THRIFT_I64_TYPE), std::vector<ThriftConstStruct>{ }},    { 2, "dst_vertex_id", false, std::make_unique<Primitive>(ThriftPrimitiveType::THRIFT_I64_TYPE), std::vector<ThriftConstStruct>{ }},    { 3, "properties", false, std::make_unique<List>(std::make_unique<Union<::eugraph::thrift::PropertyValueThrift>>("eugraph.PropertyValueThrift")), std::vector<ThriftConstStruct>{ }},  }};
  for (const auto& f : *eugraph_EdgeRecord_fields) {
    ::apache::thrift::metadata::ThriftField field;
    field.id() = f.id;
    field.name() = f.name;
    field.is_optional() = f.is_optional;
    f.metadata_type_interface->writeAndGenType(*field.type(), metadata);
    field.structured_annotations() = f.structured_annotations;
    eugraph_EdgeRecord.fields()->push_back(std::move(field));
  }
  return res.first->second;
}
const ::apache::thrift::metadata::ThriftStruct&
StructMetadata<::eugraph::thrift::BatchInsertVerticesResult>::gen(ThriftMetadata& metadata) {
  auto res = metadata.structs()->emplace("eugraph.BatchInsertVerticesResult", ::apache::thrift::metadata::ThriftStruct{});
  if (!res.second) {
    return res.first->second;
  }
  ::apache::thrift::metadata::ThriftStruct& eugraph_BatchInsertVerticesResult = res.first->second;
  eugraph_BatchInsertVerticesResult.name() = "eugraph.BatchInsertVerticesResult";
  eugraph_BatchInsertVerticesResult.is_union() = false;
  static const auto* const
  eugraph_BatchInsertVerticesResult_fields = new std::array<EncodedThriftField, 2>{ {
    { 1, "vertex_ids", false, std::make_unique<List>(std::make_unique<Primitive>(ThriftPrimitiveType::THRIFT_I64_TYPE)), std::vector<ThriftConstStruct>{ }},    { 2, "count", false, std::make_unique<Primitive>(ThriftPrimitiveType::THRIFT_I32_TYPE), std::vector<ThriftConstStruct>{ }},  }};
  for (const auto& f : *eugraph_BatchInsertVerticesResult_fields) {
    ::apache::thrift::metadata::ThriftField field;
    field.id() = f.id;
    field.name() = f.name;
    field.is_optional() = f.is_optional;
    f.metadata_type_interface->writeAndGenType(*field.type(), metadata);
    field.structured_annotations() = f.structured_annotations;
    eugraph_BatchInsertVerticesResult.fields()->push_back(std::move(field));
  }
  return res.first->second;
}
const ::apache::thrift::metadata::ThriftStruct&
StructMetadata<::eugraph::thrift::ResultValue>::gen(ThriftMetadata& metadata) {
  auto res = metadata.structs()->emplace("eugraph.ResultValue", ::apache::thrift::metadata::ThriftStruct{});
  if (!res.second) {
    return res.first->second;
  }
  ::apache::thrift::metadata::ThriftStruct& eugraph_ResultValue = res.first->second;
  eugraph_ResultValue.name() = "eugraph.ResultValue";
  eugraph_ResultValue.is_union() = true;
  static const auto* const
  eugraph_ResultValue_fields = new std::array<EncodedThriftField, 6>{ {
    { 1, "bool_val", false, std::make_unique<Primitive>(ThriftPrimitiveType::THRIFT_BOOL_TYPE), std::vector<ThriftConstStruct>{ }},    { 2, "int_val", false, std::make_unique<Primitive>(ThriftPrimitiveType::THRIFT_I64_TYPE), std::vector<ThriftConstStruct>{ }},    { 3, "double_val", false, std::make_unique<Primitive>(ThriftPrimitiveType::THRIFT_DOUBLE_TYPE), std::vector<ThriftConstStruct>{ }},    { 4, "string_val", false, std::make_unique<Primitive>(ThriftPrimitiveType::THRIFT_STRING_TYPE), std::vector<ThriftConstStruct>{ }},    { 5, "vertex_json", false, std::make_unique<Primitive>(ThriftPrimitiveType::THRIFT_STRING_TYPE), std::vector<ThriftConstStruct>{ }},    { 6, "edge_json", false, std::make_unique<Primitive>(ThriftPrimitiveType::THRIFT_STRING_TYPE), std::vector<ThriftConstStruct>{ }},  }};
  for (const auto& f : *eugraph_ResultValue_fields) {
    ::apache::thrift::metadata::ThriftField field;
    field.id() = f.id;
    field.name() = f.name;
    field.is_optional() = f.is_optional;
    f.metadata_type_interface->writeAndGenType(*field.type(), metadata);
    field.structured_annotations() = f.structured_annotations;
    eugraph_ResultValue.fields()->push_back(std::move(field));
  }
  return res.first->second;
}
const ::apache::thrift::metadata::ThriftStruct&
StructMetadata<::eugraph::thrift::ResultRow>::gen(ThriftMetadata& metadata) {
  auto res = metadata.structs()->emplace("eugraph.ResultRow", ::apache::thrift::metadata::ThriftStruct{});
  if (!res.second) {
    return res.first->second;
  }
  ::apache::thrift::metadata::ThriftStruct& eugraph_ResultRow = res.first->second;
  eugraph_ResultRow.name() = "eugraph.ResultRow";
  eugraph_ResultRow.is_union() = false;
  static const auto* const
  eugraph_ResultRow_fields = new std::array<EncodedThriftField, 1>{ {
    { 1, "values", false, std::make_unique<List>(std::make_unique<Union<::eugraph::thrift::ResultValue>>("eugraph.ResultValue")), std::vector<ThriftConstStruct>{ }},  }};
  for (const auto& f : *eugraph_ResultRow_fields) {
    ::apache::thrift::metadata::ThriftField field;
    field.id() = f.id;
    field.name() = f.name;
    field.is_optional() = f.is_optional;
    f.metadata_type_interface->writeAndGenType(*field.type(), metadata);
    field.structured_annotations() = f.structured_annotations;
    eugraph_ResultRow.fields()->push_back(std::move(field));
  }
  return res.first->second;
}
const ::apache::thrift::metadata::ThriftStruct&
StructMetadata<::eugraph::thrift::QueryResult>::gen(ThriftMetadata& metadata) {
  auto res = metadata.structs()->emplace("eugraph.QueryResult", ::apache::thrift::metadata::ThriftStruct{});
  if (!res.second) {
    return res.first->second;
  }
  ::apache::thrift::metadata::ThriftStruct& eugraph_QueryResult = res.first->second;
  eugraph_QueryResult.name() = "eugraph.QueryResult";
  eugraph_QueryResult.is_union() = false;
  static const auto* const
  eugraph_QueryResult_fields = new std::array<EncodedThriftField, 4>{ {
    { 1, "columns", false, std::make_unique<List>(std::make_unique<Primitive>(ThriftPrimitiveType::THRIFT_STRING_TYPE)), std::vector<ThriftConstStruct>{ }},    { 2, "rows", false, std::make_unique<List>(std::make_unique<Struct<::eugraph::thrift::ResultRow>>("eugraph.ResultRow")), std::vector<ThriftConstStruct>{ }},    { 3, "rows_affected", false, std::make_unique<Primitive>(ThriftPrimitiveType::THRIFT_I64_TYPE), std::vector<ThriftConstStruct>{ }},    { 4, "error", false, std::make_unique<Primitive>(ThriftPrimitiveType::THRIFT_STRING_TYPE), std::vector<ThriftConstStruct>{ }},  }};
  for (const auto& f : *eugraph_QueryResult_fields) {
    ::apache::thrift::metadata::ThriftField field;
    field.id() = f.id;
    field.name() = f.name;
    field.is_optional() = f.is_optional;
    f.metadata_type_interface->writeAndGenType(*field.type(), metadata);
    field.structured_annotations() = f.structured_annotations;
    eugraph_QueryResult.fields()->push_back(std::move(field));
  }
  return res.first->second;
}

void ServiceMetadata<::apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>>::gen_createLabel([[maybe_unused]] ThriftMetadata& metadata, ThriftService& service) {
  ::apache::thrift::metadata::ThriftFunction func;
  func.name() = "createLabel";
  auto func_ret_type = std::make_unique<Struct<::eugraph::thrift::LabelInfo>>("eugraph.LabelInfo");
  func_ret_type->writeAndGenType(*func.return_type(), metadata);
  ::apache::thrift::metadata::ThriftField eugraph_EuGraphService_createLabel_name_1;
  eugraph_EuGraphService_createLabel_name_1.id() = 1;
  eugraph_EuGraphService_createLabel_name_1.name() = "name";
  eugraph_EuGraphService_createLabel_name_1.is_optional() = false;
  auto eugraph_EuGraphService_createLabel_name_1_type = std::make_unique<Primitive>(ThriftPrimitiveType::THRIFT_STRING_TYPE);
  eugraph_EuGraphService_createLabel_name_1_type->writeAndGenType(*eugraph_EuGraphService_createLabel_name_1.type(), metadata);
  func.arguments()->push_back(std::move(eugraph_EuGraphService_createLabel_name_1));
  ::apache::thrift::metadata::ThriftField eugraph_EuGraphService_createLabel_properties_2;
  eugraph_EuGraphService_createLabel_properties_2.id() = 2;
  eugraph_EuGraphService_createLabel_properties_2.name() = "properties";
  eugraph_EuGraphService_createLabel_properties_2.is_optional() = false;
  auto eugraph_EuGraphService_createLabel_properties_2_type = std::make_unique<List>(std::make_unique<Struct<::eugraph::thrift::PropertyDefThrift>>("eugraph.PropertyDefThrift"));
  eugraph_EuGraphService_createLabel_properties_2_type->writeAndGenType(*eugraph_EuGraphService_createLabel_properties_2.type(), metadata);
  func.arguments()->push_back(std::move(eugraph_EuGraphService_createLabel_properties_2));
  func.is_oneway() = false;
  service.functions()->push_back(std::move(func));
}
void ServiceMetadata<::apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>>::gen_listLabels([[maybe_unused]] ThriftMetadata& metadata, ThriftService& service) {
  ::apache::thrift::metadata::ThriftFunction func;
  func.name() = "listLabels";
  auto func_ret_type = std::make_unique<List>(std::make_unique<Struct<::eugraph::thrift::LabelInfo>>("eugraph.LabelInfo"));
  func_ret_type->writeAndGenType(*func.return_type(), metadata);
  func.is_oneway() = false;
  service.functions()->push_back(std::move(func));
}
void ServiceMetadata<::apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>>::gen_createEdgeLabel([[maybe_unused]] ThriftMetadata& metadata, ThriftService& service) {
  ::apache::thrift::metadata::ThriftFunction func;
  func.name() = "createEdgeLabel";
  auto func_ret_type = std::make_unique<Struct<::eugraph::thrift::EdgeLabelInfo>>("eugraph.EdgeLabelInfo");
  func_ret_type->writeAndGenType(*func.return_type(), metadata);
  ::apache::thrift::metadata::ThriftField eugraph_EuGraphService_createEdgeLabel_name_1;
  eugraph_EuGraphService_createEdgeLabel_name_1.id() = 1;
  eugraph_EuGraphService_createEdgeLabel_name_1.name() = "name";
  eugraph_EuGraphService_createEdgeLabel_name_1.is_optional() = false;
  auto eugraph_EuGraphService_createEdgeLabel_name_1_type = std::make_unique<Primitive>(ThriftPrimitiveType::THRIFT_STRING_TYPE);
  eugraph_EuGraphService_createEdgeLabel_name_1_type->writeAndGenType(*eugraph_EuGraphService_createEdgeLabel_name_1.type(), metadata);
  func.arguments()->push_back(std::move(eugraph_EuGraphService_createEdgeLabel_name_1));
  ::apache::thrift::metadata::ThriftField eugraph_EuGraphService_createEdgeLabel_properties_2;
  eugraph_EuGraphService_createEdgeLabel_properties_2.id() = 2;
  eugraph_EuGraphService_createEdgeLabel_properties_2.name() = "properties";
  eugraph_EuGraphService_createEdgeLabel_properties_2.is_optional() = false;
  auto eugraph_EuGraphService_createEdgeLabel_properties_2_type = std::make_unique<List>(std::make_unique<Struct<::eugraph::thrift::PropertyDefThrift>>("eugraph.PropertyDefThrift"));
  eugraph_EuGraphService_createEdgeLabel_properties_2_type->writeAndGenType(*eugraph_EuGraphService_createEdgeLabel_properties_2.type(), metadata);
  func.arguments()->push_back(std::move(eugraph_EuGraphService_createEdgeLabel_properties_2));
  func.is_oneway() = false;
  service.functions()->push_back(std::move(func));
}
void ServiceMetadata<::apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>>::gen_listEdgeLabels([[maybe_unused]] ThriftMetadata& metadata, ThriftService& service) {
  ::apache::thrift::metadata::ThriftFunction func;
  func.name() = "listEdgeLabels";
  auto func_ret_type = std::make_unique<List>(std::make_unique<Struct<::eugraph::thrift::EdgeLabelInfo>>("eugraph.EdgeLabelInfo"));
  func_ret_type->writeAndGenType(*func.return_type(), metadata);
  func.is_oneway() = false;
  service.functions()->push_back(std::move(func));
}
void ServiceMetadata<::apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>>::gen_executeCypher([[maybe_unused]] ThriftMetadata& metadata, ThriftService& service) {
  ::apache::thrift::metadata::ThriftFunction func;
  func.name() = "executeCypher";
  auto func_ret_type = std::make_unique<Struct<::eugraph::thrift::QueryResult>>("eugraph.QueryResult");
  func_ret_type->writeAndGenType(*func.return_type(), metadata);
  ::apache::thrift::metadata::ThriftField eugraph_EuGraphService_executeCypher_query_1;
  eugraph_EuGraphService_executeCypher_query_1.id() = 1;
  eugraph_EuGraphService_executeCypher_query_1.name() = "query";
  eugraph_EuGraphService_executeCypher_query_1.is_optional() = false;
  auto eugraph_EuGraphService_executeCypher_query_1_type = std::make_unique<Primitive>(ThriftPrimitiveType::THRIFT_STRING_TYPE);
  eugraph_EuGraphService_executeCypher_query_1_type->writeAndGenType(*eugraph_EuGraphService_executeCypher_query_1.type(), metadata);
  func.arguments()->push_back(std::move(eugraph_EuGraphService_executeCypher_query_1));
  func.is_oneway() = false;
  service.functions()->push_back(std::move(func));
}
void ServiceMetadata<::apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>>::gen_batchInsertVertices([[maybe_unused]] ThriftMetadata& metadata, ThriftService& service) {
  ::apache::thrift::metadata::ThriftFunction func;
  func.name() = "batchInsertVertices";
  auto func_ret_type = std::make_unique<Struct<::eugraph::thrift::BatchInsertVerticesResult>>("eugraph.BatchInsertVerticesResult");
  func_ret_type->writeAndGenType(*func.return_type(), metadata);
  ::apache::thrift::metadata::ThriftField eugraph_EuGraphService_batchInsertVertices_label_name_1;
  eugraph_EuGraphService_batchInsertVertices_label_name_1.id() = 1;
  eugraph_EuGraphService_batchInsertVertices_label_name_1.name() = "label_name";
  eugraph_EuGraphService_batchInsertVertices_label_name_1.is_optional() = false;
  auto eugraph_EuGraphService_batchInsertVertices_label_name_1_type = std::make_unique<Primitive>(ThriftPrimitiveType::THRIFT_STRING_TYPE);
  eugraph_EuGraphService_batchInsertVertices_label_name_1_type->writeAndGenType(*eugraph_EuGraphService_batchInsertVertices_label_name_1.type(), metadata);
  func.arguments()->push_back(std::move(eugraph_EuGraphService_batchInsertVertices_label_name_1));
  ::apache::thrift::metadata::ThriftField eugraph_EuGraphService_batchInsertVertices_records_2;
  eugraph_EuGraphService_batchInsertVertices_records_2.id() = 2;
  eugraph_EuGraphService_batchInsertVertices_records_2.name() = "records";
  eugraph_EuGraphService_batchInsertVertices_records_2.is_optional() = false;
  auto eugraph_EuGraphService_batchInsertVertices_records_2_type = std::make_unique<List>(std::make_unique<Struct<::eugraph::thrift::VertexRecord>>("eugraph.VertexRecord"));
  eugraph_EuGraphService_batchInsertVertices_records_2_type->writeAndGenType(*eugraph_EuGraphService_batchInsertVertices_records_2.type(), metadata);
  func.arguments()->push_back(std::move(eugraph_EuGraphService_batchInsertVertices_records_2));
  func.is_oneway() = false;
  service.functions()->push_back(std::move(func));
}
void ServiceMetadata<::apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>>::gen_batchInsertEdges([[maybe_unused]] ThriftMetadata& metadata, ThriftService& service) {
  ::apache::thrift::metadata::ThriftFunction func;
  func.name() = "batchInsertEdges";
  auto func_ret_type = std::make_unique<Primitive>(ThriftPrimitiveType::THRIFT_I32_TYPE);
  func_ret_type->writeAndGenType(*func.return_type(), metadata);
  ::apache::thrift::metadata::ThriftField eugraph_EuGraphService_batchInsertEdges_edge_label_name_1;
  eugraph_EuGraphService_batchInsertEdges_edge_label_name_1.id() = 1;
  eugraph_EuGraphService_batchInsertEdges_edge_label_name_1.name() = "edge_label_name";
  eugraph_EuGraphService_batchInsertEdges_edge_label_name_1.is_optional() = false;
  auto eugraph_EuGraphService_batchInsertEdges_edge_label_name_1_type = std::make_unique<Primitive>(ThriftPrimitiveType::THRIFT_STRING_TYPE);
  eugraph_EuGraphService_batchInsertEdges_edge_label_name_1_type->writeAndGenType(*eugraph_EuGraphService_batchInsertEdges_edge_label_name_1.type(), metadata);
  func.arguments()->push_back(std::move(eugraph_EuGraphService_batchInsertEdges_edge_label_name_1));
  ::apache::thrift::metadata::ThriftField eugraph_EuGraphService_batchInsertEdges_records_2;
  eugraph_EuGraphService_batchInsertEdges_records_2.id() = 2;
  eugraph_EuGraphService_batchInsertEdges_records_2.name() = "records";
  eugraph_EuGraphService_batchInsertEdges_records_2.is_optional() = false;
  auto eugraph_EuGraphService_batchInsertEdges_records_2_type = std::make_unique<List>(std::make_unique<Struct<::eugraph::thrift::EdgeRecord>>("eugraph.EdgeRecord"));
  eugraph_EuGraphService_batchInsertEdges_records_2_type->writeAndGenType(*eugraph_EuGraphService_batchInsertEdges_records_2.type(), metadata);
  func.arguments()->push_back(std::move(eugraph_EuGraphService_batchInsertEdges_records_2));
  func.is_oneway() = false;
  service.functions()->push_back(std::move(func));
}

void ServiceMetadata<::apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>>::gen(::apache::thrift::metadata::ThriftServiceMetadataResponse& response) {
  const ::apache::thrift::metadata::ThriftServiceContextRef* self = genRecurse(*response.metadata(), *response.services());
  DCHECK(self != nullptr);
  // TODO(praihan): Remove ThriftServiceContext from response. But in the meantime, we need to fill the field with the result of looking up in ThriftMetadata.
  ::apache::thrift::metadata::ThriftServiceContext context;
  context.module() = *self->module();
  context.service_info() = response.metadata()->services()->at(*self->service_name());
  response.context() = std::move(context);
}

const ThriftServiceContextRef* ServiceMetadata<::apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>>::genRecurse([[maybe_unused]] ThriftMetadata& metadata, std::vector<ThriftServiceContextRef>& services) {
  ::apache::thrift::metadata::ThriftService eugraph_EuGraphService;
  eugraph_EuGraphService.name() = "eugraph.EuGraphService";
  static const ThriftFunctionGenerator functions[] = {
    ServiceMetadata<::apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>>::gen_createLabel,
    ServiceMetadata<::apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>>::gen_listLabels,
    ServiceMetadata<::apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>>::gen_createEdgeLabel,
    ServiceMetadata<::apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>>::gen_listEdgeLabels,
    ServiceMetadata<::apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>>::gen_executeCypher,
    ServiceMetadata<::apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>>::gen_batchInsertVertices,
    ServiceMetadata<::apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>>::gen_batchInsertEdges,
  };
  for (auto& function_gen : functions) {
    function_gen(metadata, eugraph_EuGraphService);
  }
  // We need to keep the index around because a reference or iterator could be invalidated.
  auto selfIndex = services.size();
  services.emplace_back();
  ThriftServiceContextRef& context = services[selfIndex];
  metadata.services()->emplace("eugraph.EuGraphService", std::move(eugraph_EuGraphService));
  context.service_name() = "eugraph.EuGraphService";
  ::apache::thrift::metadata::ThriftModuleContext module;
  module.name() = "eugraph";
  context.module() = std::move(module);
  return &context;
}
} // namespace md
} // namespace detail
} // namespace thrift
} // namespace apache
