/**
 * Autogenerated by Thrift for proto/eugraph.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated @nocommit
 */
#include "gen-cpp2/eugraph_types.h"
#include "gen-cpp2/eugraph_types.tcc"

#include <thrift/lib/cpp2/gen/module_types_cpp.h>

#include "gen-cpp2/eugraph_data.h"
[[maybe_unused]] static constexpr std::string_view kModuleName = "eugraph";


namespace apache { namespace thrift {

const std::string_view TEnumTraits<::eugraph::thrift::PropertyType>::__fbthrift_module_name_internal_do_not_use = kModuleName;
folly::Range<::eugraph::thrift::PropertyType const*> const TEnumTraits<::eugraph::thrift::PropertyType>::values = folly::range(TEnumDataStorage<::eugraph::thrift::PropertyType>::values);
folly::Range<std::string_view const*> const TEnumTraits<::eugraph::thrift::PropertyType>::names = folly::range(TEnumDataStorage<::eugraph::thrift::PropertyType>::names);

bool TEnumTraits<::eugraph::thrift::PropertyType>::findName(type value, std::string_view* out) noexcept {
  return ::apache::thrift::detail::st::enum_find_name(value, out);
}

bool TEnumTraits<::eugraph::thrift::PropertyType>::findValue(std::string_view name, type* out) noexcept {
  return ::apache::thrift::detail::st::enum_find_value(name, out);
}

}} // apache::thrift


namespace apache {
namespace thrift {
namespace detail {

void TccStructTraits<::eugraph::thrift::PropertyDefThrift>::translateFieldName(
    std::string_view _fname,
    int16_t& fid,
    apache::thrift::protocol::TType& _ftype) noexcept {
  using data = apache::thrift::TStructDataStorage<::eugraph::thrift::PropertyDefThrift>;
  static const st::translate_field_name_table table{
      data::fields_size,
      data::fields_names.data(),
      data::fields_ids.data(),
      data::fields_types.data()};
  st::translate_field_name(_fname, fid, _ftype, table);
}

} // namespace detail
} // namespace thrift
} // namespace apache

namespace eugraph::thrift {

std::string_view PropertyDefThrift::__fbthrift_get_field_name(::apache::thrift::FieldOrdinal ord) {
  if (ord == ::apache::thrift::FieldOrdinal{0}) { return {}; }
  return apache::thrift::TStructDataStorage<PropertyDefThrift>::fields_names[folly::to_underlying(ord) - 1];
}
std::string_view PropertyDefThrift::__fbthrift_get_class_name() {
  return apache::thrift::TStructDataStorage<PropertyDefThrift>::name;
}

PropertyDefThrift::PropertyDefThrift(const PropertyDefThrift&) = default;
PropertyDefThrift& PropertyDefThrift::operator=(const PropertyDefThrift&) = default;
PropertyDefThrift::PropertyDefThrift() :
    __fbthrift_field_type(),
    __fbthrift_field_is_required(false) {
}


PropertyDefThrift::~PropertyDefThrift() {}

PropertyDefThrift::PropertyDefThrift([[maybe_unused]] PropertyDefThrift&& other) noexcept :
    __fbthrift_field_name(std::move(other.__fbthrift_field_name)),
    __fbthrift_field_type(std::move(other.__fbthrift_field_type)),
    __fbthrift_field_is_required(std::move(other.__fbthrift_field_is_required)),
    __isset(other.__isset) {
}

PropertyDefThrift& PropertyDefThrift::operator=([[maybe_unused]] PropertyDefThrift&& other) noexcept {
    this->__fbthrift_field_name = std::move(other.__fbthrift_field_name);
    this->__fbthrift_field_type = std::move(other.__fbthrift_field_type);
    this->__fbthrift_field_is_required = std::move(other.__fbthrift_field_is_required);
    __isset = other.__isset;
    return *this;
}


PropertyDefThrift::PropertyDefThrift(apache::thrift::FragileConstructor, ::std::string name__arg, ::eugraph::thrift::PropertyType type__arg, bool is_required__arg) :
    __fbthrift_field_name(std::move(name__arg)),
    __fbthrift_field_type(std::move(type__arg)),
    __fbthrift_field_is_required(std::move(is_required__arg)) { 
  __isset.set(folly::index_constant<0>(), true);
  __isset.set(folly::index_constant<1>(), true);
  __isset.set(folly::index_constant<2>(), true);
}


void PropertyDefThrift::__fbthrift_clear() {
  // clear all fields
  this->__fbthrift_field_name = apache::thrift::StringTraits<::std::string>::fromStringLiteral("");
  this->__fbthrift_field_type = ::eugraph::thrift::PropertyType();
  this->__fbthrift_field_is_required = bool();
  __isset = {};
}

void PropertyDefThrift::__fbthrift_clear_terse_fields() {
}

bool PropertyDefThrift::__fbthrift_is_empty() const {
  return false;
}

bool PropertyDefThrift::operator==([[maybe_unused]] const PropertyDefThrift& rhs) const {
  return ::apache::thrift::op::detail::StructEquality{}(*this, rhs);
}

bool PropertyDefThrift::operator<([[maybe_unused]] const PropertyDefThrift& rhs) const {
  return ::apache::thrift::op::detail::StructLessThan{}(*this, rhs);
}


::eugraph::thrift::PropertyType PropertyDefThrift::get_type() const {
  return __fbthrift_field_type;
}

::eugraph::thrift::PropertyType& PropertyDefThrift::set_type(::eugraph::thrift::PropertyType type_) {
  type_ref() = type_;
  return __fbthrift_field_type;
}

bool PropertyDefThrift::get_is_required() const {
  return __fbthrift_field_is_required;
}

bool& PropertyDefThrift::set_is_required(bool is_required_) {
  is_required_ref() = is_required_;
  return __fbthrift_field_is_required;
}

void swap([[maybe_unused]] PropertyDefThrift& a, [[maybe_unused]] PropertyDefThrift& b) {
  using ::std::swap;
  swap(a.__fbthrift_field_name, b.__fbthrift_field_name);
  swap(a.__fbthrift_field_type, b.__fbthrift_field_type);
  swap(a.__fbthrift_field_is_required, b.__fbthrift_field_is_required);
  swap(a.__isset, b.__isset);
}

#ifndef __FBTHRIFT_INSTANTIATE_COMPACT_BINARY_PROTOCOL_IN_SEPARATE_TU
template void PropertyDefThrift::readNoXfer<>(apache::thrift::BinaryProtocolReader*);
template uint32_t PropertyDefThrift::write<>(apache::thrift::BinaryProtocolWriter*) const;
template uint32_t PropertyDefThrift::serializedSize<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t PropertyDefThrift::serializedSizeZC<>(apache::thrift::BinaryProtocolWriter const*) const;
template void PropertyDefThrift::readNoXfer<>(apache::thrift::CompactProtocolReader*);
template uint32_t PropertyDefThrift::write<>(apache::thrift::CompactProtocolWriter*) const;
template uint32_t PropertyDefThrift::serializedSize<>(apache::thrift::CompactProtocolWriter const*) const;
template uint32_t PropertyDefThrift::serializedSizeZC<>(apache::thrift::CompactProtocolWriter const*) const;
#endif


} // namespace eugraph::thrift

namespace apache {
namespace thrift {
namespace detail {

void TccStructTraits<::eugraph::thrift::PropertyValueThrift>::translateFieldName(
    std::string_view _fname,
    int16_t& fid,
    apache::thrift::protocol::TType& _ftype) noexcept {
  using data = apache::thrift::TStructDataStorage<::eugraph::thrift::PropertyValueThrift>;
  static const st::translate_field_name_table table{
      data::fields_size,
      data::fields_names.data(),
      data::fields_ids.data(),
      data::fields_types.data()};
  st::translate_field_name(_fname, fid, _ftype, table);
}

} // namespace detail
} // namespace thrift
} // namespace apache

namespace apache { namespace thrift {

folly::Range<::eugraph::thrift::PropertyValueThrift::Type const*> const TEnumTraits<::eugraph::thrift::PropertyValueThrift::Type>::values = folly::range(TEnumDataStorage<::eugraph::thrift::PropertyValueThrift::Type>::values);
folly::Range<std::string_view const*> const TEnumTraits<::eugraph::thrift::PropertyValueThrift::Type>::names = folly::range(TEnumDataStorage<::eugraph::thrift::PropertyValueThrift::Type>::names);

bool TEnumTraits<::eugraph::thrift::PropertyValueThrift::Type>::findName(type value, std::string_view* out) noexcept {
  return ::apache::thrift::detail::st::enum_find_name(value, out);
}

bool TEnumTraits<::eugraph::thrift::PropertyValueThrift::Type>::findValue(std::string_view name, type* out) noexcept {
  return ::apache::thrift::detail::st::enum_find_value(name, out);
}
}} // apache::thrift
namespace eugraph::thrift {

std::string_view PropertyValueThrift::__fbthrift_get_field_name(::apache::thrift::FieldOrdinal ord) {
  if (ord == ::apache::thrift::FieldOrdinal{0}) { return {}; }
  return apache::thrift::TStructDataStorage<PropertyValueThrift>::fields_names[folly::to_underlying(ord) - 1];
}
std::string_view PropertyValueThrift::__fbthrift_get_class_name() {
  return apache::thrift::TStructDataStorage<PropertyValueThrift>::name;
}

void PropertyValueThrift::__fbthrift_destruct() {
  switch(getType()) {
    case Type::__EMPTY__:
      break;
    case Type::bool_val:
      ::std::destroy_at(::std::addressof(value_.bool_val));
      break;
    case Type::int_val:
      ::std::destroy_at(::std::addressof(value_.int_val));
      break;
    case Type::double_val:
      ::std::destroy_at(::std::addressof(value_.double_val));
      break;
    case Type::string_val:
      ::std::destroy_at(::std::addressof(value_.string_val));
      break;
    case Type::int_array:
      ::std::destroy_at(::std::addressof(value_.int_array));
      break;
    case Type::double_array:
      ::std::destroy_at(::std::addressof(value_.double_array));
      break;
    case Type::string_array:
      ::std::destroy_at(::std::addressof(value_.string_array));
      break;
    default:
      assert(false);
      break;
  }
}

void PropertyValueThrift::__fbthrift_clear() {
  __fbthrift_destruct();
  type_ = folly::to_underlying(Type::__EMPTY__);
}

  PropertyValueThrift::~PropertyValueThrift() {
    __fbthrift_destruct();
  }

bool PropertyValueThrift::__fbthrift_is_empty() const {
  return getType() == Type::__EMPTY__;
}
  PropertyValueThrift::PropertyValueThrift(const PropertyValueThrift& rhs)
      : type_(folly::to_underlying(Type::__EMPTY__)) {
    switch (rhs.getType()) {
      case Type::__EMPTY__:
        return;
      case Type::bool_val:
        set_bool_val(rhs.value_.bool_val);
        break;
      case Type::int_val:
        set_int_val(rhs.value_.int_val);
        break;
      case Type::double_val:
        set_double_val(rhs.value_.double_val);
        break;
      case Type::string_val:
        set_string_val(rhs.value_.string_val);
        break;
      case Type::int_array:
        set_int_array(rhs.value_.int_array);
        break;
      case Type::double_array:
        set_double_array(rhs.value_.double_array);
        break;
      case Type::string_array:
        set_string_array(rhs.value_.string_array);
        break;
      default:
        assert(false);
    }
  }

    PropertyValueThrift&PropertyValueThrift::operator=(const PropertyValueThrift& rhs) {
    if (this == &rhs) { return *this; }
    switch (rhs.getType()) {
      case Type::__EMPTY__:
        __fbthrift_clear();
        return *this;
      case Type::bool_val:
        set_bool_val(rhs.value_.bool_val);
        break;
      case Type::int_val:
        set_int_val(rhs.value_.int_val);
        break;
      case Type::double_val:
        set_double_val(rhs.value_.double_val);
        break;
      case Type::string_val:
        set_string_val(rhs.value_.string_val);
        break;
      case Type::int_array:
        set_int_array(rhs.value_.int_array);
        break;
      case Type::double_array:
        set_double_array(rhs.value_.double_array);
        break;
      case Type::string_array:
        set_string_array(rhs.value_.string_array);
        break;
      default:
        __fbthrift_clear();
        assert(false);
    }
    return *this;
  }


bool PropertyValueThrift::operator==(const PropertyValueThrift& rhs) const {
  return ::apache::thrift::op::detail::UnionEquality{}(*this, rhs);
}

bool PropertyValueThrift::operator<([[maybe_unused]] const PropertyValueThrift& rhs) const {
  return ::apache::thrift::op::detail::UnionLessThan{}(*this, rhs);
}

void swap(PropertyValueThrift& a, PropertyValueThrift& b) {
  PropertyValueThrift temp(std::move(a));
  a = std::move(b);
  b = std::move(temp);
}

#ifndef __FBTHRIFT_INSTANTIATE_COMPACT_BINARY_PROTOCOL_IN_SEPARATE_TU
template void PropertyValueThrift::readNoXfer<>(apache::thrift::BinaryProtocolReader*);
template uint32_t PropertyValueThrift::write<>(apache::thrift::BinaryProtocolWriter*) const;
template uint32_t PropertyValueThrift::serializedSize<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t PropertyValueThrift::serializedSizeZC<>(apache::thrift::BinaryProtocolWriter const*) const;
template void PropertyValueThrift::readNoXfer<>(apache::thrift::CompactProtocolReader*);
template uint32_t PropertyValueThrift::write<>(apache::thrift::CompactProtocolWriter*) const;
template uint32_t PropertyValueThrift::serializedSize<>(apache::thrift::CompactProtocolWriter const*) const;
template uint32_t PropertyValueThrift::serializedSizeZC<>(apache::thrift::CompactProtocolWriter const*) const;
#endif


} // namespace eugraph::thrift

namespace apache {
namespace thrift {
namespace detail {

void TccStructTraits<::eugraph::thrift::LabelInfo>::translateFieldName(
    std::string_view _fname,
    int16_t& fid,
    apache::thrift::protocol::TType& _ftype) noexcept {
  using data = apache::thrift::TStructDataStorage<::eugraph::thrift::LabelInfo>;
  static const st::translate_field_name_table table{
      data::fields_size,
      data::fields_names.data(),
      data::fields_ids.data(),
      data::fields_types.data()};
  st::translate_field_name(_fname, fid, _ftype, table);
}

} // namespace detail
} // namespace thrift
} // namespace apache

namespace eugraph::thrift {

std::string_view LabelInfo::__fbthrift_get_field_name(::apache::thrift::FieldOrdinal ord) {
  if (ord == ::apache::thrift::FieldOrdinal{0}) { return {}; }
  return apache::thrift::TStructDataStorage<LabelInfo>::fields_names[folly::to_underlying(ord) - 1];
}
std::string_view LabelInfo::__fbthrift_get_class_name() {
  return apache::thrift::TStructDataStorage<LabelInfo>::name;
}

LabelInfo::LabelInfo(const LabelInfo&) = default;
LabelInfo& LabelInfo::operator=(const LabelInfo&) = default;
LabelInfo::LabelInfo() :
    __fbthrift_field_id() {
}


LabelInfo::~LabelInfo() {}

LabelInfo::LabelInfo([[maybe_unused]] LabelInfo&& other) noexcept :
    __fbthrift_field_id(std::move(other.__fbthrift_field_id)),
    __fbthrift_field_name(std::move(other.__fbthrift_field_name)),
    __fbthrift_field_properties(std::move(other.__fbthrift_field_properties)),
    __isset(other.__isset) {
}

LabelInfo& LabelInfo::operator=([[maybe_unused]] LabelInfo&& other) noexcept {
    this->__fbthrift_field_id = std::move(other.__fbthrift_field_id);
    this->__fbthrift_field_name = std::move(other.__fbthrift_field_name);
    this->__fbthrift_field_properties = std::move(other.__fbthrift_field_properties);
    __isset = other.__isset;
    return *this;
}


LabelInfo::LabelInfo(apache::thrift::FragileConstructor, ::std::int16_t id__arg, ::std::string name__arg, ::std::vector<::eugraph::thrift::PropertyDefThrift> properties__arg) :
    __fbthrift_field_id(std::move(id__arg)),
    __fbthrift_field_name(std::move(name__arg)),
    __fbthrift_field_properties(std::move(properties__arg)) { 
  __isset.set(folly::index_constant<0>(), true);
  __isset.set(folly::index_constant<1>(), true);
  __isset.set(folly::index_constant<2>(), true);
}


void LabelInfo::__fbthrift_clear() {
  // clear all fields
  this->__fbthrift_field_id = ::std::int16_t();
  this->__fbthrift_field_name = apache::thrift::StringTraits<::std::string>::fromStringLiteral("");
  this->__fbthrift_field_properties.clear();
  __isset = {};
}

void LabelInfo::__fbthrift_clear_terse_fields() {
}

bool LabelInfo::__fbthrift_is_empty() const {
  return false;
}

bool LabelInfo::operator==([[maybe_unused]] const LabelInfo& rhs) const {
  return ::apache::thrift::op::detail::StructEquality{}(*this, rhs);
}

bool LabelInfo::operator<([[maybe_unused]] const LabelInfo& rhs) const {
  return ::apache::thrift::op::detail::StructLessThan{}(*this, rhs);
}


::std::int16_t LabelInfo::get_id() const {
  return __fbthrift_field_id;
}

::std::int16_t& LabelInfo::set_id(::std::int16_t id_) {
  id_ref() = id_;
  return __fbthrift_field_id;
}

const ::std::vector<::eugraph::thrift::PropertyDefThrift>& LabelInfo::get_properties() const& {
  return __fbthrift_field_properties;
}

::std::vector<::eugraph::thrift::PropertyDefThrift> LabelInfo::get_properties() && {
  return static_cast<::std::vector<::eugraph::thrift::PropertyDefThrift>&&>(__fbthrift_field_properties);
}

void swap([[maybe_unused]] LabelInfo& a, [[maybe_unused]] LabelInfo& b) {
  using ::std::swap;
  swap(a.__fbthrift_field_id, b.__fbthrift_field_id);
  swap(a.__fbthrift_field_name, b.__fbthrift_field_name);
  swap(a.__fbthrift_field_properties, b.__fbthrift_field_properties);
  swap(a.__isset, b.__isset);
}

#ifndef __FBTHRIFT_INSTANTIATE_COMPACT_BINARY_PROTOCOL_IN_SEPARATE_TU
template void LabelInfo::readNoXfer<>(apache::thrift::BinaryProtocolReader*);
template uint32_t LabelInfo::write<>(apache::thrift::BinaryProtocolWriter*) const;
template uint32_t LabelInfo::serializedSize<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t LabelInfo::serializedSizeZC<>(apache::thrift::BinaryProtocolWriter const*) const;
template void LabelInfo::readNoXfer<>(apache::thrift::CompactProtocolReader*);
template uint32_t LabelInfo::write<>(apache::thrift::CompactProtocolWriter*) const;
template uint32_t LabelInfo::serializedSize<>(apache::thrift::CompactProtocolWriter const*) const;
template uint32_t LabelInfo::serializedSizeZC<>(apache::thrift::CompactProtocolWriter const*) const;
#endif

static_assert(
    ::apache::thrift::detail::st::gen_check_json<
        LabelInfo,
        ::apache::thrift::type_class::list<::apache::thrift::type_class::structure>,
        ::std::vector<::eugraph::thrift::PropertyDefThrift>>,
    "inconsistent use of json option");

} // namespace eugraph::thrift

namespace apache {
namespace thrift {
namespace detail {

void TccStructTraits<::eugraph::thrift::EdgeLabelInfo>::translateFieldName(
    std::string_view _fname,
    int16_t& fid,
    apache::thrift::protocol::TType& _ftype) noexcept {
  using data = apache::thrift::TStructDataStorage<::eugraph::thrift::EdgeLabelInfo>;
  static const st::translate_field_name_table table{
      data::fields_size,
      data::fields_names.data(),
      data::fields_ids.data(),
      data::fields_types.data()};
  st::translate_field_name(_fname, fid, _ftype, table);
}

} // namespace detail
} // namespace thrift
} // namespace apache

namespace eugraph::thrift {

std::string_view EdgeLabelInfo::__fbthrift_get_field_name(::apache::thrift::FieldOrdinal ord) {
  if (ord == ::apache::thrift::FieldOrdinal{0}) { return {}; }
  return apache::thrift::TStructDataStorage<EdgeLabelInfo>::fields_names[folly::to_underlying(ord) - 1];
}
std::string_view EdgeLabelInfo::__fbthrift_get_class_name() {
  return apache::thrift::TStructDataStorage<EdgeLabelInfo>::name;
}

EdgeLabelInfo::EdgeLabelInfo(const EdgeLabelInfo&) = default;
EdgeLabelInfo& EdgeLabelInfo::operator=(const EdgeLabelInfo&) = default;
EdgeLabelInfo::EdgeLabelInfo() :
    __fbthrift_field_id(),
    __fbthrift_field_directed(true) {
}


EdgeLabelInfo::~EdgeLabelInfo() {}

EdgeLabelInfo::EdgeLabelInfo([[maybe_unused]] EdgeLabelInfo&& other) noexcept :
    __fbthrift_field_id(std::move(other.__fbthrift_field_id)),
    __fbthrift_field_name(std::move(other.__fbthrift_field_name)),
    __fbthrift_field_properties(std::move(other.__fbthrift_field_properties)),
    __fbthrift_field_directed(std::move(other.__fbthrift_field_directed)),
    __isset(other.__isset) {
}

EdgeLabelInfo& EdgeLabelInfo::operator=([[maybe_unused]] EdgeLabelInfo&& other) noexcept {
    this->__fbthrift_field_id = std::move(other.__fbthrift_field_id);
    this->__fbthrift_field_name = std::move(other.__fbthrift_field_name);
    this->__fbthrift_field_properties = std::move(other.__fbthrift_field_properties);
    this->__fbthrift_field_directed = std::move(other.__fbthrift_field_directed);
    __isset = other.__isset;
    return *this;
}


EdgeLabelInfo::EdgeLabelInfo(apache::thrift::FragileConstructor, ::std::int16_t id__arg, ::std::string name__arg, ::std::vector<::eugraph::thrift::PropertyDefThrift> properties__arg, bool directed__arg) :
    __fbthrift_field_id(std::move(id__arg)),
    __fbthrift_field_name(std::move(name__arg)),
    __fbthrift_field_properties(std::move(properties__arg)),
    __fbthrift_field_directed(std::move(directed__arg)) { 
  __isset.set(folly::index_constant<0>(), true);
  __isset.set(folly::index_constant<1>(), true);
  __isset.set(folly::index_constant<2>(), true);
  __isset.set(folly::index_constant<3>(), true);
}


void EdgeLabelInfo::__fbthrift_clear() {
  // clear all fields
  this->__fbthrift_field_id = ::std::int16_t();
  this->__fbthrift_field_name = apache::thrift::StringTraits<::std::string>::fromStringLiteral("");
  this->__fbthrift_field_properties.clear();
  this->__fbthrift_field_directed = bool();
  __isset = {};
}

void EdgeLabelInfo::__fbthrift_clear_terse_fields() {
}

bool EdgeLabelInfo::__fbthrift_is_empty() const {
  return false;
}

bool EdgeLabelInfo::operator==([[maybe_unused]] const EdgeLabelInfo& rhs) const {
  return ::apache::thrift::op::detail::StructEquality{}(*this, rhs);
}

bool EdgeLabelInfo::operator<([[maybe_unused]] const EdgeLabelInfo& rhs) const {
  return ::apache::thrift::op::detail::StructLessThan{}(*this, rhs);
}


::std::int16_t EdgeLabelInfo::get_id() const {
  return __fbthrift_field_id;
}

::std::int16_t& EdgeLabelInfo::set_id(::std::int16_t id_) {
  id_ref() = id_;
  return __fbthrift_field_id;
}

const ::std::vector<::eugraph::thrift::PropertyDefThrift>& EdgeLabelInfo::get_properties() const& {
  return __fbthrift_field_properties;
}

::std::vector<::eugraph::thrift::PropertyDefThrift> EdgeLabelInfo::get_properties() && {
  return static_cast<::std::vector<::eugraph::thrift::PropertyDefThrift>&&>(__fbthrift_field_properties);
}

bool EdgeLabelInfo::get_directed() const {
  return __fbthrift_field_directed;
}

bool& EdgeLabelInfo::set_directed(bool directed_) {
  directed_ref() = directed_;
  return __fbthrift_field_directed;
}

void swap([[maybe_unused]] EdgeLabelInfo& a, [[maybe_unused]] EdgeLabelInfo& b) {
  using ::std::swap;
  swap(a.__fbthrift_field_id, b.__fbthrift_field_id);
  swap(a.__fbthrift_field_name, b.__fbthrift_field_name);
  swap(a.__fbthrift_field_properties, b.__fbthrift_field_properties);
  swap(a.__fbthrift_field_directed, b.__fbthrift_field_directed);
  swap(a.__isset, b.__isset);
}

#ifndef __FBTHRIFT_INSTANTIATE_COMPACT_BINARY_PROTOCOL_IN_SEPARATE_TU
template void EdgeLabelInfo::readNoXfer<>(apache::thrift::BinaryProtocolReader*);
template uint32_t EdgeLabelInfo::write<>(apache::thrift::BinaryProtocolWriter*) const;
template uint32_t EdgeLabelInfo::serializedSize<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t EdgeLabelInfo::serializedSizeZC<>(apache::thrift::BinaryProtocolWriter const*) const;
template void EdgeLabelInfo::readNoXfer<>(apache::thrift::CompactProtocolReader*);
template uint32_t EdgeLabelInfo::write<>(apache::thrift::CompactProtocolWriter*) const;
template uint32_t EdgeLabelInfo::serializedSize<>(apache::thrift::CompactProtocolWriter const*) const;
template uint32_t EdgeLabelInfo::serializedSizeZC<>(apache::thrift::CompactProtocolWriter const*) const;
#endif

static_assert(
    ::apache::thrift::detail::st::gen_check_json<
        EdgeLabelInfo,
        ::apache::thrift::type_class::list<::apache::thrift::type_class::structure>,
        ::std::vector<::eugraph::thrift::PropertyDefThrift>>,
    "inconsistent use of json option");

} // namespace eugraph::thrift

namespace apache {
namespace thrift {
namespace detail {

void TccStructTraits<::eugraph::thrift::VertexRecord>::translateFieldName(
    std::string_view _fname,
    int16_t& fid,
    apache::thrift::protocol::TType& _ftype) noexcept {
  using data = apache::thrift::TStructDataStorage<::eugraph::thrift::VertexRecord>;
  static const st::translate_field_name_table table{
      data::fields_size,
      data::fields_names.data(),
      data::fields_ids.data(),
      data::fields_types.data()};
  st::translate_field_name(_fname, fid, _ftype, table);
}

} // namespace detail
} // namespace thrift
} // namespace apache

namespace eugraph::thrift {

std::string_view VertexRecord::__fbthrift_get_field_name(::apache::thrift::FieldOrdinal ord) {
  if (ord == ::apache::thrift::FieldOrdinal{0}) { return {}; }
  return apache::thrift::TStructDataStorage<VertexRecord>::fields_names[folly::to_underlying(ord) - 1];
}
std::string_view VertexRecord::__fbthrift_get_class_name() {
  return apache::thrift::TStructDataStorage<VertexRecord>::name;
}

VertexRecord::VertexRecord(const VertexRecord&) = default;
VertexRecord& VertexRecord::operator=(const VertexRecord&) = default;
VertexRecord::VertexRecord() {
}


VertexRecord::~VertexRecord() {}

VertexRecord::VertexRecord([[maybe_unused]] VertexRecord&& other) noexcept :
    __fbthrift_field_pk_value(std::move(other.__fbthrift_field_pk_value)),
    __fbthrift_field_properties(std::move(other.__fbthrift_field_properties)),
    __isset(other.__isset) {
}

VertexRecord& VertexRecord::operator=([[maybe_unused]] VertexRecord&& other) noexcept {
    this->__fbthrift_field_pk_value = std::move(other.__fbthrift_field_pk_value);
    this->__fbthrift_field_properties = std::move(other.__fbthrift_field_properties);
    __isset = other.__isset;
    return *this;
}


VertexRecord::VertexRecord(apache::thrift::FragileConstructor, ::eugraph::thrift::PropertyValueThrift pk_value__arg, ::std::vector<::eugraph::thrift::PropertyValueThrift> properties__arg) :
    __fbthrift_field_pk_value(std::move(pk_value__arg)),
    __fbthrift_field_properties(std::move(properties__arg)) { 
  __isset.set(folly::index_constant<0>(), true);
  __isset.set(folly::index_constant<1>(), true);
}


void VertexRecord::__fbthrift_clear() {
  // clear all fields
  ::apache::thrift::clear(this->__fbthrift_field_pk_value);
  this->__fbthrift_field_properties.clear();
  __isset = {};
}

void VertexRecord::__fbthrift_clear_terse_fields() {
}

bool VertexRecord::__fbthrift_is_empty() const {
  return false;
}

bool VertexRecord::operator==([[maybe_unused]] const VertexRecord& rhs) const {
  return ::apache::thrift::op::detail::StructEquality{}(*this, rhs);
}

bool VertexRecord::operator<([[maybe_unused]] const VertexRecord& rhs) const {
  return ::apache::thrift::op::detail::StructLessThan{}(*this, rhs);
}


const ::eugraph::thrift::PropertyValueThrift& VertexRecord::get_pk_value() const& {
  return __fbthrift_field_pk_value;
}

::eugraph::thrift::PropertyValueThrift VertexRecord::get_pk_value() && {
  return static_cast<::eugraph::thrift::PropertyValueThrift&&>(__fbthrift_field_pk_value);
}

const ::std::vector<::eugraph::thrift::PropertyValueThrift>& VertexRecord::get_properties() const& {
  return __fbthrift_field_properties;
}

::std::vector<::eugraph::thrift::PropertyValueThrift> VertexRecord::get_properties() && {
  return static_cast<::std::vector<::eugraph::thrift::PropertyValueThrift>&&>(__fbthrift_field_properties);
}

void swap([[maybe_unused]] VertexRecord& a, [[maybe_unused]] VertexRecord& b) {
  using ::std::swap;
  swap(a.__fbthrift_field_pk_value, b.__fbthrift_field_pk_value);
  swap(a.__fbthrift_field_properties, b.__fbthrift_field_properties);
  swap(a.__isset, b.__isset);
}

#ifndef __FBTHRIFT_INSTANTIATE_COMPACT_BINARY_PROTOCOL_IN_SEPARATE_TU
template void VertexRecord::readNoXfer<>(apache::thrift::BinaryProtocolReader*);
template uint32_t VertexRecord::write<>(apache::thrift::BinaryProtocolWriter*) const;
template uint32_t VertexRecord::serializedSize<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t VertexRecord::serializedSizeZC<>(apache::thrift::BinaryProtocolWriter const*) const;
template void VertexRecord::readNoXfer<>(apache::thrift::CompactProtocolReader*);
template uint32_t VertexRecord::write<>(apache::thrift::CompactProtocolWriter*) const;
template uint32_t VertexRecord::serializedSize<>(apache::thrift::CompactProtocolWriter const*) const;
template uint32_t VertexRecord::serializedSizeZC<>(apache::thrift::CompactProtocolWriter const*) const;
#endif

static_assert(
    ::apache::thrift::detail::st::gen_check_json<
        VertexRecord,
        ::apache::thrift::type_class::variant,
        ::eugraph::thrift::PropertyValueThrift>,
    "inconsistent use of json option");
static_assert(
    ::apache::thrift::detail::st::gen_check_json<
        VertexRecord,
        ::apache::thrift::type_class::list<::apache::thrift::type_class::variant>,
        ::std::vector<::eugraph::thrift::PropertyValueThrift>>,
    "inconsistent use of json option");

} // namespace eugraph::thrift

namespace apache {
namespace thrift {
namespace detail {

void TccStructTraits<::eugraph::thrift::EdgeRecord>::translateFieldName(
    std::string_view _fname,
    int16_t& fid,
    apache::thrift::protocol::TType& _ftype) noexcept {
  using data = apache::thrift::TStructDataStorage<::eugraph::thrift::EdgeRecord>;
  static const st::translate_field_name_table table{
      data::fields_size,
      data::fields_names.data(),
      data::fields_ids.data(),
      data::fields_types.data()};
  st::translate_field_name(_fname, fid, _ftype, table);
}

} // namespace detail
} // namespace thrift
} // namespace apache

namespace eugraph::thrift {

std::string_view EdgeRecord::__fbthrift_get_field_name(::apache::thrift::FieldOrdinal ord) {
  if (ord == ::apache::thrift::FieldOrdinal{0}) { return {}; }
  return apache::thrift::TStructDataStorage<EdgeRecord>::fields_names[folly::to_underlying(ord) - 1];
}
std::string_view EdgeRecord::__fbthrift_get_class_name() {
  return apache::thrift::TStructDataStorage<EdgeRecord>::name;
}

EdgeRecord::EdgeRecord(const EdgeRecord&) = default;
EdgeRecord& EdgeRecord::operator=(const EdgeRecord&) = default;
EdgeRecord::EdgeRecord() :
    __fbthrift_field_src_vertex_id(),
    __fbthrift_field_dst_vertex_id() {
}


EdgeRecord::~EdgeRecord() {}

EdgeRecord::EdgeRecord([[maybe_unused]] EdgeRecord&& other) noexcept :
    __fbthrift_field_src_vertex_id(std::move(other.__fbthrift_field_src_vertex_id)),
    __fbthrift_field_dst_vertex_id(std::move(other.__fbthrift_field_dst_vertex_id)),
    __fbthrift_field_properties(std::move(other.__fbthrift_field_properties)),
    __isset(other.__isset) {
}

EdgeRecord& EdgeRecord::operator=([[maybe_unused]] EdgeRecord&& other) noexcept {
    this->__fbthrift_field_src_vertex_id = std::move(other.__fbthrift_field_src_vertex_id);
    this->__fbthrift_field_dst_vertex_id = std::move(other.__fbthrift_field_dst_vertex_id);
    this->__fbthrift_field_properties = std::move(other.__fbthrift_field_properties);
    __isset = other.__isset;
    return *this;
}


EdgeRecord::EdgeRecord(apache::thrift::FragileConstructor, ::std::int64_t src_vertex_id__arg, ::std::int64_t dst_vertex_id__arg, ::std::vector<::eugraph::thrift::PropertyValueThrift> properties__arg) :
    __fbthrift_field_src_vertex_id(std::move(src_vertex_id__arg)),
    __fbthrift_field_dst_vertex_id(std::move(dst_vertex_id__arg)),
    __fbthrift_field_properties(std::move(properties__arg)) { 
  __isset.set(folly::index_constant<0>(), true);
  __isset.set(folly::index_constant<1>(), true);
  __isset.set(folly::index_constant<2>(), true);
}


void EdgeRecord::__fbthrift_clear() {
  // clear all fields
  this->__fbthrift_field_src_vertex_id = ::std::int64_t();
  this->__fbthrift_field_dst_vertex_id = ::std::int64_t();
  this->__fbthrift_field_properties.clear();
  __isset = {};
}

void EdgeRecord::__fbthrift_clear_terse_fields() {
}

bool EdgeRecord::__fbthrift_is_empty() const {
  return false;
}

bool EdgeRecord::operator==([[maybe_unused]] const EdgeRecord& rhs) const {
  return ::apache::thrift::op::detail::StructEquality{}(*this, rhs);
}

bool EdgeRecord::operator<([[maybe_unused]] const EdgeRecord& rhs) const {
  return ::apache::thrift::op::detail::StructLessThan{}(*this, rhs);
}


::std::int64_t EdgeRecord::get_src_vertex_id() const {
  return __fbthrift_field_src_vertex_id;
}

::std::int64_t& EdgeRecord::set_src_vertex_id(::std::int64_t src_vertex_id_) {
  src_vertex_id_ref() = src_vertex_id_;
  return __fbthrift_field_src_vertex_id;
}

::std::int64_t EdgeRecord::get_dst_vertex_id() const {
  return __fbthrift_field_dst_vertex_id;
}

::std::int64_t& EdgeRecord::set_dst_vertex_id(::std::int64_t dst_vertex_id_) {
  dst_vertex_id_ref() = dst_vertex_id_;
  return __fbthrift_field_dst_vertex_id;
}

const ::std::vector<::eugraph::thrift::PropertyValueThrift>& EdgeRecord::get_properties() const& {
  return __fbthrift_field_properties;
}

::std::vector<::eugraph::thrift::PropertyValueThrift> EdgeRecord::get_properties() && {
  return static_cast<::std::vector<::eugraph::thrift::PropertyValueThrift>&&>(__fbthrift_field_properties);
}

void swap([[maybe_unused]] EdgeRecord& a, [[maybe_unused]] EdgeRecord& b) {
  using ::std::swap;
  swap(a.__fbthrift_field_src_vertex_id, b.__fbthrift_field_src_vertex_id);
  swap(a.__fbthrift_field_dst_vertex_id, b.__fbthrift_field_dst_vertex_id);
  swap(a.__fbthrift_field_properties, b.__fbthrift_field_properties);
  swap(a.__isset, b.__isset);
}

#ifndef __FBTHRIFT_INSTANTIATE_COMPACT_BINARY_PROTOCOL_IN_SEPARATE_TU
template void EdgeRecord::readNoXfer<>(apache::thrift::BinaryProtocolReader*);
template uint32_t EdgeRecord::write<>(apache::thrift::BinaryProtocolWriter*) const;
template uint32_t EdgeRecord::serializedSize<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t EdgeRecord::serializedSizeZC<>(apache::thrift::BinaryProtocolWriter const*) const;
template void EdgeRecord::readNoXfer<>(apache::thrift::CompactProtocolReader*);
template uint32_t EdgeRecord::write<>(apache::thrift::CompactProtocolWriter*) const;
template uint32_t EdgeRecord::serializedSize<>(apache::thrift::CompactProtocolWriter const*) const;
template uint32_t EdgeRecord::serializedSizeZC<>(apache::thrift::CompactProtocolWriter const*) const;
#endif

static_assert(
    ::apache::thrift::detail::st::gen_check_json<
        EdgeRecord,
        ::apache::thrift::type_class::list<::apache::thrift::type_class::variant>,
        ::std::vector<::eugraph::thrift::PropertyValueThrift>>,
    "inconsistent use of json option");

} // namespace eugraph::thrift

namespace apache {
namespace thrift {
namespace detail {

void TccStructTraits<::eugraph::thrift::BatchInsertVerticesResult>::translateFieldName(
    std::string_view _fname,
    int16_t& fid,
    apache::thrift::protocol::TType& _ftype) noexcept {
  using data = apache::thrift::TStructDataStorage<::eugraph::thrift::BatchInsertVerticesResult>;
  static const st::translate_field_name_table table{
      data::fields_size,
      data::fields_names.data(),
      data::fields_ids.data(),
      data::fields_types.data()};
  st::translate_field_name(_fname, fid, _ftype, table);
}

} // namespace detail
} // namespace thrift
} // namespace apache

namespace eugraph::thrift {

std::string_view BatchInsertVerticesResult::__fbthrift_get_field_name(::apache::thrift::FieldOrdinal ord) {
  if (ord == ::apache::thrift::FieldOrdinal{0}) { return {}; }
  return apache::thrift::TStructDataStorage<BatchInsertVerticesResult>::fields_names[folly::to_underlying(ord) - 1];
}
std::string_view BatchInsertVerticesResult::__fbthrift_get_class_name() {
  return apache::thrift::TStructDataStorage<BatchInsertVerticesResult>::name;
}

BatchInsertVerticesResult::BatchInsertVerticesResult(const BatchInsertVerticesResult&) = default;
BatchInsertVerticesResult& BatchInsertVerticesResult::operator=(const BatchInsertVerticesResult&) = default;
BatchInsertVerticesResult::BatchInsertVerticesResult() :
    __fbthrift_field_count() {
}


BatchInsertVerticesResult::~BatchInsertVerticesResult() {}

BatchInsertVerticesResult::BatchInsertVerticesResult([[maybe_unused]] BatchInsertVerticesResult&& other) noexcept :
    __fbthrift_field_vertex_ids(std::move(other.__fbthrift_field_vertex_ids)),
    __fbthrift_field_count(std::move(other.__fbthrift_field_count)),
    __isset(other.__isset) {
}

BatchInsertVerticesResult& BatchInsertVerticesResult::operator=([[maybe_unused]] BatchInsertVerticesResult&& other) noexcept {
    this->__fbthrift_field_vertex_ids = std::move(other.__fbthrift_field_vertex_ids);
    this->__fbthrift_field_count = std::move(other.__fbthrift_field_count);
    __isset = other.__isset;
    return *this;
}


BatchInsertVerticesResult::BatchInsertVerticesResult(apache::thrift::FragileConstructor, ::std::vector<::std::int64_t> vertex_ids__arg, ::std::int32_t count__arg) :
    __fbthrift_field_vertex_ids(std::move(vertex_ids__arg)),
    __fbthrift_field_count(std::move(count__arg)) { 
  __isset.set(folly::index_constant<0>(), true);
  __isset.set(folly::index_constant<1>(), true);
}


void BatchInsertVerticesResult::__fbthrift_clear() {
  // clear all fields
  this->__fbthrift_field_vertex_ids.clear();
  this->__fbthrift_field_count = ::std::int32_t();
  __isset = {};
}

void BatchInsertVerticesResult::__fbthrift_clear_terse_fields() {
}

bool BatchInsertVerticesResult::__fbthrift_is_empty() const {
  return false;
}

bool BatchInsertVerticesResult::operator==([[maybe_unused]] const BatchInsertVerticesResult& rhs) const {
  return ::apache::thrift::op::detail::StructEquality{}(*this, rhs);
}

bool BatchInsertVerticesResult::operator<([[maybe_unused]] const BatchInsertVerticesResult& rhs) const {
  return ::apache::thrift::op::detail::StructLessThan{}(*this, rhs);
}


const ::std::vector<::std::int64_t>& BatchInsertVerticesResult::get_vertex_ids() const& {
  return __fbthrift_field_vertex_ids;
}

::std::vector<::std::int64_t> BatchInsertVerticesResult::get_vertex_ids() && {
  return static_cast<::std::vector<::std::int64_t>&&>(__fbthrift_field_vertex_ids);
}

::std::int32_t BatchInsertVerticesResult::get_count() const {
  return __fbthrift_field_count;
}

::std::int32_t& BatchInsertVerticesResult::set_count(::std::int32_t count_) {
  count_ref() = count_;
  return __fbthrift_field_count;
}

void swap([[maybe_unused]] BatchInsertVerticesResult& a, [[maybe_unused]] BatchInsertVerticesResult& b) {
  using ::std::swap;
  swap(a.__fbthrift_field_vertex_ids, b.__fbthrift_field_vertex_ids);
  swap(a.__fbthrift_field_count, b.__fbthrift_field_count);
  swap(a.__isset, b.__isset);
}

#ifndef __FBTHRIFT_INSTANTIATE_COMPACT_BINARY_PROTOCOL_IN_SEPARATE_TU
template void BatchInsertVerticesResult::readNoXfer<>(apache::thrift::BinaryProtocolReader*);
template uint32_t BatchInsertVerticesResult::write<>(apache::thrift::BinaryProtocolWriter*) const;
template uint32_t BatchInsertVerticesResult::serializedSize<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t BatchInsertVerticesResult::serializedSizeZC<>(apache::thrift::BinaryProtocolWriter const*) const;
template void BatchInsertVerticesResult::readNoXfer<>(apache::thrift::CompactProtocolReader*);
template uint32_t BatchInsertVerticesResult::write<>(apache::thrift::CompactProtocolWriter*) const;
template uint32_t BatchInsertVerticesResult::serializedSize<>(apache::thrift::CompactProtocolWriter const*) const;
template uint32_t BatchInsertVerticesResult::serializedSizeZC<>(apache::thrift::CompactProtocolWriter const*) const;
#endif


} // namespace eugraph::thrift

namespace apache {
namespace thrift {
namespace detail {

void TccStructTraits<::eugraph::thrift::ResultValue>::translateFieldName(
    std::string_view _fname,
    int16_t& fid,
    apache::thrift::protocol::TType& _ftype) noexcept {
  using data = apache::thrift::TStructDataStorage<::eugraph::thrift::ResultValue>;
  static const st::translate_field_name_table table{
      data::fields_size,
      data::fields_names.data(),
      data::fields_ids.data(),
      data::fields_types.data()};
  st::translate_field_name(_fname, fid, _ftype, table);
}

} // namespace detail
} // namespace thrift
} // namespace apache

namespace apache { namespace thrift {

folly::Range<::eugraph::thrift::ResultValue::Type const*> const TEnumTraits<::eugraph::thrift::ResultValue::Type>::values = folly::range(TEnumDataStorage<::eugraph::thrift::ResultValue::Type>::values);
folly::Range<std::string_view const*> const TEnumTraits<::eugraph::thrift::ResultValue::Type>::names = folly::range(TEnumDataStorage<::eugraph::thrift::ResultValue::Type>::names);

bool TEnumTraits<::eugraph::thrift::ResultValue::Type>::findName(type value, std::string_view* out) noexcept {
  return ::apache::thrift::detail::st::enum_find_name(value, out);
}

bool TEnumTraits<::eugraph::thrift::ResultValue::Type>::findValue(std::string_view name, type* out) noexcept {
  return ::apache::thrift::detail::st::enum_find_value(name, out);
}
}} // apache::thrift
namespace eugraph::thrift {

std::string_view ResultValue::__fbthrift_get_field_name(::apache::thrift::FieldOrdinal ord) {
  if (ord == ::apache::thrift::FieldOrdinal{0}) { return {}; }
  return apache::thrift::TStructDataStorage<ResultValue>::fields_names[folly::to_underlying(ord) - 1];
}
std::string_view ResultValue::__fbthrift_get_class_name() {
  return apache::thrift::TStructDataStorage<ResultValue>::name;
}

void ResultValue::__fbthrift_destruct() {
  switch(getType()) {
    case Type::__EMPTY__:
      break;
    case Type::bool_val:
      ::std::destroy_at(::std::addressof(value_.bool_val));
      break;
    case Type::int_val:
      ::std::destroy_at(::std::addressof(value_.int_val));
      break;
    case Type::double_val:
      ::std::destroy_at(::std::addressof(value_.double_val));
      break;
    case Type::string_val:
      ::std::destroy_at(::std::addressof(value_.string_val));
      break;
    case Type::vertex_json:
      ::std::destroy_at(::std::addressof(value_.vertex_json));
      break;
    case Type::edge_json:
      ::std::destroy_at(::std::addressof(value_.edge_json));
      break;
    default:
      assert(false);
      break;
  }
}

void ResultValue::__fbthrift_clear() {
  __fbthrift_destruct();
  type_ = folly::to_underlying(Type::__EMPTY__);
}

  ResultValue::~ResultValue() {
    __fbthrift_destruct();
  }

bool ResultValue::__fbthrift_is_empty() const {
  return getType() == Type::__EMPTY__;
}
  ResultValue::ResultValue(const ResultValue& rhs)
      : type_(folly::to_underlying(Type::__EMPTY__)) {
    switch (rhs.getType()) {
      case Type::__EMPTY__:
        return;
      case Type::bool_val:
        set_bool_val(rhs.value_.bool_val);
        break;
      case Type::int_val:
        set_int_val(rhs.value_.int_val);
        break;
      case Type::double_val:
        set_double_val(rhs.value_.double_val);
        break;
      case Type::string_val:
        set_string_val(rhs.value_.string_val);
        break;
      case Type::vertex_json:
        set_vertex_json(rhs.value_.vertex_json);
        break;
      case Type::edge_json:
        set_edge_json(rhs.value_.edge_json);
        break;
      default:
        assert(false);
    }
  }

    ResultValue&ResultValue::operator=(const ResultValue& rhs) {
    if (this == &rhs) { return *this; }
    switch (rhs.getType()) {
      case Type::__EMPTY__:
        __fbthrift_clear();
        return *this;
      case Type::bool_val:
        set_bool_val(rhs.value_.bool_val);
        break;
      case Type::int_val:
        set_int_val(rhs.value_.int_val);
        break;
      case Type::double_val:
        set_double_val(rhs.value_.double_val);
        break;
      case Type::string_val:
        set_string_val(rhs.value_.string_val);
        break;
      case Type::vertex_json:
        set_vertex_json(rhs.value_.vertex_json);
        break;
      case Type::edge_json:
        set_edge_json(rhs.value_.edge_json);
        break;
      default:
        __fbthrift_clear();
        assert(false);
    }
    return *this;
  }


bool ResultValue::operator==(const ResultValue& rhs) const {
  return ::apache::thrift::op::detail::UnionEquality{}(*this, rhs);
}

bool ResultValue::operator<([[maybe_unused]] const ResultValue& rhs) const {
  return ::apache::thrift::op::detail::UnionLessThan{}(*this, rhs);
}

void swap(ResultValue& a, ResultValue& b) {
  ResultValue temp(std::move(a));
  a = std::move(b);
  b = std::move(temp);
}

#ifndef __FBTHRIFT_INSTANTIATE_COMPACT_BINARY_PROTOCOL_IN_SEPARATE_TU
template void ResultValue::readNoXfer<>(apache::thrift::BinaryProtocolReader*);
template uint32_t ResultValue::write<>(apache::thrift::BinaryProtocolWriter*) const;
template uint32_t ResultValue::serializedSize<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t ResultValue::serializedSizeZC<>(apache::thrift::BinaryProtocolWriter const*) const;
template void ResultValue::readNoXfer<>(apache::thrift::CompactProtocolReader*);
template uint32_t ResultValue::write<>(apache::thrift::CompactProtocolWriter*) const;
template uint32_t ResultValue::serializedSize<>(apache::thrift::CompactProtocolWriter const*) const;
template uint32_t ResultValue::serializedSizeZC<>(apache::thrift::CompactProtocolWriter const*) const;
#endif


} // namespace eugraph::thrift

namespace apache {
namespace thrift {
namespace detail {

void TccStructTraits<::eugraph::thrift::ResultRow>::translateFieldName(
    std::string_view _fname,
    int16_t& fid,
    apache::thrift::protocol::TType& _ftype) noexcept {
  using data = apache::thrift::TStructDataStorage<::eugraph::thrift::ResultRow>;
  static const st::translate_field_name_table table{
      data::fields_size,
      data::fields_names.data(),
      data::fields_ids.data(),
      data::fields_types.data()};
  st::translate_field_name(_fname, fid, _ftype, table);
}

} // namespace detail
} // namespace thrift
} // namespace apache

namespace eugraph::thrift {

std::string_view ResultRow::__fbthrift_get_field_name(::apache::thrift::FieldOrdinal ord) {
  if (ord == ::apache::thrift::FieldOrdinal{0}) { return {}; }
  return apache::thrift::TStructDataStorage<ResultRow>::fields_names[folly::to_underlying(ord) - 1];
}
std::string_view ResultRow::__fbthrift_get_class_name() {
  return apache::thrift::TStructDataStorage<ResultRow>::name;
}

ResultRow::ResultRow(const ResultRow&) = default;
ResultRow& ResultRow::operator=(const ResultRow&) = default;
ResultRow::ResultRow() {
}


ResultRow::~ResultRow() {}

ResultRow::ResultRow([[maybe_unused]] ResultRow&& other) noexcept :
    __fbthrift_field_values(std::move(other.__fbthrift_field_values)),
    __isset(other.__isset) {
}

ResultRow& ResultRow::operator=([[maybe_unused]] ResultRow&& other) noexcept {
    this->__fbthrift_field_values = std::move(other.__fbthrift_field_values);
    __isset = other.__isset;
    return *this;
}


ResultRow::ResultRow(apache::thrift::FragileConstructor, ::std::vector<::eugraph::thrift::ResultValue> values__arg) :
    __fbthrift_field_values(std::move(values__arg)) { 
  __isset.set(folly::index_constant<0>(), true);
}


void ResultRow::__fbthrift_clear() {
  // clear all fields
  this->__fbthrift_field_values.clear();
  __isset = {};
}

void ResultRow::__fbthrift_clear_terse_fields() {
}

bool ResultRow::__fbthrift_is_empty() const {
  return false;
}

bool ResultRow::operator==([[maybe_unused]] const ResultRow& rhs) const {
  return ::apache::thrift::op::detail::StructEquality{}(*this, rhs);
}

bool ResultRow::operator<([[maybe_unused]] const ResultRow& rhs) const {
  return ::apache::thrift::op::detail::StructLessThan{}(*this, rhs);
}


const ::std::vector<::eugraph::thrift::ResultValue>& ResultRow::get_values() const& {
  return __fbthrift_field_values;
}

::std::vector<::eugraph::thrift::ResultValue> ResultRow::get_values() && {
  return static_cast<::std::vector<::eugraph::thrift::ResultValue>&&>(__fbthrift_field_values);
}

void swap([[maybe_unused]] ResultRow& a, [[maybe_unused]] ResultRow& b) {
  using ::std::swap;
  swap(a.__fbthrift_field_values, b.__fbthrift_field_values);
  swap(a.__isset, b.__isset);
}

#ifndef __FBTHRIFT_INSTANTIATE_COMPACT_BINARY_PROTOCOL_IN_SEPARATE_TU
template void ResultRow::readNoXfer<>(apache::thrift::BinaryProtocolReader*);
template uint32_t ResultRow::write<>(apache::thrift::BinaryProtocolWriter*) const;
template uint32_t ResultRow::serializedSize<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t ResultRow::serializedSizeZC<>(apache::thrift::BinaryProtocolWriter const*) const;
template void ResultRow::readNoXfer<>(apache::thrift::CompactProtocolReader*);
template uint32_t ResultRow::write<>(apache::thrift::CompactProtocolWriter*) const;
template uint32_t ResultRow::serializedSize<>(apache::thrift::CompactProtocolWriter const*) const;
template uint32_t ResultRow::serializedSizeZC<>(apache::thrift::CompactProtocolWriter const*) const;
#endif

static_assert(
    ::apache::thrift::detail::st::gen_check_json<
        ResultRow,
        ::apache::thrift::type_class::list<::apache::thrift::type_class::variant>,
        ::std::vector<::eugraph::thrift::ResultValue>>,
    "inconsistent use of json option");

} // namespace eugraph::thrift

namespace apache {
namespace thrift {
namespace detail {

void TccStructTraits<::eugraph::thrift::QueryResult>::translateFieldName(
    std::string_view _fname,
    int16_t& fid,
    apache::thrift::protocol::TType& _ftype) noexcept {
  using data = apache::thrift::TStructDataStorage<::eugraph::thrift::QueryResult>;
  static const st::translate_field_name_table table{
      data::fields_size,
      data::fields_names.data(),
      data::fields_ids.data(),
      data::fields_types.data()};
  st::translate_field_name(_fname, fid, _ftype, table);
}

} // namespace detail
} // namespace thrift
} // namespace apache

namespace eugraph::thrift {

std::string_view QueryResult::__fbthrift_get_field_name(::apache::thrift::FieldOrdinal ord) {
  if (ord == ::apache::thrift::FieldOrdinal{0}) { return {}; }
  return apache::thrift::TStructDataStorage<QueryResult>::fields_names[folly::to_underlying(ord) - 1];
}
std::string_view QueryResult::__fbthrift_get_class_name() {
  return apache::thrift::TStructDataStorage<QueryResult>::name;
}

QueryResult::QueryResult(const QueryResult&) = default;
QueryResult& QueryResult::operator=(const QueryResult&) = default;
QueryResult::QueryResult() :
    __fbthrift_field_rows_affected(static_cast<::std::int64_t>(0)) {
}


QueryResult::~QueryResult() {}

QueryResult::QueryResult([[maybe_unused]] QueryResult&& other) noexcept :
    __fbthrift_field_columns(std::move(other.__fbthrift_field_columns)),
    __fbthrift_field_rows(std::move(other.__fbthrift_field_rows)),
    __fbthrift_field_rows_affected(std::move(other.__fbthrift_field_rows_affected)),
    __fbthrift_field_error(std::move(other.__fbthrift_field_error)),
    __isset(other.__isset) {
}

QueryResult& QueryResult::operator=([[maybe_unused]] QueryResult&& other) noexcept {
    this->__fbthrift_field_columns = std::move(other.__fbthrift_field_columns);
    this->__fbthrift_field_rows = std::move(other.__fbthrift_field_rows);
    this->__fbthrift_field_rows_affected = std::move(other.__fbthrift_field_rows_affected);
    this->__fbthrift_field_error = std::move(other.__fbthrift_field_error);
    __isset = other.__isset;
    return *this;
}


QueryResult::QueryResult(apache::thrift::FragileConstructor, ::std::vector<::std::string> columns__arg, ::std::vector<::eugraph::thrift::ResultRow> rows__arg, ::std::int64_t rows_affected__arg, ::std::string error__arg) :
    __fbthrift_field_columns(std::move(columns__arg)),
    __fbthrift_field_rows(std::move(rows__arg)),
    __fbthrift_field_rows_affected(std::move(rows_affected__arg)),
    __fbthrift_field_error(std::move(error__arg)) { 
  __isset.set(folly::index_constant<0>(), true);
  __isset.set(folly::index_constant<1>(), true);
  __isset.set(folly::index_constant<2>(), true);
  __isset.set(folly::index_constant<3>(), true);
}


void QueryResult::__fbthrift_clear() {
  // clear all fields
  this->__fbthrift_field_columns.clear();
  this->__fbthrift_field_rows.clear();
  this->__fbthrift_field_rows_affected = ::std::int64_t();
  this->__fbthrift_field_error = apache::thrift::StringTraits<::std::string>::fromStringLiteral("");
  __isset = {};
}

void QueryResult::__fbthrift_clear_terse_fields() {
}

bool QueryResult::__fbthrift_is_empty() const {
  return false;
}

bool QueryResult::operator==([[maybe_unused]] const QueryResult& rhs) const {
  return ::apache::thrift::op::detail::StructEquality{}(*this, rhs);
}

bool QueryResult::operator<([[maybe_unused]] const QueryResult& rhs) const {
  return ::apache::thrift::op::detail::StructLessThan{}(*this, rhs);
}


const ::std::vector<::std::string>& QueryResult::get_columns() const& {
  return __fbthrift_field_columns;
}

::std::vector<::std::string> QueryResult::get_columns() && {
  return static_cast<::std::vector<::std::string>&&>(__fbthrift_field_columns);
}

const ::std::vector<::eugraph::thrift::ResultRow>& QueryResult::get_rows() const& {
  return __fbthrift_field_rows;
}

::std::vector<::eugraph::thrift::ResultRow> QueryResult::get_rows() && {
  return static_cast<::std::vector<::eugraph::thrift::ResultRow>&&>(__fbthrift_field_rows);
}

::std::int64_t QueryResult::get_rows_affected() const {
  return __fbthrift_field_rows_affected;
}

::std::int64_t& QueryResult::set_rows_affected(::std::int64_t rows_affected_) {
  rows_affected_ref() = rows_affected_;
  return __fbthrift_field_rows_affected;
}

void swap([[maybe_unused]] QueryResult& a, [[maybe_unused]] QueryResult& b) {
  using ::std::swap;
  swap(a.__fbthrift_field_columns, b.__fbthrift_field_columns);
  swap(a.__fbthrift_field_rows, b.__fbthrift_field_rows);
  swap(a.__fbthrift_field_rows_affected, b.__fbthrift_field_rows_affected);
  swap(a.__fbthrift_field_error, b.__fbthrift_field_error);
  swap(a.__isset, b.__isset);
}

#ifndef __FBTHRIFT_INSTANTIATE_COMPACT_BINARY_PROTOCOL_IN_SEPARATE_TU
template void QueryResult::readNoXfer<>(apache::thrift::BinaryProtocolReader*);
template uint32_t QueryResult::write<>(apache::thrift::BinaryProtocolWriter*) const;
template uint32_t QueryResult::serializedSize<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t QueryResult::serializedSizeZC<>(apache::thrift::BinaryProtocolWriter const*) const;
template void QueryResult::readNoXfer<>(apache::thrift::CompactProtocolReader*);
template uint32_t QueryResult::write<>(apache::thrift::CompactProtocolWriter*) const;
template uint32_t QueryResult::serializedSize<>(apache::thrift::CompactProtocolWriter const*) const;
template uint32_t QueryResult::serializedSizeZC<>(apache::thrift::CompactProtocolWriter const*) const;
#endif

static_assert(
    ::apache::thrift::detail::st::gen_check_json<
        QueryResult,
        ::apache::thrift::type_class::list<::apache::thrift::type_class::structure>,
        ::std::vector<::eugraph::thrift::ResultRow>>,
    "inconsistent use of json option");

} // namespace eugraph::thrift

namespace eugraph::thrift { namespace {
[[maybe_unused]] FOLLY_ERASE void validateAdapters() {
}
}} // namespace eugraph::thrift
namespace apache::thrift::detail::annotation {
}
