/**
 * Autogenerated by Thrift for /mnt/f/code/eugraph/proto/eugraph.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated @nocommit
 */
#pragma once

#include <thrift/lib/cpp2/gen/service_h.h>

#include "gen-cpp2/EuGraphServiceAsyncClient.h"
#include "gen-cpp2/eugraph_types.h"
#include <thrift/lib/cpp2/async/ServerStream.h>

namespace folly {
  class IOBuf;
  class IOBufQueue;
}
namespace apache { namespace thrift {
  class Cpp2RequestContext;
  class BinaryProtocolReader;
  class CompactProtocolReader;
  namespace transport { class THeader; }
}}

namespace eugraph::thrift {
class EuGraphService;
class EuGraphServiceAsyncProcessor;

class EuGraphServiceServiceInfoHolder : public apache::thrift::ServiceInfoHolder {
  public:
   apache::thrift::ServiceRequestInfoMap const& requestInfoMap() const override;
   static apache::thrift::ServiceRequestInfoMap staticRequestInfoMap();
};
} // namespace eugraph::thrift

namespace apache::thrift {
template <>
class ServiceHandler<::eugraph::thrift::EuGraphService> : public apache::thrift::ServerInterface {
  static_assert(!folly::is_detected_v<::apache::thrift::detail::st::detect_complete, ::eugraph::thrift::EuGraphService>, "Definition collision with service tag. Either rename the Thrift service using @cpp.Name annotation or rename the conflicting C++ type.");

 public:
  std::string_view getGeneratedName() const override { return "EuGraphService"; }

  typedef ::eugraph::thrift::EuGraphServiceAsyncProcessor ProcessorType;
  std::unique_ptr<apache::thrift::AsyncProcessor> getProcessor() override;
  CreateMethodMetadataResult createMethodMetadata() override;
  bool isThriftGenerated() const override final { return true; }
 private:
  std::optional<std::reference_wrapper<apache::thrift::ServiceRequestInfoMap const>> getServiceRequestInfoMap() const;
 public:

  virtual void sync_createLabel(::eugraph::thrift::LabelInfo& /*_return*/, std::unique_ptr<::std::string> /*name*/, std::unique_ptr<::std::vector<::eugraph::thrift::PropertyDefThrift>> /*properties*/);
  [[deprecated("Use sync_createLabel instead")]] virtual void createLabel(::eugraph::thrift::LabelInfo& /*_return*/, std::unique_ptr<::std::string> /*name*/, std::unique_ptr<::std::vector<::eugraph::thrift::PropertyDefThrift>> /*properties*/);
  virtual folly::Future<std::unique_ptr<::eugraph::thrift::LabelInfo>> future_createLabel(std::unique_ptr<::std::string> p_name, std::unique_ptr<::std::vector<::eugraph::thrift::PropertyDefThrift>> p_properties);
  virtual folly::SemiFuture<std::unique_ptr<::eugraph::thrift::LabelInfo>> semifuture_createLabel(std::unique_ptr<::std::string> p_name, std::unique_ptr<::std::vector<::eugraph::thrift::PropertyDefThrift>> p_properties);
#if FOLLY_HAS_COROUTINES
  virtual folly::coro::Task<std::unique_ptr<::eugraph::thrift::LabelInfo>> co_createLabel(std::unique_ptr<::std::string> p_name, std::unique_ptr<::std::vector<::eugraph::thrift::PropertyDefThrift>> p_properties);
  virtual folly::coro::Task<std::unique_ptr<::eugraph::thrift::LabelInfo>> co_createLabel(apache::thrift::RequestParams params, std::unique_ptr<::std::string> p_name, std::unique_ptr<::std::vector<::eugraph::thrift::PropertyDefThrift>> p_properties);
#endif
  virtual void async_tm_createLabel(apache::thrift::HandlerCallbackPtr<std::unique_ptr<::eugraph::thrift::LabelInfo>> callback, std::unique_ptr<::std::string> p_name, std::unique_ptr<::std::vector<::eugraph::thrift::PropertyDefThrift>> p_properties);
  virtual void sync_listLabels(::std::vector<::eugraph::thrift::LabelInfo>& /*_return*/);
  [[deprecated("Use sync_listLabels instead")]] virtual void listLabels(::std::vector<::eugraph::thrift::LabelInfo>& /*_return*/);
  virtual folly::Future<std::unique_ptr<::std::vector<::eugraph::thrift::LabelInfo>>> future_listLabels();
  virtual folly::SemiFuture<std::unique_ptr<::std::vector<::eugraph::thrift::LabelInfo>>> semifuture_listLabels();
#if FOLLY_HAS_COROUTINES
  virtual folly::coro::Task<std::unique_ptr<::std::vector<::eugraph::thrift::LabelInfo>>> co_listLabels();
  virtual folly::coro::Task<std::unique_ptr<::std::vector<::eugraph::thrift::LabelInfo>>> co_listLabels(apache::thrift::RequestParams params);
#endif
  virtual void async_tm_listLabels(apache::thrift::HandlerCallbackPtr<std::unique_ptr<::std::vector<::eugraph::thrift::LabelInfo>>> callback);
  virtual void sync_createEdgeLabel(::eugraph::thrift::EdgeLabelInfo& /*_return*/, std::unique_ptr<::std::string> /*name*/, std::unique_ptr<::std::vector<::eugraph::thrift::PropertyDefThrift>> /*properties*/);
  [[deprecated("Use sync_createEdgeLabel instead")]] virtual void createEdgeLabel(::eugraph::thrift::EdgeLabelInfo& /*_return*/, std::unique_ptr<::std::string> /*name*/, std::unique_ptr<::std::vector<::eugraph::thrift::PropertyDefThrift>> /*properties*/);
  virtual folly::Future<std::unique_ptr<::eugraph::thrift::EdgeLabelInfo>> future_createEdgeLabel(std::unique_ptr<::std::string> p_name, std::unique_ptr<::std::vector<::eugraph::thrift::PropertyDefThrift>> p_properties);
  virtual folly::SemiFuture<std::unique_ptr<::eugraph::thrift::EdgeLabelInfo>> semifuture_createEdgeLabel(std::unique_ptr<::std::string> p_name, std::unique_ptr<::std::vector<::eugraph::thrift::PropertyDefThrift>> p_properties);
#if FOLLY_HAS_COROUTINES
  virtual folly::coro::Task<std::unique_ptr<::eugraph::thrift::EdgeLabelInfo>> co_createEdgeLabel(std::unique_ptr<::std::string> p_name, std::unique_ptr<::std::vector<::eugraph::thrift::PropertyDefThrift>> p_properties);
  virtual folly::coro::Task<std::unique_ptr<::eugraph::thrift::EdgeLabelInfo>> co_createEdgeLabel(apache::thrift::RequestParams params, std::unique_ptr<::std::string> p_name, std::unique_ptr<::std::vector<::eugraph::thrift::PropertyDefThrift>> p_properties);
#endif
  virtual void async_tm_createEdgeLabel(apache::thrift::HandlerCallbackPtr<std::unique_ptr<::eugraph::thrift::EdgeLabelInfo>> callback, std::unique_ptr<::std::string> p_name, std::unique_ptr<::std::vector<::eugraph::thrift::PropertyDefThrift>> p_properties);
  virtual void sync_listEdgeLabels(::std::vector<::eugraph::thrift::EdgeLabelInfo>& /*_return*/);
  [[deprecated("Use sync_listEdgeLabels instead")]] virtual void listEdgeLabels(::std::vector<::eugraph::thrift::EdgeLabelInfo>& /*_return*/);
  virtual folly::Future<std::unique_ptr<::std::vector<::eugraph::thrift::EdgeLabelInfo>>> future_listEdgeLabels();
  virtual folly::SemiFuture<std::unique_ptr<::std::vector<::eugraph::thrift::EdgeLabelInfo>>> semifuture_listEdgeLabels();
#if FOLLY_HAS_COROUTINES
  virtual folly::coro::Task<std::unique_ptr<::std::vector<::eugraph::thrift::EdgeLabelInfo>>> co_listEdgeLabels();
  virtual folly::coro::Task<std::unique_ptr<::std::vector<::eugraph::thrift::EdgeLabelInfo>>> co_listEdgeLabels(apache::thrift::RequestParams params);
#endif
  virtual void async_tm_listEdgeLabels(apache::thrift::HandlerCallbackPtr<std::unique_ptr<::std::vector<::eugraph::thrift::EdgeLabelInfo>>> callback);
  virtual ::apache::thrift::ResponseAndServerStream<::eugraph::thrift::QueryStreamMeta, ::eugraph::thrift::ResultRowBatch> sync_executeCypher(std::unique_ptr<::std::string> /*query*/);
  [[deprecated("Use sync_executeCypher instead")]] virtual ::apache::thrift::ResponseAndServerStream<::eugraph::thrift::QueryStreamMeta, ::eugraph::thrift::ResultRowBatch> executeCypher(std::unique_ptr<::std::string> /*query*/);
  virtual folly::Future<::apache::thrift::ResponseAndServerStream<::eugraph::thrift::QueryStreamMeta, ::eugraph::thrift::ResultRowBatch>> future_executeCypher(std::unique_ptr<::std::string> p_query);
  virtual folly::SemiFuture<::apache::thrift::ResponseAndServerStream<::eugraph::thrift::QueryStreamMeta, ::eugraph::thrift::ResultRowBatch>> semifuture_executeCypher(std::unique_ptr<::std::string> p_query);
#if FOLLY_HAS_COROUTINES
  virtual folly::coro::Task<::apache::thrift::ResponseAndServerStream<::eugraph::thrift::QueryStreamMeta, ::eugraph::thrift::ResultRowBatch>> co_executeCypher(std::unique_ptr<::std::string> p_query);
  virtual folly::coro::Task<::apache::thrift::ResponseAndServerStream<::eugraph::thrift::QueryStreamMeta, ::eugraph::thrift::ResultRowBatch>> co_executeCypher(apache::thrift::RequestParams params, std::unique_ptr<::std::string> p_query);
#endif
  virtual void async_tm_executeCypher(apache::thrift::HandlerCallbackPtr<::apache::thrift::ResponseAndServerStream<::eugraph::thrift::QueryStreamMeta, ::eugraph::thrift::ResultRowBatch>> callback, std::unique_ptr<::std::string> p_query);
  virtual void sync_batchInsertVertices(::eugraph::thrift::BatchInsertVerticesResult& /*_return*/, std::unique_ptr<::std::string> /*label_name*/, std::unique_ptr<::std::vector<::eugraph::thrift::VertexRecord>> /*records*/);
  [[deprecated("Use sync_batchInsertVertices instead")]] virtual void batchInsertVertices(::eugraph::thrift::BatchInsertVerticesResult& /*_return*/, std::unique_ptr<::std::string> /*label_name*/, std::unique_ptr<::std::vector<::eugraph::thrift::VertexRecord>> /*records*/);
  virtual folly::Future<std::unique_ptr<::eugraph::thrift::BatchInsertVerticesResult>> future_batchInsertVertices(std::unique_ptr<::std::string> p_label_name, std::unique_ptr<::std::vector<::eugraph::thrift::VertexRecord>> p_records);
  virtual folly::SemiFuture<std::unique_ptr<::eugraph::thrift::BatchInsertVerticesResult>> semifuture_batchInsertVertices(std::unique_ptr<::std::string> p_label_name, std::unique_ptr<::std::vector<::eugraph::thrift::VertexRecord>> p_records);
#if FOLLY_HAS_COROUTINES
  virtual folly::coro::Task<std::unique_ptr<::eugraph::thrift::BatchInsertVerticesResult>> co_batchInsertVertices(std::unique_ptr<::std::string> p_label_name, std::unique_ptr<::std::vector<::eugraph::thrift::VertexRecord>> p_records);
  virtual folly::coro::Task<std::unique_ptr<::eugraph::thrift::BatchInsertVerticesResult>> co_batchInsertVertices(apache::thrift::RequestParams params, std::unique_ptr<::std::string> p_label_name, std::unique_ptr<::std::vector<::eugraph::thrift::VertexRecord>> p_records);
#endif
  virtual void async_tm_batchInsertVertices(apache::thrift::HandlerCallbackPtr<std::unique_ptr<::eugraph::thrift::BatchInsertVerticesResult>> callback, std::unique_ptr<::std::string> p_label_name, std::unique_ptr<::std::vector<::eugraph::thrift::VertexRecord>> p_records);
  virtual ::std::int32_t sync_batchInsertEdges(std::unique_ptr<::std::string> /*edge_label_name*/, std::unique_ptr<::std::vector<::eugraph::thrift::EdgeRecord>> /*records*/);
  [[deprecated("Use sync_batchInsertEdges instead")]] virtual ::std::int32_t batchInsertEdges(std::unique_ptr<::std::string> /*edge_label_name*/, std::unique_ptr<::std::vector<::eugraph::thrift::EdgeRecord>> /*records*/);
  virtual folly::Future<::std::int32_t> future_batchInsertEdges(std::unique_ptr<::std::string> p_edge_label_name, std::unique_ptr<::std::vector<::eugraph::thrift::EdgeRecord>> p_records);
  virtual folly::SemiFuture<::std::int32_t> semifuture_batchInsertEdges(std::unique_ptr<::std::string> p_edge_label_name, std::unique_ptr<::std::vector<::eugraph::thrift::EdgeRecord>> p_records);
#if FOLLY_HAS_COROUTINES
  virtual folly::coro::Task<::std::int32_t> co_batchInsertEdges(std::unique_ptr<::std::string> p_edge_label_name, std::unique_ptr<::std::vector<::eugraph::thrift::EdgeRecord>> p_records);
  virtual folly::coro::Task<::std::int32_t> co_batchInsertEdges(apache::thrift::RequestParams params, std::unique_ptr<::std::string> p_edge_label_name, std::unique_ptr<::std::vector<::eugraph::thrift::EdgeRecord>> p_records);
#endif
  virtual void async_tm_batchInsertEdges(apache::thrift::HandlerCallbackPtr<::std::int32_t> callback, std::unique_ptr<::std::string> p_edge_label_name, std::unique_ptr<::std::vector<::eugraph::thrift::EdgeRecord>> p_records);
 private:
  static ::eugraph::thrift::EuGraphServiceServiceInfoHolder __fbthrift_serviceInfoHolder;
  std::atomic<apache::thrift::detail::si::InvocationType> __fbthrift_invocation_createLabel{apache::thrift::detail::si::InvocationType::AsyncTm};
  std::atomic<apache::thrift::detail::si::InvocationType> __fbthrift_invocation_listLabels{apache::thrift::detail::si::InvocationType::AsyncTm};
  std::atomic<apache::thrift::detail::si::InvocationType> __fbthrift_invocation_createEdgeLabel{apache::thrift::detail::si::InvocationType::AsyncTm};
  std::atomic<apache::thrift::detail::si::InvocationType> __fbthrift_invocation_listEdgeLabels{apache::thrift::detail::si::InvocationType::AsyncTm};
  std::atomic<apache::thrift::detail::si::InvocationType> __fbthrift_invocation_executeCypher{apache::thrift::detail::si::InvocationType::AsyncTm};
  std::atomic<apache::thrift::detail::si::InvocationType> __fbthrift_invocation_batchInsertVertices{apache::thrift::detail::si::InvocationType::AsyncTm};
  std::atomic<apache::thrift::detail::si::InvocationType> __fbthrift_invocation_batchInsertEdges{apache::thrift::detail::si::InvocationType::AsyncTm};
};

namespace detail {
template <> struct TSchemaAssociation<::eugraph::thrift::EuGraphService, false> {
  static ::folly::Range<const ::std::string_view*>(*bundle)();
  static constexpr int64_t programId = 590156813256549374;
  static constexpr ::std::string_view definitionKey = {"\xcf\x1f\x8b\x11\x15\xdc\x5c\xcc\x02\xec\xe9\x6e\x87\xba\xe4\x5f", 16};
};
}
} // namespace apache::thrift

namespace eugraph::thrift {
using EuGraphServiceSvIf [[deprecated("Use apache::thrift::ServiceHandler<EuGraphService> instead")]] = ::apache::thrift::ServiceHandler<EuGraphService>;
} // namespace eugraph::thrift

namespace eugraph::thrift {
class EuGraphServiceSvNull : public ::apache::thrift::ServiceHandler<EuGraphService> {
 public:
  void createLabel(::eugraph::thrift::LabelInfo& /*_return*/, std::unique_ptr<::std::string> /*name*/, std::unique_ptr<::std::vector<::eugraph::thrift::PropertyDefThrift>> /*properties*/) override;
  void listLabels(::std::vector<::eugraph::thrift::LabelInfo>& /*_return*/) override;
  void createEdgeLabel(::eugraph::thrift::EdgeLabelInfo& /*_return*/, std::unique_ptr<::std::string> /*name*/, std::unique_ptr<::std::vector<::eugraph::thrift::PropertyDefThrift>> /*properties*/) override;
  void listEdgeLabels(::std::vector<::eugraph::thrift::EdgeLabelInfo>& /*_return*/) override;
  void batchInsertVertices(::eugraph::thrift::BatchInsertVerticesResult& /*_return*/, std::unique_ptr<::std::string> /*label_name*/, std::unique_ptr<::std::vector<::eugraph::thrift::VertexRecord>> /*records*/) override;
  ::std::int32_t batchInsertEdges(std::unique_ptr<::std::string> /*edge_label_name*/, std::unique_ptr<::std::vector<::eugraph::thrift::EdgeRecord>> /*records*/) override;
};

class EuGraphServiceAsyncProcessor : public ::apache::thrift::GeneratedAsyncProcessorBase {
 public:
  const char* getServiceName() override;
  void getServiceMetadata(apache::thrift::metadata::ThriftServiceMetadataResponse& response) override;
  using BaseAsyncProcessor = void;
 protected:
  ::apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>* iface_;
 public:
  void processSerializedCompressedRequestWithMetadata(apache::thrift::ResponseChannelRequest::UniquePtr req, apache::thrift::SerializedCompressedRequest&& serializedRequest, const apache::thrift::AsyncProcessorFactory::MethodMetadata& methodMetadata, apache::thrift::protocol::PROTOCOL_TYPES protType, apache::thrift::Cpp2RequestContext* context, folly::EventBase* eb, apache::thrift::concurrency::ThreadManager* tm) override;
  void executeRequest(apache::thrift::ServerRequest&& serverRequest, const apache::thrift::AsyncProcessorFactory::MethodMetadata& methodMetadata) override;
 public:
  using ProcessFuncs = GeneratedAsyncProcessorBase::ProcessFuncs<EuGraphServiceAsyncProcessor>;
  using ProcessMap = GeneratedAsyncProcessorBase::ProcessMap<ProcessFuncs>;
  static const EuGraphServiceAsyncProcessor::ProcessMap& getOwnProcessMap();
 private:
  static const EuGraphServiceAsyncProcessor::ProcessMap kOwnProcessMap_;
 private:
  template <typename ProtocolIn_, typename ProtocolOut_>
  void setUpAndProcess_createLabel(apache::thrift::ResponseChannelRequest::UniquePtr req, apache::thrift::SerializedCompressedRequest&& serializedRequest, apache::thrift::Cpp2RequestContext* ctx, folly::EventBase* eb, apache::thrift::concurrency::ThreadManager* tm);
  template <typename ProtocolIn_, typename ProtocolOut_>
  void executeRequest_createLabel(apache::thrift::ServerRequest&& serverRequest);
  template <class ProtocolIn_, class ProtocolOut_>
  static apache::thrift::SerializedResponse return_createLabel(apache::thrift::ContextStack* ctx, ::eugraph::thrift::LabelInfo const& _return);
  template <class ProtocolIn_, class ProtocolOut_>
  static void throw_wrapped_createLabel(apache::thrift::ResponseChannelRequest::UniquePtr req,int32_t protoSeqId,apache::thrift::ContextStack* ctx,folly::exception_wrapper ew,apache::thrift::Cpp2RequestContext* reqCtx);
  template <typename ProtocolIn_, typename ProtocolOut_>
  void setUpAndProcess_listLabels(apache::thrift::ResponseChannelRequest::UniquePtr req, apache::thrift::SerializedCompressedRequest&& serializedRequest, apache::thrift::Cpp2RequestContext* ctx, folly::EventBase* eb, apache::thrift::concurrency::ThreadManager* tm);
  template <typename ProtocolIn_, typename ProtocolOut_>
  void executeRequest_listLabels(apache::thrift::ServerRequest&& serverRequest);
  template <class ProtocolIn_, class ProtocolOut_>
  static apache::thrift::SerializedResponse return_listLabels(apache::thrift::ContextStack* ctx, ::std::vector<::eugraph::thrift::LabelInfo> const& _return);
  template <class ProtocolIn_, class ProtocolOut_>
  static void throw_wrapped_listLabels(apache::thrift::ResponseChannelRequest::UniquePtr req,int32_t protoSeqId,apache::thrift::ContextStack* ctx,folly::exception_wrapper ew,apache::thrift::Cpp2RequestContext* reqCtx);
  template <typename ProtocolIn_, typename ProtocolOut_>
  void setUpAndProcess_createEdgeLabel(apache::thrift::ResponseChannelRequest::UniquePtr req, apache::thrift::SerializedCompressedRequest&& serializedRequest, apache::thrift::Cpp2RequestContext* ctx, folly::EventBase* eb, apache::thrift::concurrency::ThreadManager* tm);
  template <typename ProtocolIn_, typename ProtocolOut_>
  void executeRequest_createEdgeLabel(apache::thrift::ServerRequest&& serverRequest);
  template <class ProtocolIn_, class ProtocolOut_>
  static apache::thrift::SerializedResponse return_createEdgeLabel(apache::thrift::ContextStack* ctx, ::eugraph::thrift::EdgeLabelInfo const& _return);
  template <class ProtocolIn_, class ProtocolOut_>
  static void throw_wrapped_createEdgeLabel(apache::thrift::ResponseChannelRequest::UniquePtr req,int32_t protoSeqId,apache::thrift::ContextStack* ctx,folly::exception_wrapper ew,apache::thrift::Cpp2RequestContext* reqCtx);
  template <typename ProtocolIn_, typename ProtocolOut_>
  void setUpAndProcess_listEdgeLabels(apache::thrift::ResponseChannelRequest::UniquePtr req, apache::thrift::SerializedCompressedRequest&& serializedRequest, apache::thrift::Cpp2RequestContext* ctx, folly::EventBase* eb, apache::thrift::concurrency::ThreadManager* tm);
  template <typename ProtocolIn_, typename ProtocolOut_>
  void executeRequest_listEdgeLabels(apache::thrift::ServerRequest&& serverRequest);
  template <class ProtocolIn_, class ProtocolOut_>
  static apache::thrift::SerializedResponse return_listEdgeLabels(apache::thrift::ContextStack* ctx, ::std::vector<::eugraph::thrift::EdgeLabelInfo> const& _return);
  template <class ProtocolIn_, class ProtocolOut_>
  static void throw_wrapped_listEdgeLabels(apache::thrift::ResponseChannelRequest::UniquePtr req,int32_t protoSeqId,apache::thrift::ContextStack* ctx,folly::exception_wrapper ew,apache::thrift::Cpp2RequestContext* reqCtx);
  template <typename ProtocolIn_, typename ProtocolOut_>
  void setUpAndProcess_executeCypher(apache::thrift::ResponseChannelRequest::UniquePtr req, apache::thrift::SerializedCompressedRequest&& serializedRequest, apache::thrift::Cpp2RequestContext* ctx, folly::EventBase* eb, apache::thrift::concurrency::ThreadManager* tm);
  template <typename ProtocolIn_, typename ProtocolOut_>
  void executeRequest_executeCypher(apache::thrift::ServerRequest&& serverRequest);
  template <class ProtocolIn_, class ProtocolOut_>
  static apache::thrift::ResponseAndServerStreamFactory return_executeCypher(apache::thrift::ContextStack* ctx, folly::Executor::KeepAlive<> executor, ::apache::thrift::ResponseAndServerStream<::eugraph::thrift::QueryStreamMeta, ::eugraph::thrift::ResultRowBatch>&& _return);
  template <class ProtocolIn_, class ProtocolOut_>
  static void throw_wrapped_executeCypher(apache::thrift::ResponseChannelRequest::UniquePtr req,int32_t protoSeqId,apache::thrift::ContextStack* ctx,folly::exception_wrapper ew,apache::thrift::Cpp2RequestContext* reqCtx);
  template <typename ProtocolIn_, typename ProtocolOut_>
  void setUpAndProcess_batchInsertVertices(apache::thrift::ResponseChannelRequest::UniquePtr req, apache::thrift::SerializedCompressedRequest&& serializedRequest, apache::thrift::Cpp2RequestContext* ctx, folly::EventBase* eb, apache::thrift::concurrency::ThreadManager* tm);
  template <typename ProtocolIn_, typename ProtocolOut_>
  void executeRequest_batchInsertVertices(apache::thrift::ServerRequest&& serverRequest);
  template <class ProtocolIn_, class ProtocolOut_>
  static apache::thrift::SerializedResponse return_batchInsertVertices(apache::thrift::ContextStack* ctx, ::eugraph::thrift::BatchInsertVerticesResult const& _return);
  template <class ProtocolIn_, class ProtocolOut_>
  static void throw_wrapped_batchInsertVertices(apache::thrift::ResponseChannelRequest::UniquePtr req,int32_t protoSeqId,apache::thrift::ContextStack* ctx,folly::exception_wrapper ew,apache::thrift::Cpp2RequestContext* reqCtx);
  template <typename ProtocolIn_, typename ProtocolOut_>
  void setUpAndProcess_batchInsertEdges(apache::thrift::ResponseChannelRequest::UniquePtr req, apache::thrift::SerializedCompressedRequest&& serializedRequest, apache::thrift::Cpp2RequestContext* ctx, folly::EventBase* eb, apache::thrift::concurrency::ThreadManager* tm);
  template <typename ProtocolIn_, typename ProtocolOut_>
  void executeRequest_batchInsertEdges(apache::thrift::ServerRequest&& serverRequest);
  template <class ProtocolIn_, class ProtocolOut_>
  static apache::thrift::SerializedResponse return_batchInsertEdges(apache::thrift::ContextStack* ctx, ::std::int32_t const& _return);
  template <class ProtocolIn_, class ProtocolOut_>
  static void throw_wrapped_batchInsertEdges(apache::thrift::ResponseChannelRequest::UniquePtr req,int32_t protoSeqId,apache::thrift::ContextStack* ctx,folly::exception_wrapper ew,apache::thrift::Cpp2RequestContext* reqCtx);
 public:
  EuGraphServiceAsyncProcessor(::apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>* iface) :
      iface_(iface) {}
  ~EuGraphServiceAsyncProcessor() override {}
};

} // namespace eugraph::thrift
