/**
 * Autogenerated by Thrift for proto/eugraph.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated @nocommit
 */
#pragma once

#include <thrift/lib/cpp2/gen/module_constants_h.h>

#include "gen-cpp2/eugraph_types.h"

namespace eugraph::thrift {
/** Glean {"file": "proto/eugraph.thrift"} */
namespace eugraph_constants {

  FOLLY_EXPORT ::std::string_view _fbthrift_schema_41fae82f0b1b067c();
  FOLLY_EXPORT ::folly::Range<const ::std::string_view*> _fbthrift_schema_41fae82f0b1b067c_includes();

} // namespace eugraph_constants
} // namespace eugraph::thrift
