/**
 * Autogenerated by Thrift for /mnt/f/code/eugraph/proto/eugraph.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated @nocommit
 */

#include "gen-cpp2/eugraph_constants.h"

#include <thrift/lib/cpp2/gen/module_constants_cpp.h>


namespace eugraph::thrift {
namespace eugraph_constants {


::std::string_view _fbthrift_schema_830a87eafeee3fe() {
  return "";
}
::folly::Range<const ::std::string_view*> _fbthrift_schema_830a87eafeee3fe_includes() {
  return {};
}

} // namespace eugraph_constants
} // namespace eugraph::thrift
