/**
 * Autogenerated by Thrift for proto/eugraph.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated @nocommit
 */

#include "gen-cpp2/eugraph_constants.h"

#include <thrift/lib/cpp2/gen/module_constants_cpp.h>


namespace eugraph::thrift {
namespace eugraph_constants {


::std::string_view _fbthrift_schema_41fae82f0b1b067c() {
  return "";
}
::folly::Range<const ::std::string_view*> _fbthrift_schema_41fae82f0b1b067c_includes() {
  return {};
}

} // namespace eugraph_constants
} // namespace eugraph::thrift
