/**
 * Autogenerated by Thrift for /home/dodo/code/fuck/eugraph/proto/eugraph.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated @nocommit
 */
#pragma once

#include <thrift/lib/cpp2/gen/module_data_h.h>

#include "gen-cpp2/eugraph_types.h"

namespace apache { namespace thrift {

template <> struct TEnumDataStorage<::eugraph::thrift::PropertyType> {
  using type = ::eugraph::thrift::PropertyType;
  static constexpr const std::size_t size = 13;
  static constexpr std::array<type, size> values = { {
      type::BOOL,
      type::INT64,
      type::DOUBLE,
      type::STRING,
      type::INT64_ARRAY,
      type::DOUBLE_ARRAY,
      type::STRING_ARRAY,
      type::DATETIME,
      type::TIME,
      type::DURATION,
      type::DATETIME_ARRAY,
      type::TIME_ARRAY,
      type::DURATION_ARRAY,
  }};
  static constexpr std::array<std::string_view, size> names = { {
      "BOOL"sv,
      "INT64"sv,
      "DOUBLE"sv,
      "STRING"sv,
      "INT64_ARRAY"sv,
      "DOUBLE_ARRAY"sv,
      "STRING_ARRAY"sv,
      "DATETIME"sv,
      "TIME"sv,
      "DURATION"sv,
      "DATETIME_ARRAY"sv,
      "TIME_ARRAY"sv,
      "DURATION_ARRAY"sv,
  }};
};

template <> struct TEnumDataStorage<::eugraph::thrift::DateTimeKind> {
  using type = ::eugraph::thrift::DateTimeKind;
  static constexpr const std::size_t size = 3;
  static constexpr std::array<type, size> values = { {
      type::DATE,
      type::LOCAL_DATETIME,
      type::DATETIME_WITH_TZ,
  }};
  static constexpr std::array<std::string_view, size> names = { {
      "DATE"sv,
      "LOCAL_DATETIME"sv,
      "DATETIME_WITH_TZ"sv,
  }};
};

template <> struct TEnumDataStorage<::eugraph::thrift::TimeKind> {
  using type = ::eugraph::thrift::TimeKind;
  static constexpr const std::size_t size = 2;
  static constexpr std::array<type, size> values = { {
      type::LOCAL_TIME,
      type::TIME_WITH_TZ,
  }};
  static constexpr std::array<std::string_view, size> names = { {
      "LOCAL_TIME"sv,
      "TIME_WITH_TZ"sv,
  }};
};

template <> struct TEnumDataStorage<::eugraph::thrift::PropertyValueThrift::Type> {
  using type = ::eugraph::thrift::PropertyValueThrift::Type;
  static constexpr const std::size_t size = 13;
  static constexpr std::array<type, size> values = { {
      type::bool_val,
      type::int_val,
      type::double_val,
      type::string_val,
      type::int_array,
      type::double_array,
      type::string_array,
      type::datetime_val,
      type::time_val,
      type::duration_val,
      type::datetime_array,
      type::time_array,
      type::duration_array,
  }};
  static constexpr std::array<std::string_view, size> names = { {
      "bool_val"sv,
      "int_val"sv,
      "double_val"sv,
      "string_val"sv,
      "int_array"sv,
      "double_array"sv,
      "string_array"sv,
      "datetime_val"sv,
      "time_val"sv,
      "duration_val"sv,
      "datetime_array"sv,
      "time_array"sv,
      "duration_array"sv,
  }};
};

template <> struct TEnumDataStorage<::eugraph::thrift::ResultValue::Type> {
  using type = ::eugraph::thrift::ResultValue::Type;
  static constexpr const std::size_t size = 9;
  static constexpr std::array<type, size> values = { {
      type::bool_val,
      type::int_val,
      type::double_val,
      type::string_val,
      type::vertex_json,
      type::edge_json,
      type::path_json,
      type::list_json,
      type::map_json,
  }};
  static constexpr std::array<std::string_view, size> names = { {
      "bool_val"sv,
      "int_val"sv,
      "double_val"sv,
      "string_val"sv,
      "vertex_json"sv,
      "edge_json"sv,
      "path_json"sv,
      "list_json"sv,
      "map_json"sv,
  }};
};

template <> struct TStructDataStorage<::eugraph::thrift::PropertyDefThrift> {
  static constexpr const std::size_t fields_size = 3;
  static const std::string_view name;
  static const std::array<std::string_view, fields_size> fields_names;
  static const std::array<int16_t, fields_size> fields_ids;
  static const std::array<protocol::TType, fields_size> fields_types;

 private:
  // The following fields describe internal storage metadata, and are private to
  // prevent user logic from accessing them, but they can be inspected by
  // debuggers.
  // -1 if the field has no isset.
  static const std::array<int, fields_size> isset_indexes;
};

template <> struct TStructDataStorage<::eugraph::thrift::DateTimeValueThrift> {
  static constexpr const std::size_t fields_size = 10;
  static const std::string_view name;
  static const std::array<std::string_view, fields_size> fields_names;
  static const std::array<int16_t, fields_size> fields_ids;
  static const std::array<protocol::TType, fields_size> fields_types;

 private:
  // The following fields describe internal storage metadata, and are private to
  // prevent user logic from accessing them, but they can be inspected by
  // debuggers.
  // -1 if the field has no isset.
  static const std::array<int, fields_size> isset_indexes;
};

template <> struct TStructDataStorage<::eugraph::thrift::TimeValueThrift> {
  static constexpr const std::size_t fields_size = 7;
  static const std::string_view name;
  static const std::array<std::string_view, fields_size> fields_names;
  static const std::array<int16_t, fields_size> fields_ids;
  static const std::array<protocol::TType, fields_size> fields_types;

 private:
  // The following fields describe internal storage metadata, and are private to
  // prevent user logic from accessing them, but they can be inspected by
  // debuggers.
  // -1 if the field has no isset.
  static const std::array<int, fields_size> isset_indexes;
};

template <> struct TStructDataStorage<::eugraph::thrift::DurationValueThrift> {
  static constexpr const std::size_t fields_size = 4;
  static const std::string_view name;
  static const std::array<std::string_view, fields_size> fields_names;
  static const std::array<int16_t, fields_size> fields_ids;
  static const std::array<protocol::TType, fields_size> fields_types;

 private:
  // The following fields describe internal storage metadata, and are private to
  // prevent user logic from accessing them, but they can be inspected by
  // debuggers.
  // -1 if the field has no isset.
  static const std::array<int, fields_size> isset_indexes;
};

template <> struct TStructDataStorage<::eugraph::thrift::PropertyValueThrift> {
  static constexpr const std::size_t fields_size = 13;
  static const std::string_view name;
  static const std::array<std::string_view, fields_size> fields_names;
  static const std::array<int16_t, fields_size> fields_ids;
  static const std::array<protocol::TType, fields_size> fields_types;

 private:
  // The following fields describe internal storage metadata, and are private to
  // prevent user logic from accessing them, but they can be inspected by
  // debuggers.
  // -1 if the field has no isset.
  static const std::array<int, fields_size> isset_indexes;
};

template <> struct TStructDataStorage<::eugraph::thrift::LabelInfo> {
  static constexpr const std::size_t fields_size = 3;
  static const std::string_view name;
  static const std::array<std::string_view, fields_size> fields_names;
  static const std::array<int16_t, fields_size> fields_ids;
  static const std::array<protocol::TType, fields_size> fields_types;

 private:
  // The following fields describe internal storage metadata, and are private to
  // prevent user logic from accessing them, but they can be inspected by
  // debuggers.
  // -1 if the field has no isset.
  static const std::array<int, fields_size> isset_indexes;
};

template <> struct TStructDataStorage<::eugraph::thrift::EdgeLabelInfo> {
  static constexpr const std::size_t fields_size = 4;
  static const std::string_view name;
  static const std::array<std::string_view, fields_size> fields_names;
  static const std::array<int16_t, fields_size> fields_ids;
  static const std::array<protocol::TType, fields_size> fields_types;

 private:
  // The following fields describe internal storage metadata, and are private to
  // prevent user logic from accessing them, but they can be inspected by
  // debuggers.
  // -1 if the field has no isset.
  static const std::array<int, fields_size> isset_indexes;
};

template <> struct TStructDataStorage<::eugraph::thrift::VertexRecord> {
  static constexpr const std::size_t fields_size = 1;
  static const std::string_view name;
  static const std::array<std::string_view, fields_size> fields_names;
  static const std::array<int16_t, fields_size> fields_ids;
  static const std::array<protocol::TType, fields_size> fields_types;

 private:
  // The following fields describe internal storage metadata, and are private to
  // prevent user logic from accessing them, but they can be inspected by
  // debuggers.
  // -1 if the field has no isset.
  static const std::array<int, fields_size> isset_indexes;
};

template <> struct TStructDataStorage<::eugraph::thrift::EdgeRecord> {
  static constexpr const std::size_t fields_size = 3;
  static const std::string_view name;
  static const std::array<std::string_view, fields_size> fields_names;
  static const std::array<int16_t, fields_size> fields_ids;
  static const std::array<protocol::TType, fields_size> fields_types;

 private:
  // The following fields describe internal storage metadata, and are private to
  // prevent user logic from accessing them, but they can be inspected by
  // debuggers.
  // -1 if the field has no isset.
  static const std::array<int, fields_size> isset_indexes;
};

template <> struct TStructDataStorage<::eugraph::thrift::BatchInsertVerticesResult> {
  static constexpr const std::size_t fields_size = 2;
  static const std::string_view name;
  static const std::array<std::string_view, fields_size> fields_names;
  static const std::array<int16_t, fields_size> fields_ids;
  static const std::array<protocol::TType, fields_size> fields_types;

 private:
  // The following fields describe internal storage metadata, and are private to
  // prevent user logic from accessing them, but they can be inspected by
  // debuggers.
  // -1 if the field has no isset.
  static const std::array<int, fields_size> isset_indexes;
};

template <> struct TStructDataStorage<::eugraph::thrift::ResultValue> {
  static constexpr const std::size_t fields_size = 9;
  static const std::string_view name;
  static const std::array<std::string_view, fields_size> fields_names;
  static const std::array<int16_t, fields_size> fields_ids;
  static const std::array<protocol::TType, fields_size> fields_types;

 private:
  // The following fields describe internal storage metadata, and are private to
  // prevent user logic from accessing them, but they can be inspected by
  // debuggers.
  // -1 if the field has no isset.
  static const std::array<int, fields_size> isset_indexes;
};

template <> struct TStructDataStorage<::eugraph::thrift::ResultRow> {
  static constexpr const std::size_t fields_size = 1;
  static const std::string_view name;
  static const std::array<std::string_view, fields_size> fields_names;
  static const std::array<int16_t, fields_size> fields_ids;
  static const std::array<protocol::TType, fields_size> fields_types;

 private:
  // The following fields describe internal storage metadata, and are private to
  // prevent user logic from accessing them, but they can be inspected by
  // debuggers.
  // -1 if the field has no isset.
  static const std::array<int, fields_size> isset_indexes;
};

template <> struct TStructDataStorage<::eugraph::thrift::QueryStreamMeta> {
  static constexpr const std::size_t fields_size = 1;
  static const std::string_view name;
  static const std::array<std::string_view, fields_size> fields_names;
  static const std::array<int16_t, fields_size> fields_ids;
  static const std::array<protocol::TType, fields_size> fields_types;

 private:
  // The following fields describe internal storage metadata, and are private to
  // prevent user logic from accessing them, but they can be inspected by
  // debuggers.
  // -1 if the field has no isset.
  static const std::array<int, fields_size> isset_indexes;
};

template <> struct TStructDataStorage<::eugraph::thrift::ResultRowBatch> {
  static constexpr const std::size_t fields_size = 1;
  static const std::string_view name;
  static const std::array<std::string_view, fields_size> fields_names;
  static const std::array<int16_t, fields_size> fields_ids;
  static const std::array<protocol::TType, fields_size> fields_types;

 private:
  // The following fields describe internal storage metadata, and are private to
  // prevent user logic from accessing them, but they can be inspected by
  // debuggers.
  // -1 if the field has no isset.
  static const std::array<int, fields_size> isset_indexes;
};

template <> struct TStructDataStorage<::eugraph::thrift::GraphInfo> {
  static constexpr const std::size_t fields_size = 3;
  static const std::string_view name;
  static const std::array<std::string_view, fields_size> fields_names;
  static const std::array<int16_t, fields_size> fields_ids;
  static const std::array<protocol::TType, fields_size> fields_types;

 private:
  // The following fields describe internal storage metadata, and are private to
  // prevent user logic from accessing them, but they can be inspected by
  // debuggers.
  // -1 if the field has no isset.
  static const std::array<int, fields_size> isset_indexes;
};

}} // apache::thrift
