/**
 * Autogenerated by Thrift for /mnt/f/code/eugraph/proto/eugraph.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated @nocommit
 */
#pragma once

#include <thrift/lib/cpp2/visitation/visit_by_thrift_field_metadata.h>
#include "gen-cpp2/eugraph_metadata.h"

namespace apache {
namespace thrift {
namespace detail {

template <>
struct VisitByFieldId<::eugraph::thrift::PropertyDefThrift> {
  template <typename F, typename T>
  void operator()([[maybe_unused]] F&& f, int32_t fieldId, [[maybe_unused]] T&& t) const {
    switch (fieldId) {
    case 1:
      return f(0, static_cast<T&&>(t).name_ref());
    case 2:
      return f(1, static_cast<T&&>(t).type_ref());
    case 3:
      return f(2, static_cast<T&&>(t).is_required_ref());
    default:
      throwInvalidThriftId(fieldId, "::eugraph::thrift::PropertyDefThrift");
    }
  }
};

template <>
struct VisitByFieldId<::eugraph::thrift::PropertyValueThrift> {
  template <typename F, typename T>
  void operator()([[maybe_unused]] F&& f, int32_t fieldId, [[maybe_unused]] T&& t) const {
    switch (fieldId) {
    case 1:
      return f(0, static_cast<T&&>(t).bool_val_ref());
    case 2:
      return f(1, static_cast<T&&>(t).int_val_ref());
    case 3:
      return f(2, static_cast<T&&>(t).double_val_ref());
    case 4:
      return f(3, static_cast<T&&>(t).string_val_ref());
    case 5:
      return f(4, static_cast<T&&>(t).int_array_ref());
    case 6:
      return f(5, static_cast<T&&>(t).double_array_ref());
    case 7:
      return f(6, static_cast<T&&>(t).string_array_ref());
    default:
      throwInvalidThriftId(fieldId, "::eugraph::thrift::PropertyValueThrift");
    }
  }
};

template <>
struct VisitByFieldId<::eugraph::thrift::LabelInfo> {
  template <typename F, typename T>
  void operator()([[maybe_unused]] F&& f, int32_t fieldId, [[maybe_unused]] T&& t) const {
    switch (fieldId) {
    case 1:
      return f(0, static_cast<T&&>(t).id_ref());
    case 2:
      return f(1, static_cast<T&&>(t).name_ref());
    case 3:
      return f(2, static_cast<T&&>(t).properties_ref());
    default:
      throwInvalidThriftId(fieldId, "::eugraph::thrift::LabelInfo");
    }
  }
};

template <>
struct VisitByFieldId<::eugraph::thrift::EdgeLabelInfo> {
  template <typename F, typename T>
  void operator()([[maybe_unused]] F&& f, int32_t fieldId, [[maybe_unused]] T&& t) const {
    switch (fieldId) {
    case 1:
      return f(0, static_cast<T&&>(t).id_ref());
    case 2:
      return f(1, static_cast<T&&>(t).name_ref());
    case 3:
      return f(2, static_cast<T&&>(t).properties_ref());
    case 4:
      return f(3, static_cast<T&&>(t).directed_ref());
    default:
      throwInvalidThriftId(fieldId, "::eugraph::thrift::EdgeLabelInfo");
    }
  }
};

template <>
struct VisitByFieldId<::eugraph::thrift::ResultValue> {
  template <typename F, typename T>
  void operator()([[maybe_unused]] F&& f, int32_t fieldId, [[maybe_unused]] T&& t) const {
    switch (fieldId) {
    case 1:
      return f(0, static_cast<T&&>(t).bool_val_ref());
    case 2:
      return f(1, static_cast<T&&>(t).int_val_ref());
    case 3:
      return f(2, static_cast<T&&>(t).double_val_ref());
    case 4:
      return f(3, static_cast<T&&>(t).string_val_ref());
    case 5:
      return f(4, static_cast<T&&>(t).vertex_json_ref());
    case 6:
      return f(5, static_cast<T&&>(t).edge_json_ref());
    default:
      throwInvalidThriftId(fieldId, "::eugraph::thrift::ResultValue");
    }
  }
};

template <>
struct VisitByFieldId<::eugraph::thrift::ResultRow> {
  template <typename F, typename T>
  void operator()([[maybe_unused]] F&& f, int32_t fieldId, [[maybe_unused]] T&& t) const {
    switch (fieldId) {
    case 1:
      return f(0, static_cast<T&&>(t).values_ref());
    default:
      throwInvalidThriftId(fieldId, "::eugraph::thrift::ResultRow");
    }
  }
};

template <>
struct VisitByFieldId<::eugraph::thrift::QueryResult> {
  template <typename F, typename T>
  void operator()([[maybe_unused]] F&& f, int32_t fieldId, [[maybe_unused]] T&& t) const {
    switch (fieldId) {
    case 1:
      return f(0, static_cast<T&&>(t).columns_ref());
    case 2:
      return f(1, static_cast<T&&>(t).rows_ref());
    case 3:
      return f(2, static_cast<T&&>(t).rows_affected_ref());
    case 4:
      return f(3, static_cast<T&&>(t).error_ref());
    default:
      throwInvalidThriftId(fieldId, "::eugraph::thrift::QueryResult");
    }
  }
};
} // namespace detail
} // namespace thrift
} // namespace apache
