/**
 * Autogenerated by Thrift for /mnt/f/code/eugraph/proto/eugraph.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated @nocommit
 */

#include "gen-cpp2/eugraph_data.h"
#include "gen-cpp2/eugraph_constants.h"

#include <thrift/lib/cpp2/gen/module_data_cpp.h>

namespace apache::thrift {

THRIFT_DATA_MEMBER const std::string_view TStructDataStorage<::eugraph::thrift::PropertyDefThrift>::name = "PropertyDefThrift";
THRIFT_DATA_MEMBER const std::array<std::string_view, 3> TStructDataStorage<::eugraph::thrift::PropertyDefThrift>::fields_names = { {
  "name"sv,
  "type"sv,
  "is_required"sv,
}};
THRIFT_DATA_MEMBER const std::array<int16_t, 3> TStructDataStorage<::eugraph::thrift::PropertyDefThrift>::fields_ids = { {
  1,
  2,
  3,
}};
THRIFT_DATA_MEMBER const std::array<protocol::TType, 3> TStructDataStorage<::eugraph::thrift::PropertyDefThrift>::fields_types = { {
  TType::T_STRING,
  TType::T_I32,
  TType::T_BOOL,
}};
THRIFT_DATA_MEMBER const std::array<int, 3> TStructDataStorage<::eugraph::thrift::PropertyDefThrift>::isset_indexes = { {
  0,
  1,
  2,
}};

THRIFT_DATA_MEMBER const std::string_view TStructDataStorage<::eugraph::thrift::PropertyValueThrift>::name = "PropertyValueThrift";
THRIFT_DATA_MEMBER const std::array<std::string_view, 7> TStructDataStorage<::eugraph::thrift::PropertyValueThrift>::fields_names = { {
  "bool_val"sv,
  "int_val"sv,
  "double_val"sv,
  "string_val"sv,
  "int_array"sv,
  "double_array"sv,
  "string_array"sv,
}};
THRIFT_DATA_MEMBER const std::array<int16_t, 7> TStructDataStorage<::eugraph::thrift::PropertyValueThrift>::fields_ids = { {
  1,
  2,
  3,
  4,
  5,
  6,
  7,
}};
THRIFT_DATA_MEMBER const std::array<protocol::TType, 7> TStructDataStorage<::eugraph::thrift::PropertyValueThrift>::fields_types = { {
  TType::T_BOOL,
  TType::T_I64,
  TType::T_DOUBLE,
  TType::T_STRING,
  TType::T_LIST,
  TType::T_LIST,
  TType::T_LIST,
}};
THRIFT_DATA_MEMBER const std::array<int, 7> TStructDataStorage<::eugraph::thrift::PropertyValueThrift>::isset_indexes = { {
  0,
  1,
  2,
  3,
  4,
  5,
  6,
}};

THRIFT_DATA_MEMBER const std::string_view TStructDataStorage<::eugraph::thrift::LabelInfo>::name = "LabelInfo";
THRIFT_DATA_MEMBER const std::array<std::string_view, 3> TStructDataStorage<::eugraph::thrift::LabelInfo>::fields_names = { {
  "id"sv,
  "name"sv,
  "properties"sv,
}};
THRIFT_DATA_MEMBER const std::array<int16_t, 3> TStructDataStorage<::eugraph::thrift::LabelInfo>::fields_ids = { {
  1,
  2,
  3,
}};
THRIFT_DATA_MEMBER const std::array<protocol::TType, 3> TStructDataStorage<::eugraph::thrift::LabelInfo>::fields_types = { {
  TType::T_I16,
  TType::T_STRING,
  TType::T_LIST,
}};
THRIFT_DATA_MEMBER const std::array<int, 3> TStructDataStorage<::eugraph::thrift::LabelInfo>::isset_indexes = { {
  0,
  1,
  2,
}};

THRIFT_DATA_MEMBER const std::string_view TStructDataStorage<::eugraph::thrift::EdgeLabelInfo>::name = "EdgeLabelInfo";
THRIFT_DATA_MEMBER const std::array<std::string_view, 4> TStructDataStorage<::eugraph::thrift::EdgeLabelInfo>::fields_names = { {
  "id"sv,
  "name"sv,
  "properties"sv,
  "directed"sv,
}};
THRIFT_DATA_MEMBER const std::array<int16_t, 4> TStructDataStorage<::eugraph::thrift::EdgeLabelInfo>::fields_ids = { {
  1,
  2,
  3,
  4,
}};
THRIFT_DATA_MEMBER const std::array<protocol::TType, 4> TStructDataStorage<::eugraph::thrift::EdgeLabelInfo>::fields_types = { {
  TType::T_I16,
  TType::T_STRING,
  TType::T_LIST,
  TType::T_BOOL,
}};
THRIFT_DATA_MEMBER const std::array<int, 4> TStructDataStorage<::eugraph::thrift::EdgeLabelInfo>::isset_indexes = { {
  0,
  1,
  2,
  3,
}};

THRIFT_DATA_MEMBER const std::string_view TStructDataStorage<::eugraph::thrift::ResultValue>::name = "ResultValue";
THRIFT_DATA_MEMBER const std::array<std::string_view, 6> TStructDataStorage<::eugraph::thrift::ResultValue>::fields_names = { {
  "bool_val"sv,
  "int_val"sv,
  "double_val"sv,
  "string_val"sv,
  "vertex_json"sv,
  "edge_json"sv,
}};
THRIFT_DATA_MEMBER const std::array<int16_t, 6> TStructDataStorage<::eugraph::thrift::ResultValue>::fields_ids = { {
  1,
  2,
  3,
  4,
  5,
  6,
}};
THRIFT_DATA_MEMBER const std::array<protocol::TType, 6> TStructDataStorage<::eugraph::thrift::ResultValue>::fields_types = { {
  TType::T_BOOL,
  TType::T_I64,
  TType::T_DOUBLE,
  TType::T_STRING,
  TType::T_STRING,
  TType::T_STRING,
}};
THRIFT_DATA_MEMBER const std::array<int, 6> TStructDataStorage<::eugraph::thrift::ResultValue>::isset_indexes = { {
  0,
  1,
  2,
  3,
  4,
  5,
}};

THRIFT_DATA_MEMBER const std::string_view TStructDataStorage<::eugraph::thrift::ResultRow>::name = "ResultRow";
THRIFT_DATA_MEMBER const std::array<std::string_view, 1> TStructDataStorage<::eugraph::thrift::ResultRow>::fields_names = { {
  "values"sv,
}};
THRIFT_DATA_MEMBER const std::array<int16_t, 1> TStructDataStorage<::eugraph::thrift::ResultRow>::fields_ids = { {
  1,
}};
THRIFT_DATA_MEMBER const std::array<protocol::TType, 1> TStructDataStorage<::eugraph::thrift::ResultRow>::fields_types = { {
  TType::T_LIST,
}};
THRIFT_DATA_MEMBER const std::array<int, 1> TStructDataStorage<::eugraph::thrift::ResultRow>::isset_indexes = { {
  0,
}};

THRIFT_DATA_MEMBER const std::string_view TStructDataStorage<::eugraph::thrift::QueryResult>::name = "QueryResult";
THRIFT_DATA_MEMBER const std::array<std::string_view, 4> TStructDataStorage<::eugraph::thrift::QueryResult>::fields_names = { {
  "columns"sv,
  "rows"sv,
  "rows_affected"sv,
  "error"sv,
}};
THRIFT_DATA_MEMBER const std::array<int16_t, 4> TStructDataStorage<::eugraph::thrift::QueryResult>::fields_ids = { {
  1,
  2,
  3,
  4,
}};
THRIFT_DATA_MEMBER const std::array<protocol::TType, 4> TStructDataStorage<::eugraph::thrift::QueryResult>::fields_types = { {
  TType::T_LIST,
  TType::T_LIST,
  TType::T_I64,
  TType::T_STRING,
}};
THRIFT_DATA_MEMBER const std::array<int, 4> TStructDataStorage<::eugraph::thrift::QueryResult>::isset_indexes = { {
  0,
  1,
  2,
  3,
}};

namespace detail {

::folly::Range<const ::std::string_view*>(*TSchemaAssociation<::eugraph::thrift::PropertyDefThrift, false>::bundle)() =
    nullptr;

::folly::Range<const ::std::string_view*>(*TSchemaAssociation<::eugraph::thrift::PropertyValueThrift, false>::bundle)() =
    nullptr;

::folly::Range<const ::std::string_view*>(*TSchemaAssociation<::eugraph::thrift::LabelInfo, false>::bundle)() =
    nullptr;

::folly::Range<const ::std::string_view*>(*TSchemaAssociation<::eugraph::thrift::EdgeLabelInfo, false>::bundle)() =
    nullptr;

::folly::Range<const ::std::string_view*>(*TSchemaAssociation<::eugraph::thrift::ResultValue, false>::bundle)() =
    nullptr;

::folly::Range<const ::std::string_view*>(*TSchemaAssociation<::eugraph::thrift::ResultRow, false>::bundle)() =
    nullptr;

::folly::Range<const ::std::string_view*>(*TSchemaAssociation<::eugraph::thrift::QueryResult, false>::bundle)() =
    nullptr;

::folly::Range<const ::std::string_view*>(*TSchemaAssociation<::eugraph::thrift::PropertyType, true>::bundle)() =
    nullptr;

} // namespace detail
} // namespace apache::thrift
