/**
 * Autogenerated by Thrift for /mnt/f/code/eugraph/proto/eugraph.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated @nocommit
 */
#pragma once

#include <cstdint>

// BEGIN forward_declare
namespace eugraph::thrift {
class PropertyDefThrift;
class PropertyValueThrift;
class LabelInfo;
class EdgeLabelInfo;
class ResultValue;
class ResultRow;
class QueryResult;
} // namespace eugraph::thrift
// END forward_declare

// BEGIN forward_declare_enums
namespace eugraph::thrift {
enum class PropertyType;
} // namespace eugraph::thrift
// END forward_declare_enums
