/**
 * Autogenerated by Thrift for /home/dodo/code/fuck/eugraph/proto/eugraph.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated @nocommit
 */
#pragma once

#include "gen-cpp2/eugraph_metadata.h"
#include <thrift/lib/cpp2/visitation/for_each.h>

namespace apache {
namespace thrift {
namespace detail {

template <>
struct ForEachField<::eugraph::thrift::PropertyDefThrift> {
  template <typename F, typename... T>
  void operator()([[maybe_unused]] F&& f, [[maybe_unused]] T&&... t) const {
    f(0, static_cast<T&&>(t).name_ref()...);
    f(1, static_cast<T&&>(t).type_ref()...);
    f(2, static_cast<T&&>(t).is_required_ref()...);
  }
};

template <>
struct ForEachField<::eugraph::thrift::DateTimeValueThrift> {
  template <typename F, typename... T>
  void operator()([[maybe_unused]] F&& f, [[maybe_unused]] T&&... t) const {
    f(0, static_cast<T&&>(t).kind_ref()...);
    f(1, static_cast<T&&>(t).year_ref()...);
    f(2, static_cast<T&&>(t).month_ref()...);
    f(3, static_cast<T&&>(t).day_ref()...);
    f(4, static_cast<T&&>(t).hour_ref()...);
    f(5, static_cast<T&&>(t).minute_ref()...);
    f(6, static_cast<T&&>(t).second_ref()...);
    f(7, static_cast<T&&>(t).nanos_ref()...);
    f(8, static_cast<T&&>(t).tz_offset_min_ref()...);
    f(9, static_cast<T&&>(t).tz_name_ref()...);
  }
};

template <>
struct ForEachField<::eugraph::thrift::TimeValueThrift> {
  template <typename F, typename... T>
  void operator()([[maybe_unused]] F&& f, [[maybe_unused]] T&&... t) const {
    f(0, static_cast<T&&>(t).kind_ref()...);
    f(1, static_cast<T&&>(t).hour_ref()...);
    f(2, static_cast<T&&>(t).minute_ref()...);
    f(3, static_cast<T&&>(t).second_ref()...);
    f(4, static_cast<T&&>(t).nanos_ref()...);
    f(5, static_cast<T&&>(t).tz_offset_min_ref()...);
    f(6, static_cast<T&&>(t).tz_name_ref()...);
  }
};

template <>
struct ForEachField<::eugraph::thrift::DurationValueThrift> {
  template <typename F, typename... T>
  void operator()([[maybe_unused]] F&& f, [[maybe_unused]] T&&... t) const {
    f(0, static_cast<T&&>(t).months_ref()...);
    f(1, static_cast<T&&>(t).days_ref()...);
    f(2, static_cast<T&&>(t).seconds_ref()...);
    f(3, static_cast<T&&>(t).nanos_ref()...);
  }
};

template <>
struct ForEachField<::eugraph::thrift::PropertyValueThrift> {
  template <typename F, typename... T>
  void operator()([[maybe_unused]] F&& f, [[maybe_unused]] T&&... t) const {
    f(0, static_cast<T&&>(t).bool_val_ref()...);
    f(1, static_cast<T&&>(t).int_val_ref()...);
    f(2, static_cast<T&&>(t).double_val_ref()...);
    f(3, static_cast<T&&>(t).string_val_ref()...);
    f(4, static_cast<T&&>(t).int_array_ref()...);
    f(5, static_cast<T&&>(t).double_array_ref()...);
    f(6, static_cast<T&&>(t).string_array_ref()...);
    f(7, static_cast<T&&>(t).datetime_val_ref()...);
    f(8, static_cast<T&&>(t).time_val_ref()...);
    f(9, static_cast<T&&>(t).duration_val_ref()...);
    f(10, static_cast<T&&>(t).datetime_array_ref()...);
    f(11, static_cast<T&&>(t).time_array_ref()...);
    f(12, static_cast<T&&>(t).duration_array_ref()...);
  }
};

template <>
struct ForEachField<::eugraph::thrift::LabelInfo> {
  template <typename F, typename... T>
  void operator()([[maybe_unused]] F&& f, [[maybe_unused]] T&&... t) const {
    f(0, static_cast<T&&>(t).id_ref()...);
    f(1, static_cast<T&&>(t).name_ref()...);
    f(2, static_cast<T&&>(t).properties_ref()...);
  }
};

template <>
struct ForEachField<::eugraph::thrift::EdgeLabelInfo> {
  template <typename F, typename... T>
  void operator()([[maybe_unused]] F&& f, [[maybe_unused]] T&&... t) const {
    f(0, static_cast<T&&>(t).id_ref()...);
    f(1, static_cast<T&&>(t).name_ref()...);
    f(2, static_cast<T&&>(t).properties_ref()...);
    f(3, static_cast<T&&>(t).directed_ref()...);
  }
};

template <>
struct ForEachField<::eugraph::thrift::VertexRecord> {
  template <typename F, typename... T>
  void operator()([[maybe_unused]] F&& f, [[maybe_unused]] T&&... t) const {
    f(0, static_cast<T&&>(t).properties_ref()...);
  }
};

template <>
struct ForEachField<::eugraph::thrift::EdgeRecord> {
  template <typename F, typename... T>
  void operator()([[maybe_unused]] F&& f, [[maybe_unused]] T&&... t) const {
    f(0, static_cast<T&&>(t).src_vertex_id_ref()...);
    f(1, static_cast<T&&>(t).dst_vertex_id_ref()...);
    f(2, static_cast<T&&>(t).properties_ref()...);
  }
};

template <>
struct ForEachField<::eugraph::thrift::BatchInsertVerticesResult> {
  template <typename F, typename... T>
  void operator()([[maybe_unused]] F&& f, [[maybe_unused]] T&&... t) const {
    f(0, static_cast<T&&>(t).vertex_ids_ref()...);
    f(1, static_cast<T&&>(t).count_ref()...);
  }
};

template <>
struct ForEachField<::eugraph::thrift::ResultValue> {
  template <typename F, typename... T>
  void operator()([[maybe_unused]] F&& f, [[maybe_unused]] T&&... t) const {
    f(0, static_cast<T&&>(t).bool_val_ref()...);
    f(1, static_cast<T&&>(t).int_val_ref()...);
    f(2, static_cast<T&&>(t).double_val_ref()...);
    f(3, static_cast<T&&>(t).string_val_ref()...);
    f(4, static_cast<T&&>(t).vertex_json_ref()...);
    f(5, static_cast<T&&>(t).edge_json_ref()...);
    f(6, static_cast<T&&>(t).path_json_ref()...);
    f(7, static_cast<T&&>(t).list_json_ref()...);
    f(8, static_cast<T&&>(t).map_json_ref()...);
  }
};

template <>
struct ForEachField<::eugraph::thrift::ResultRow> {
  template <typename F, typename... T>
  void operator()([[maybe_unused]] F&& f, [[maybe_unused]] T&&... t) const {
    f(0, static_cast<T&&>(t).values_ref()...);
  }
};

template <>
struct ForEachField<::eugraph::thrift::QueryStreamMeta> {
  template <typename F, typename... T>
  void operator()([[maybe_unused]] F&& f, [[maybe_unused]] T&&... t) const {
    f(0, static_cast<T&&>(t).columns_ref()...);
  }
};

template <>
struct ForEachField<::eugraph::thrift::ResultRowBatch> {
  template <typename F, typename... T>
  void operator()([[maybe_unused]] F&& f, [[maybe_unused]] T&&... t) const {
    f(0, static_cast<T&&>(t).rows_ref()...);
  }
};

template <>
struct ForEachField<::eugraph::thrift::GraphInfo> {
  template <typename F, typename... T>
  void operator()([[maybe_unused]] F&& f, [[maybe_unused]] T&&... t) const {
    f(0, static_cast<T&&>(t).graph_id_ref()...);
    f(1, static_cast<T&&>(t).name_ref()...);
    f(2, static_cast<T&&>(t).created_at_ref()...);
  }
};
} // namespace detail
} // namespace thrift
} // namespace apache
