/**
 * Autogenerated by Thrift for proto/eugraph.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated @nocommit
 */

#include "gen-cpp2/EuGraphService.h"
#include "gen-cpp2/EuGraphService.tcc"
#include "gen-cpp2/eugraph_metadata.h"
#include <thrift/lib/cpp2/gen/service_cpp.h>

std::unique_ptr<apache::thrift::AsyncProcessor> apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>::getProcessor() {
  return std::make_unique<::eugraph::thrift::EuGraphServiceAsyncProcessor>(this);
}

apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>::CreateMethodMetadataResult apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>::createMethodMetadata() {
  return ::apache::thrift::detail::ap::createMethodMetadataMap<::eugraph::thrift::EuGraphServiceAsyncProcessor>(getServiceRequestInfoMap().value().get());
}


std::optional<std::reference_wrapper<apache::thrift::ServiceRequestInfoMap const>> apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>::getServiceRequestInfoMap() const {
  return __fbthrift_serviceInfoHolder.requestInfoMap();
}

::eugraph::thrift::EuGraphServiceServiceInfoHolder apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>::__fbthrift_serviceInfoHolder;


void apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>::createGraph(::eugraph::thrift::GraphInfo& /*_return*/, std::unique_ptr<::std::string> /*name*/) {
  apache::thrift::detail::si::throw_app_exn_unimplemented("createGraph");
}

void apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>::sync_createGraph(::eugraph::thrift::GraphInfo& _return, std::unique_ptr<::std::string> p_name) {
  return createGraph(_return, std::move(p_name));
}

folly::SemiFuture<std::unique_ptr<::eugraph::thrift::GraphInfo>> apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>::semifuture_createGraph(std::unique_ptr<::std::string> p_name) {
  auto expected{apache::thrift::detail::si::InvocationType::SemiFuture};
  __fbthrift_invocation_createGraph.compare_exchange_strong(expected, apache::thrift::detail::si::InvocationType::Sync, std::memory_order_relaxed);
  auto ret = std::make_unique<::eugraph::thrift::GraphInfo>();
  sync_createGraph(*ret, std::move(p_name));
  return folly::makeSemiFuture(std::move(ret));
}

folly::Future<std::unique_ptr<::eugraph::thrift::GraphInfo>> apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>::future_createGraph(std::unique_ptr<::std::string> p_name) {
  auto expected{apache::thrift::detail::si::InvocationType::Future};
  __fbthrift_invocation_createGraph.compare_exchange_strong(expected, apache::thrift::detail::si::InvocationType::SemiFuture, std::memory_order_relaxed);
  return apache::thrift::detail::si::future(semifuture_createGraph(std::move(p_name)), getInternalKeepAlive());
}

#if FOLLY_HAS_COROUTINES
folly::coro::Task<std::unique_ptr<::eugraph::thrift::GraphInfo>> apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>::co_createGraph(std::unique_ptr<::std::string> p_name) {
  auto expected{apache::thrift::detail::si::InvocationType::Coro};
  __fbthrift_invocation_createGraph.compare_exchange_strong(expected, apache::thrift::detail::si::InvocationType::Future, std::memory_order_relaxed);
  folly::throw_exception(apache::thrift::detail::si::UnimplementedCoroMethod::withCapturedArgs<std::unique_ptr<::std::string> /*name*/>(std::move(p_name)));
}

folly::coro::Task<std::unique_ptr<::eugraph::thrift::GraphInfo>> apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>::co_createGraph(apache::thrift::RequestParams /* params */, std::unique_ptr<::std::string> p_name) {
  auto expected{apache::thrift::detail::si::InvocationType::CoroParam};
  __fbthrift_invocation_createGraph.compare_exchange_strong(expected, apache::thrift::detail::si::InvocationType::Coro, std::memory_order_relaxed);
  return co_createGraph(std::move(p_name));
}
#endif // FOLLY_HAS_COROUTINES

void apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>::async_tm_createGraph(apache::thrift::HandlerCallbackPtr<std::unique_ptr<::eugraph::thrift::GraphInfo>> callback, std::unique_ptr<::std::string> p_name) {
  // It's possible the coroutine versions will delegate to a future-based
  // version. If that happens, we need the RequestParams arguments to be
  // available to the future through the thread-local backchannel, so we create
  // a RAII object that sets up RequestParams and clears them on destruction.
  apache::thrift::detail::si::AsyncTmPrep asyncTmPrep(this, callback.get());
#if FOLLY_HAS_COROUTINES
determineInvocationType:
#endif // FOLLY_HAS_COROUTINES
  auto invocationType = __fbthrift_invocation_createGraph.load(std::memory_order_relaxed);
  try {
    switch (invocationType) {
      case apache::thrift::detail::si::InvocationType::AsyncTm:
      {
#if FOLLY_HAS_COROUTINES
        __fbthrift_invocation_createGraph.compare_exchange_strong(invocationType, apache::thrift::detail::si::InvocationType::CoroParam, std::memory_order_relaxed);
        apache::thrift::RequestParams params{callback->getRequestContext(),
          callback->getThreadManager_deprecated(), callback->getEventBase(), callback->getHandlerExecutor()};
        auto task = co_createGraph(params, std::move(p_name));
        apache::thrift::detail::si::async_tm_coro(std::move(callback), std::move(task));
        return;
#else // FOLLY_HAS_COROUTINES
        __fbthrift_invocation_createGraph.compare_exchange_strong(invocationType, apache::thrift::detail::si::InvocationType::Future, std::memory_order_relaxed);
        [[fallthrough]];
#endif // FOLLY_HAS_COROUTINES
      }
      case apache::thrift::detail::si::InvocationType::Future:
      {
        auto fut = future_createGraph(std::move(p_name));
        apache::thrift::detail::si::async_tm_future(std::move(callback), std::move(fut));
        return;
      }
      case apache::thrift::detail::si::InvocationType::SemiFuture:
      {
        auto fut = semifuture_createGraph(std::move(p_name));
        apache::thrift::detail::si::async_tm_semifuture(std::move(callback), std::move(fut));
        return;
      }
#if FOLLY_HAS_COROUTINES
      case apache::thrift::detail::si::InvocationType::CoroParam:
      {
        apache::thrift::RequestParams params{callback->getRequestContext(),
          callback->getThreadManager_deprecated(), callback->getEventBase(), callback->getHandlerExecutor()};
        auto task = co_createGraph(params, std::move(p_name));
        apache::thrift::detail::si::async_tm_coro(std::move(callback), std::move(task));
        return;
      }
      case apache::thrift::detail::si::InvocationType::Coro:
      {
        auto task = co_createGraph(std::move(p_name));
        apache::thrift::detail::si::async_tm_coro(std::move(callback), std::move(task));
        return;
      }
#endif // FOLLY_HAS_COROUTINES
      case apache::thrift::detail::si::InvocationType::Sync:
      {
        ::eugraph::thrift::GraphInfo _return;
        sync_createGraph(_return, std::move(p_name));
        callback->result(std::move(_return));
        return;
      }
      default:
      {
        folly::assume_unreachable();
      }
    }
#if FOLLY_HAS_COROUTINES
  } catch (apache::thrift::detail::si::UnimplementedCoroMethod& ex) {
    std::tie(p_name) = std::move(ex).restoreArgs<std::unique_ptr<::std::string> /*name*/>();
    goto determineInvocationType;
#endif // FOLLY_HAS_COROUTINES
  } catch (...) {
    callback->exception(std::current_exception());
  }
}

bool apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>::dropGraph(std::unique_ptr<::std::string> /*name*/) {
  apache::thrift::detail::si::throw_app_exn_unimplemented("dropGraph");
}

bool apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>::sync_dropGraph(std::unique_ptr<::std::string> p_name) {
  return dropGraph(std::move(p_name));
}

folly::SemiFuture<bool> apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>::semifuture_dropGraph(std::unique_ptr<::std::string> p_name) {
  auto expected{apache::thrift::detail::si::InvocationType::SemiFuture};
  __fbthrift_invocation_dropGraph.compare_exchange_strong(expected, apache::thrift::detail::si::InvocationType::Sync, std::memory_order_relaxed);
  return sync_dropGraph(std::move(p_name));
}

folly::Future<bool> apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>::future_dropGraph(std::unique_ptr<::std::string> p_name) {
  auto expected{apache::thrift::detail::si::InvocationType::Future};
  __fbthrift_invocation_dropGraph.compare_exchange_strong(expected, apache::thrift::detail::si::InvocationType::SemiFuture, std::memory_order_relaxed);
  return apache::thrift::detail::si::future(semifuture_dropGraph(std::move(p_name)), getInternalKeepAlive());
}

#if FOLLY_HAS_COROUTINES
folly::coro::Task<bool> apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>::co_dropGraph(std::unique_ptr<::std::string> p_name) {
  auto expected{apache::thrift::detail::si::InvocationType::Coro};
  __fbthrift_invocation_dropGraph.compare_exchange_strong(expected, apache::thrift::detail::si::InvocationType::Future, std::memory_order_relaxed);
  folly::throw_exception(apache::thrift::detail::si::UnimplementedCoroMethod::withCapturedArgs<std::unique_ptr<::std::string> /*name*/>(std::move(p_name)));
}

folly::coro::Task<bool> apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>::co_dropGraph(apache::thrift::RequestParams /* params */, std::unique_ptr<::std::string> p_name) {
  auto expected{apache::thrift::detail::si::InvocationType::CoroParam};
  __fbthrift_invocation_dropGraph.compare_exchange_strong(expected, apache::thrift::detail::si::InvocationType::Coro, std::memory_order_relaxed);
  return co_dropGraph(std::move(p_name));
}
#endif // FOLLY_HAS_COROUTINES

void apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>::async_tm_dropGraph(apache::thrift::HandlerCallbackPtr<bool> callback, std::unique_ptr<::std::string> p_name) {
  // It's possible the coroutine versions will delegate to a future-based
  // version. If that happens, we need the RequestParams arguments to be
  // available to the future through the thread-local backchannel, so we create
  // a RAII object that sets up RequestParams and clears them on destruction.
  apache::thrift::detail::si::AsyncTmPrep asyncTmPrep(this, callback.get());
#if FOLLY_HAS_COROUTINES
determineInvocationType:
#endif // FOLLY_HAS_COROUTINES
  auto invocationType = __fbthrift_invocation_dropGraph.load(std::memory_order_relaxed);
  try {
    switch (invocationType) {
      case apache::thrift::detail::si::InvocationType::AsyncTm:
      {
#if FOLLY_HAS_COROUTINES
        __fbthrift_invocation_dropGraph.compare_exchange_strong(invocationType, apache::thrift::detail::si::InvocationType::CoroParam, std::memory_order_relaxed);
        apache::thrift::RequestParams params{callback->getRequestContext(),
          callback->getThreadManager_deprecated(), callback->getEventBase(), callback->getHandlerExecutor()};
        auto task = co_dropGraph(params, std::move(p_name));
        apache::thrift::detail::si::async_tm_coro(std::move(callback), std::move(task));
        return;
#else // FOLLY_HAS_COROUTINES
        __fbthrift_invocation_dropGraph.compare_exchange_strong(invocationType, apache::thrift::detail::si::InvocationType::Future, std::memory_order_relaxed);
        [[fallthrough]];
#endif // FOLLY_HAS_COROUTINES
      }
      case apache::thrift::detail::si::InvocationType::Future:
      {
        auto fut = future_dropGraph(std::move(p_name));
        apache::thrift::detail::si::async_tm_future(std::move(callback), std::move(fut));
        return;
      }
      case apache::thrift::detail::si::InvocationType::SemiFuture:
      {
        auto fut = semifuture_dropGraph(std::move(p_name));
        apache::thrift::detail::si::async_tm_semifuture(std::move(callback), std::move(fut));
        return;
      }
#if FOLLY_HAS_COROUTINES
      case apache::thrift::detail::si::InvocationType::CoroParam:
      {
        apache::thrift::RequestParams params{callback->getRequestContext(),
          callback->getThreadManager_deprecated(), callback->getEventBase(), callback->getHandlerExecutor()};
        auto task = co_dropGraph(params, std::move(p_name));
        apache::thrift::detail::si::async_tm_coro(std::move(callback), std::move(task));
        return;
      }
      case apache::thrift::detail::si::InvocationType::Coro:
      {
        auto task = co_dropGraph(std::move(p_name));
        apache::thrift::detail::si::async_tm_coro(std::move(callback), std::move(task));
        return;
      }
#endif // FOLLY_HAS_COROUTINES
      case apache::thrift::detail::si::InvocationType::Sync:
      {
        callback->result(sync_dropGraph(std::move(p_name)));
        return;
      }
      default:
      {
        folly::assume_unreachable();
      }
    }
#if FOLLY_HAS_COROUTINES
  } catch (apache::thrift::detail::si::UnimplementedCoroMethod& ex) {
    std::tie(p_name) = std::move(ex).restoreArgs<std::unique_ptr<::std::string> /*name*/>();
    goto determineInvocationType;
#endif // FOLLY_HAS_COROUTINES
  } catch (...) {
    callback->exception(std::current_exception());
  }
}

void apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>::listGraphs(::std::vector<::eugraph::thrift::GraphInfo>& /*_return*/) {
  apache::thrift::detail::si::throw_app_exn_unimplemented("listGraphs");
}

void apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>::sync_listGraphs(::std::vector<::eugraph::thrift::GraphInfo>& _return) {
  return listGraphs(_return);
}

folly::SemiFuture<std::unique_ptr<::std::vector<::eugraph::thrift::GraphInfo>>> apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>::semifuture_listGraphs() {
  auto expected{apache::thrift::detail::si::InvocationType::SemiFuture};
  __fbthrift_invocation_listGraphs.compare_exchange_strong(expected, apache::thrift::detail::si::InvocationType::Sync, std::memory_order_relaxed);
  auto ret = std::make_unique<::std::vector<::eugraph::thrift::GraphInfo>>();
  sync_listGraphs(*ret);
  return folly::makeSemiFuture(std::move(ret));
}

folly::Future<std::unique_ptr<::std::vector<::eugraph::thrift::GraphInfo>>> apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>::future_listGraphs() {
  auto expected{apache::thrift::detail::si::InvocationType::Future};
  __fbthrift_invocation_listGraphs.compare_exchange_strong(expected, apache::thrift::detail::si::InvocationType::SemiFuture, std::memory_order_relaxed);
  return apache::thrift::detail::si::future(semifuture_listGraphs(), getInternalKeepAlive());
}

#if FOLLY_HAS_COROUTINES
folly::coro::Task<std::unique_ptr<::std::vector<::eugraph::thrift::GraphInfo>>> apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>::co_listGraphs() {
  auto expected{apache::thrift::detail::si::InvocationType::Coro};
  __fbthrift_invocation_listGraphs.compare_exchange_strong(expected, apache::thrift::detail::si::InvocationType::Future, std::memory_order_relaxed);
  folly::throw_exception(apache::thrift::detail::si::UnimplementedCoroMethod::withCapturedArgs<>());
}

folly::coro::Task<std::unique_ptr<::std::vector<::eugraph::thrift::GraphInfo>>> apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>::co_listGraphs(apache::thrift::RequestParams /* params */) {
  auto expected{apache::thrift::detail::si::InvocationType::CoroParam};
  __fbthrift_invocation_listGraphs.compare_exchange_strong(expected, apache::thrift::detail::si::InvocationType::Coro, std::memory_order_relaxed);
  return co_listGraphs();
}
#endif // FOLLY_HAS_COROUTINES

void apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>::async_tm_listGraphs(apache::thrift::HandlerCallbackPtr<std::unique_ptr<::std::vector<::eugraph::thrift::GraphInfo>>> callback) {
  // It's possible the coroutine versions will delegate to a future-based
  // version. If that happens, we need the RequestParams arguments to be
  // available to the future through the thread-local backchannel, so we create
  // a RAII object that sets up RequestParams and clears them on destruction.
  apache::thrift::detail::si::AsyncTmPrep asyncTmPrep(this, callback.get());
#if FOLLY_HAS_COROUTINES
determineInvocationType:
#endif // FOLLY_HAS_COROUTINES
  auto invocationType = __fbthrift_invocation_listGraphs.load(std::memory_order_relaxed);
  try {
    switch (invocationType) {
      case apache::thrift::detail::si::InvocationType::AsyncTm:
      {
#if FOLLY_HAS_COROUTINES
        __fbthrift_invocation_listGraphs.compare_exchange_strong(invocationType, apache::thrift::detail::si::InvocationType::CoroParam, std::memory_order_relaxed);
        apache::thrift::RequestParams params{callback->getRequestContext(),
          callback->getThreadManager_deprecated(), callback->getEventBase(), callback->getHandlerExecutor()};
        auto task = co_listGraphs(params);
        apache::thrift::detail::si::async_tm_coro(std::move(callback), std::move(task));
        return;
#else // FOLLY_HAS_COROUTINES
        __fbthrift_invocation_listGraphs.compare_exchange_strong(invocationType, apache::thrift::detail::si::InvocationType::Future, std::memory_order_relaxed);
        [[fallthrough]];
#endif // FOLLY_HAS_COROUTINES
      }
      case apache::thrift::detail::si::InvocationType::Future:
      {
        auto fut = future_listGraphs();
        apache::thrift::detail::si::async_tm_future(std::move(callback), std::move(fut));
        return;
      }
      case apache::thrift::detail::si::InvocationType::SemiFuture:
      {
        auto fut = semifuture_listGraphs();
        apache::thrift::detail::si::async_tm_semifuture(std::move(callback), std::move(fut));
        return;
      }
#if FOLLY_HAS_COROUTINES
      case apache::thrift::detail::si::InvocationType::CoroParam:
      {
        apache::thrift::RequestParams params{callback->getRequestContext(),
          callback->getThreadManager_deprecated(), callback->getEventBase(), callback->getHandlerExecutor()};
        auto task = co_listGraphs(params);
        apache::thrift::detail::si::async_tm_coro(std::move(callback), std::move(task));
        return;
      }
      case apache::thrift::detail::si::InvocationType::Coro:
      {
        auto task = co_listGraphs();
        apache::thrift::detail::si::async_tm_coro(std::move(callback), std::move(task));
        return;
      }
#endif // FOLLY_HAS_COROUTINES
      case apache::thrift::detail::si::InvocationType::Sync:
      {
        ::std::vector<::eugraph::thrift::GraphInfo> _return;
        sync_listGraphs(_return);
        callback->result(std::move(_return));
        return;
      }
      default:
      {
        folly::assume_unreachable();
      }
    }
#if FOLLY_HAS_COROUTINES
  } catch (apache::thrift::detail::si::UnimplementedCoroMethod& ex) {
    std::tie() = std::move(ex).restoreArgs<>();
    goto determineInvocationType;
#endif // FOLLY_HAS_COROUTINES
  } catch (...) {
    callback->exception(std::current_exception());
  }
}

void apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>::createLabel(::eugraph::thrift::LabelInfo& /*_return*/, std::unique_ptr<::std::string> /*name*/, std::unique_ptr<::std::vector<::eugraph::thrift::PropertyDefThrift>> /*properties*/, std::unique_ptr<::std::string> /*graph_name*/) {
  apache::thrift::detail::si::throw_app_exn_unimplemented("createLabel");
}

void apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>::sync_createLabel(::eugraph::thrift::LabelInfo& _return, std::unique_ptr<::std::string> p_name, std::unique_ptr<::std::vector<::eugraph::thrift::PropertyDefThrift>> p_properties, std::unique_ptr<::std::string> p_graph_name) {
  return createLabel(_return, std::move(p_name), std::move(p_properties), std::move(p_graph_name));
}

folly::SemiFuture<std::unique_ptr<::eugraph::thrift::LabelInfo>> apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>::semifuture_createLabel(std::unique_ptr<::std::string> p_name, std::unique_ptr<::std::vector<::eugraph::thrift::PropertyDefThrift>> p_properties, std::unique_ptr<::std::string> p_graph_name) {
  auto expected{apache::thrift::detail::si::InvocationType::SemiFuture};
  __fbthrift_invocation_createLabel.compare_exchange_strong(expected, apache::thrift::detail::si::InvocationType::Sync, std::memory_order_relaxed);
  auto ret = std::make_unique<::eugraph::thrift::LabelInfo>();
  sync_createLabel(*ret, std::move(p_name), std::move(p_properties), std::move(p_graph_name));
  return folly::makeSemiFuture(std::move(ret));
}

folly::Future<std::unique_ptr<::eugraph::thrift::LabelInfo>> apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>::future_createLabel(std::unique_ptr<::std::string> p_name, std::unique_ptr<::std::vector<::eugraph::thrift::PropertyDefThrift>> p_properties, std::unique_ptr<::std::string> p_graph_name) {
  auto expected{apache::thrift::detail::si::InvocationType::Future};
  __fbthrift_invocation_createLabel.compare_exchange_strong(expected, apache::thrift::detail::si::InvocationType::SemiFuture, std::memory_order_relaxed);
  return apache::thrift::detail::si::future(semifuture_createLabel(std::move(p_name), std::move(p_properties), std::move(p_graph_name)), getInternalKeepAlive());
}

#if FOLLY_HAS_COROUTINES
folly::coro::Task<std::unique_ptr<::eugraph::thrift::LabelInfo>> apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>::co_createLabel(std::unique_ptr<::std::string> p_name, std::unique_ptr<::std::vector<::eugraph::thrift::PropertyDefThrift>> p_properties, std::unique_ptr<::std::string> p_graph_name) {
  auto expected{apache::thrift::detail::si::InvocationType::Coro};
  __fbthrift_invocation_createLabel.compare_exchange_strong(expected, apache::thrift::detail::si::InvocationType::Future, std::memory_order_relaxed);
  folly::throw_exception(apache::thrift::detail::si::UnimplementedCoroMethod::withCapturedArgs<std::unique_ptr<::std::string> /*name*/, std::unique_ptr<::std::vector<::eugraph::thrift::PropertyDefThrift>> /*properties*/, std::unique_ptr<::std::string> /*graph_name*/>(std::move(p_name), std::move(p_properties), std::move(p_graph_name)));
}

folly::coro::Task<std::unique_ptr<::eugraph::thrift::LabelInfo>> apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>::co_createLabel(apache::thrift::RequestParams /* params */, std::unique_ptr<::std::string> p_name, std::unique_ptr<::std::vector<::eugraph::thrift::PropertyDefThrift>> p_properties, std::unique_ptr<::std::string> p_graph_name) {
  auto expected{apache::thrift::detail::si::InvocationType::CoroParam};
  __fbthrift_invocation_createLabel.compare_exchange_strong(expected, apache::thrift::detail::si::InvocationType::Coro, std::memory_order_relaxed);
  return co_createLabel(std::move(p_name), std::move(p_properties), std::move(p_graph_name));
}
#endif // FOLLY_HAS_COROUTINES

void apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>::async_tm_createLabel(apache::thrift::HandlerCallbackPtr<std::unique_ptr<::eugraph::thrift::LabelInfo>> callback, std::unique_ptr<::std::string> p_name, std::unique_ptr<::std::vector<::eugraph::thrift::PropertyDefThrift>> p_properties, std::unique_ptr<::std::string> p_graph_name) {
  // It's possible the coroutine versions will delegate to a future-based
  // version. If that happens, we need the RequestParams arguments to be
  // available to the future through the thread-local backchannel, so we create
  // a RAII object that sets up RequestParams and clears them on destruction.
  apache::thrift::detail::si::AsyncTmPrep asyncTmPrep(this, callback.get());
#if FOLLY_HAS_COROUTINES
determineInvocationType:
#endif // FOLLY_HAS_COROUTINES
  auto invocationType = __fbthrift_invocation_createLabel.load(std::memory_order_relaxed);
  try {
    switch (invocationType) {
      case apache::thrift::detail::si::InvocationType::AsyncTm:
      {
#if FOLLY_HAS_COROUTINES
        __fbthrift_invocation_createLabel.compare_exchange_strong(invocationType, apache::thrift::detail::si::InvocationType::CoroParam, std::memory_order_relaxed);
        apache::thrift::RequestParams params{callback->getRequestContext(),
          callback->getThreadManager_deprecated(), callback->getEventBase(), callback->getHandlerExecutor()};
        auto task = co_createLabel(params, std::move(p_name), std::move(p_properties), std::move(p_graph_name));
        apache::thrift::detail::si::async_tm_coro(std::move(callback), std::move(task));
        return;
#else // FOLLY_HAS_COROUTINES
        __fbthrift_invocation_createLabel.compare_exchange_strong(invocationType, apache::thrift::detail::si::InvocationType::Future, std::memory_order_relaxed);
        [[fallthrough]];
#endif // FOLLY_HAS_COROUTINES
      }
      case apache::thrift::detail::si::InvocationType::Future:
      {
        auto fut = future_createLabel(std::move(p_name), std::move(p_properties), std::move(p_graph_name));
        apache::thrift::detail::si::async_tm_future(std::move(callback), std::move(fut));
        return;
      }
      case apache::thrift::detail::si::InvocationType::SemiFuture:
      {
        auto fut = semifuture_createLabel(std::move(p_name), std::move(p_properties), std::move(p_graph_name));
        apache::thrift::detail::si::async_tm_semifuture(std::move(callback), std::move(fut));
        return;
      }
#if FOLLY_HAS_COROUTINES
      case apache::thrift::detail::si::InvocationType::CoroParam:
      {
        apache::thrift::RequestParams params{callback->getRequestContext(),
          callback->getThreadManager_deprecated(), callback->getEventBase(), callback->getHandlerExecutor()};
        auto task = co_createLabel(params, std::move(p_name), std::move(p_properties), std::move(p_graph_name));
        apache::thrift::detail::si::async_tm_coro(std::move(callback), std::move(task));
        return;
      }
      case apache::thrift::detail::si::InvocationType::Coro:
      {
        auto task = co_createLabel(std::move(p_name), std::move(p_properties), std::move(p_graph_name));
        apache::thrift::detail::si::async_tm_coro(std::move(callback), std::move(task));
        return;
      }
#endif // FOLLY_HAS_COROUTINES
      case apache::thrift::detail::si::InvocationType::Sync:
      {
        ::eugraph::thrift::LabelInfo _return;
        sync_createLabel(_return, std::move(p_name), std::move(p_properties), std::move(p_graph_name));
        callback->result(std::move(_return));
        return;
      }
      default:
      {
        folly::assume_unreachable();
      }
    }
#if FOLLY_HAS_COROUTINES
  } catch (apache::thrift::detail::si::UnimplementedCoroMethod& ex) {
    std::tie(p_name, p_properties, p_graph_name) = std::move(ex).restoreArgs<std::unique_ptr<::std::string> /*name*/, std::unique_ptr<::std::vector<::eugraph::thrift::PropertyDefThrift>> /*properties*/, std::unique_ptr<::std::string> /*graph_name*/>();
    goto determineInvocationType;
#endif // FOLLY_HAS_COROUTINES
  } catch (...) {
    callback->exception(std::current_exception());
  }
}

void apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>::listLabels(::std::vector<::eugraph::thrift::LabelInfo>& /*_return*/, std::unique_ptr<::std::string> /*graph_name*/) {
  apache::thrift::detail::si::throw_app_exn_unimplemented("listLabels");
}

void apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>::sync_listLabels(::std::vector<::eugraph::thrift::LabelInfo>& _return, std::unique_ptr<::std::string> p_graph_name) {
  return listLabels(_return, std::move(p_graph_name));
}

folly::SemiFuture<std::unique_ptr<::std::vector<::eugraph::thrift::LabelInfo>>> apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>::semifuture_listLabels(std::unique_ptr<::std::string> p_graph_name) {
  auto expected{apache::thrift::detail::si::InvocationType::SemiFuture};
  __fbthrift_invocation_listLabels.compare_exchange_strong(expected, apache::thrift::detail::si::InvocationType::Sync, std::memory_order_relaxed);
  auto ret = std::make_unique<::std::vector<::eugraph::thrift::LabelInfo>>();
  sync_listLabels(*ret, std::move(p_graph_name));
  return folly::makeSemiFuture(std::move(ret));
}

folly::Future<std::unique_ptr<::std::vector<::eugraph::thrift::LabelInfo>>> apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>::future_listLabels(std::unique_ptr<::std::string> p_graph_name) {
  auto expected{apache::thrift::detail::si::InvocationType::Future};
  __fbthrift_invocation_listLabels.compare_exchange_strong(expected, apache::thrift::detail::si::InvocationType::SemiFuture, std::memory_order_relaxed);
  return apache::thrift::detail::si::future(semifuture_listLabels(std::move(p_graph_name)), getInternalKeepAlive());
}

#if FOLLY_HAS_COROUTINES
folly::coro::Task<std::unique_ptr<::std::vector<::eugraph::thrift::LabelInfo>>> apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>::co_listLabels(std::unique_ptr<::std::string> p_graph_name) {
  auto expected{apache::thrift::detail::si::InvocationType::Coro};
  __fbthrift_invocation_listLabels.compare_exchange_strong(expected, apache::thrift::detail::si::InvocationType::Future, std::memory_order_relaxed);
  folly::throw_exception(apache::thrift::detail::si::UnimplementedCoroMethod::withCapturedArgs<std::unique_ptr<::std::string> /*graph_name*/>(std::move(p_graph_name)));
}

folly::coro::Task<std::unique_ptr<::std::vector<::eugraph::thrift::LabelInfo>>> apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>::co_listLabels(apache::thrift::RequestParams /* params */, std::unique_ptr<::std::string> p_graph_name) {
  auto expected{apache::thrift::detail::si::InvocationType::CoroParam};
  __fbthrift_invocation_listLabels.compare_exchange_strong(expected, apache::thrift::detail::si::InvocationType::Coro, std::memory_order_relaxed);
  return co_listLabels(std::move(p_graph_name));
}
#endif // FOLLY_HAS_COROUTINES

void apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>::async_tm_listLabels(apache::thrift::HandlerCallbackPtr<std::unique_ptr<::std::vector<::eugraph::thrift::LabelInfo>>> callback, std::unique_ptr<::std::string> p_graph_name) {
  // It's possible the coroutine versions will delegate to a future-based
  // version. If that happens, we need the RequestParams arguments to be
  // available to the future through the thread-local backchannel, so we create
  // a RAII object that sets up RequestParams and clears them on destruction.
  apache::thrift::detail::si::AsyncTmPrep asyncTmPrep(this, callback.get());
#if FOLLY_HAS_COROUTINES
determineInvocationType:
#endif // FOLLY_HAS_COROUTINES
  auto invocationType = __fbthrift_invocation_listLabels.load(std::memory_order_relaxed);
  try {
    switch (invocationType) {
      case apache::thrift::detail::si::InvocationType::AsyncTm:
      {
#if FOLLY_HAS_COROUTINES
        __fbthrift_invocation_listLabels.compare_exchange_strong(invocationType, apache::thrift::detail::si::InvocationType::CoroParam, std::memory_order_relaxed);
        apache::thrift::RequestParams params{callback->getRequestContext(),
          callback->getThreadManager_deprecated(), callback->getEventBase(), callback->getHandlerExecutor()};
        auto task = co_listLabels(params, std::move(p_graph_name));
        apache::thrift::detail::si::async_tm_coro(std::move(callback), std::move(task));
        return;
#else // FOLLY_HAS_COROUTINES
        __fbthrift_invocation_listLabels.compare_exchange_strong(invocationType, apache::thrift::detail::si::InvocationType::Future, std::memory_order_relaxed);
        [[fallthrough]];
#endif // FOLLY_HAS_COROUTINES
      }
      case apache::thrift::detail::si::InvocationType::Future:
      {
        auto fut = future_listLabels(std::move(p_graph_name));
        apache::thrift::detail::si::async_tm_future(std::move(callback), std::move(fut));
        return;
      }
      case apache::thrift::detail::si::InvocationType::SemiFuture:
      {
        auto fut = semifuture_listLabels(std::move(p_graph_name));
        apache::thrift::detail::si::async_tm_semifuture(std::move(callback), std::move(fut));
        return;
      }
#if FOLLY_HAS_COROUTINES
      case apache::thrift::detail::si::InvocationType::CoroParam:
      {
        apache::thrift::RequestParams params{callback->getRequestContext(),
          callback->getThreadManager_deprecated(), callback->getEventBase(), callback->getHandlerExecutor()};
        auto task = co_listLabels(params, std::move(p_graph_name));
        apache::thrift::detail::si::async_tm_coro(std::move(callback), std::move(task));
        return;
      }
      case apache::thrift::detail::si::InvocationType::Coro:
      {
        auto task = co_listLabels(std::move(p_graph_name));
        apache::thrift::detail::si::async_tm_coro(std::move(callback), std::move(task));
        return;
      }
#endif // FOLLY_HAS_COROUTINES
      case apache::thrift::detail::si::InvocationType::Sync:
      {
        ::std::vector<::eugraph::thrift::LabelInfo> _return;
        sync_listLabels(_return, std::move(p_graph_name));
        callback->result(std::move(_return));
        return;
      }
      default:
      {
        folly::assume_unreachable();
      }
    }
#if FOLLY_HAS_COROUTINES
  } catch (apache::thrift::detail::si::UnimplementedCoroMethod& ex) {
    std::tie(p_graph_name) = std::move(ex).restoreArgs<std::unique_ptr<::std::string> /*graph_name*/>();
    goto determineInvocationType;
#endif // FOLLY_HAS_COROUTINES
  } catch (...) {
    callback->exception(std::current_exception());
  }
}

void apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>::createEdgeLabel(::eugraph::thrift::EdgeLabelInfo& /*_return*/, std::unique_ptr<::std::string> /*name*/, std::unique_ptr<::std::vector<::eugraph::thrift::PropertyDefThrift>> /*properties*/, std::unique_ptr<::std::string> /*graph_name*/) {
  apache::thrift::detail::si::throw_app_exn_unimplemented("createEdgeLabel");
}

void apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>::sync_createEdgeLabel(::eugraph::thrift::EdgeLabelInfo& _return, std::unique_ptr<::std::string> p_name, std::unique_ptr<::std::vector<::eugraph::thrift::PropertyDefThrift>> p_properties, std::unique_ptr<::std::string> p_graph_name) {
  return createEdgeLabel(_return, std::move(p_name), std::move(p_properties), std::move(p_graph_name));
}

folly::SemiFuture<std::unique_ptr<::eugraph::thrift::EdgeLabelInfo>> apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>::semifuture_createEdgeLabel(std::unique_ptr<::std::string> p_name, std::unique_ptr<::std::vector<::eugraph::thrift::PropertyDefThrift>> p_properties, std::unique_ptr<::std::string> p_graph_name) {
  auto expected{apache::thrift::detail::si::InvocationType::SemiFuture};
  __fbthrift_invocation_createEdgeLabel.compare_exchange_strong(expected, apache::thrift::detail::si::InvocationType::Sync, std::memory_order_relaxed);
  auto ret = std::make_unique<::eugraph::thrift::EdgeLabelInfo>();
  sync_createEdgeLabel(*ret, std::move(p_name), std::move(p_properties), std::move(p_graph_name));
  return folly::makeSemiFuture(std::move(ret));
}

folly::Future<std::unique_ptr<::eugraph::thrift::EdgeLabelInfo>> apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>::future_createEdgeLabel(std::unique_ptr<::std::string> p_name, std::unique_ptr<::std::vector<::eugraph::thrift::PropertyDefThrift>> p_properties, std::unique_ptr<::std::string> p_graph_name) {
  auto expected{apache::thrift::detail::si::InvocationType::Future};
  __fbthrift_invocation_createEdgeLabel.compare_exchange_strong(expected, apache::thrift::detail::si::InvocationType::SemiFuture, std::memory_order_relaxed);
  return apache::thrift::detail::si::future(semifuture_createEdgeLabel(std::move(p_name), std::move(p_properties), std::move(p_graph_name)), getInternalKeepAlive());
}

#if FOLLY_HAS_COROUTINES
folly::coro::Task<std::unique_ptr<::eugraph::thrift::EdgeLabelInfo>> apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>::co_createEdgeLabel(std::unique_ptr<::std::string> p_name, std::unique_ptr<::std::vector<::eugraph::thrift::PropertyDefThrift>> p_properties, std::unique_ptr<::std::string> p_graph_name) {
  auto expected{apache::thrift::detail::si::InvocationType::Coro};
  __fbthrift_invocation_createEdgeLabel.compare_exchange_strong(expected, apache::thrift::detail::si::InvocationType::Future, std::memory_order_relaxed);
  folly::throw_exception(apache::thrift::detail::si::UnimplementedCoroMethod::withCapturedArgs<std::unique_ptr<::std::string> /*name*/, std::unique_ptr<::std::vector<::eugraph::thrift::PropertyDefThrift>> /*properties*/, std::unique_ptr<::std::string> /*graph_name*/>(std::move(p_name), std::move(p_properties), std::move(p_graph_name)));
}

folly::coro::Task<std::unique_ptr<::eugraph::thrift::EdgeLabelInfo>> apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>::co_createEdgeLabel(apache::thrift::RequestParams /* params */, std::unique_ptr<::std::string> p_name, std::unique_ptr<::std::vector<::eugraph::thrift::PropertyDefThrift>> p_properties, std::unique_ptr<::std::string> p_graph_name) {
  auto expected{apache::thrift::detail::si::InvocationType::CoroParam};
  __fbthrift_invocation_createEdgeLabel.compare_exchange_strong(expected, apache::thrift::detail::si::InvocationType::Coro, std::memory_order_relaxed);
  return co_createEdgeLabel(std::move(p_name), std::move(p_properties), std::move(p_graph_name));
}
#endif // FOLLY_HAS_COROUTINES

void apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>::async_tm_createEdgeLabel(apache::thrift::HandlerCallbackPtr<std::unique_ptr<::eugraph::thrift::EdgeLabelInfo>> callback, std::unique_ptr<::std::string> p_name, std::unique_ptr<::std::vector<::eugraph::thrift::PropertyDefThrift>> p_properties, std::unique_ptr<::std::string> p_graph_name) {
  // It's possible the coroutine versions will delegate to a future-based
  // version. If that happens, we need the RequestParams arguments to be
  // available to the future through the thread-local backchannel, so we create
  // a RAII object that sets up RequestParams and clears them on destruction.
  apache::thrift::detail::si::AsyncTmPrep asyncTmPrep(this, callback.get());
#if FOLLY_HAS_COROUTINES
determineInvocationType:
#endif // FOLLY_HAS_COROUTINES
  auto invocationType = __fbthrift_invocation_createEdgeLabel.load(std::memory_order_relaxed);
  try {
    switch (invocationType) {
      case apache::thrift::detail::si::InvocationType::AsyncTm:
      {
#if FOLLY_HAS_COROUTINES
        __fbthrift_invocation_createEdgeLabel.compare_exchange_strong(invocationType, apache::thrift::detail::si::InvocationType::CoroParam, std::memory_order_relaxed);
        apache::thrift::RequestParams params{callback->getRequestContext(),
          callback->getThreadManager_deprecated(), callback->getEventBase(), callback->getHandlerExecutor()};
        auto task = co_createEdgeLabel(params, std::move(p_name), std::move(p_properties), std::move(p_graph_name));
        apache::thrift::detail::si::async_tm_coro(std::move(callback), std::move(task));
        return;
#else // FOLLY_HAS_COROUTINES
        __fbthrift_invocation_createEdgeLabel.compare_exchange_strong(invocationType, apache::thrift::detail::si::InvocationType::Future, std::memory_order_relaxed);
        [[fallthrough]];
#endif // FOLLY_HAS_COROUTINES
      }
      case apache::thrift::detail::si::InvocationType::Future:
      {
        auto fut = future_createEdgeLabel(std::move(p_name), std::move(p_properties), std::move(p_graph_name));
        apache::thrift::detail::si::async_tm_future(std::move(callback), std::move(fut));
        return;
      }
      case apache::thrift::detail::si::InvocationType::SemiFuture:
      {
        auto fut = semifuture_createEdgeLabel(std::move(p_name), std::move(p_properties), std::move(p_graph_name));
        apache::thrift::detail::si::async_tm_semifuture(std::move(callback), std::move(fut));
        return;
      }
#if FOLLY_HAS_COROUTINES
      case apache::thrift::detail::si::InvocationType::CoroParam:
      {
        apache::thrift::RequestParams params{callback->getRequestContext(),
          callback->getThreadManager_deprecated(), callback->getEventBase(), callback->getHandlerExecutor()};
        auto task = co_createEdgeLabel(params, std::move(p_name), std::move(p_properties), std::move(p_graph_name));
        apache::thrift::detail::si::async_tm_coro(std::move(callback), std::move(task));
        return;
      }
      case apache::thrift::detail::si::InvocationType::Coro:
      {
        auto task = co_createEdgeLabel(std::move(p_name), std::move(p_properties), std::move(p_graph_name));
        apache::thrift::detail::si::async_tm_coro(std::move(callback), std::move(task));
        return;
      }
#endif // FOLLY_HAS_COROUTINES
      case apache::thrift::detail::si::InvocationType::Sync:
      {
        ::eugraph::thrift::EdgeLabelInfo _return;
        sync_createEdgeLabel(_return, std::move(p_name), std::move(p_properties), std::move(p_graph_name));
        callback->result(std::move(_return));
        return;
      }
      default:
      {
        folly::assume_unreachable();
      }
    }
#if FOLLY_HAS_COROUTINES
  } catch (apache::thrift::detail::si::UnimplementedCoroMethod& ex) {
    std::tie(p_name, p_properties, p_graph_name) = std::move(ex).restoreArgs<std::unique_ptr<::std::string> /*name*/, std::unique_ptr<::std::vector<::eugraph::thrift::PropertyDefThrift>> /*properties*/, std::unique_ptr<::std::string> /*graph_name*/>();
    goto determineInvocationType;
#endif // FOLLY_HAS_COROUTINES
  } catch (...) {
    callback->exception(std::current_exception());
  }
}

void apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>::listEdgeLabels(::std::vector<::eugraph::thrift::EdgeLabelInfo>& /*_return*/, std::unique_ptr<::std::string> /*graph_name*/) {
  apache::thrift::detail::si::throw_app_exn_unimplemented("listEdgeLabels");
}

void apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>::sync_listEdgeLabels(::std::vector<::eugraph::thrift::EdgeLabelInfo>& _return, std::unique_ptr<::std::string> p_graph_name) {
  return listEdgeLabels(_return, std::move(p_graph_name));
}

folly::SemiFuture<std::unique_ptr<::std::vector<::eugraph::thrift::EdgeLabelInfo>>> apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>::semifuture_listEdgeLabels(std::unique_ptr<::std::string> p_graph_name) {
  auto expected{apache::thrift::detail::si::InvocationType::SemiFuture};
  __fbthrift_invocation_listEdgeLabels.compare_exchange_strong(expected, apache::thrift::detail::si::InvocationType::Sync, std::memory_order_relaxed);
  auto ret = std::make_unique<::std::vector<::eugraph::thrift::EdgeLabelInfo>>();
  sync_listEdgeLabels(*ret, std::move(p_graph_name));
  return folly::makeSemiFuture(std::move(ret));
}

folly::Future<std::unique_ptr<::std::vector<::eugraph::thrift::EdgeLabelInfo>>> apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>::future_listEdgeLabels(std::unique_ptr<::std::string> p_graph_name) {
  auto expected{apache::thrift::detail::si::InvocationType::Future};
  __fbthrift_invocation_listEdgeLabels.compare_exchange_strong(expected, apache::thrift::detail::si::InvocationType::SemiFuture, std::memory_order_relaxed);
  return apache::thrift::detail::si::future(semifuture_listEdgeLabels(std::move(p_graph_name)), getInternalKeepAlive());
}

#if FOLLY_HAS_COROUTINES
folly::coro::Task<std::unique_ptr<::std::vector<::eugraph::thrift::EdgeLabelInfo>>> apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>::co_listEdgeLabels(std::unique_ptr<::std::string> p_graph_name) {
  auto expected{apache::thrift::detail::si::InvocationType::Coro};
  __fbthrift_invocation_listEdgeLabels.compare_exchange_strong(expected, apache::thrift::detail::si::InvocationType::Future, std::memory_order_relaxed);
  folly::throw_exception(apache::thrift::detail::si::UnimplementedCoroMethod::withCapturedArgs<std::unique_ptr<::std::string> /*graph_name*/>(std::move(p_graph_name)));
}

folly::coro::Task<std::unique_ptr<::std::vector<::eugraph::thrift::EdgeLabelInfo>>> apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>::co_listEdgeLabels(apache::thrift::RequestParams /* params */, std::unique_ptr<::std::string> p_graph_name) {
  auto expected{apache::thrift::detail::si::InvocationType::CoroParam};
  __fbthrift_invocation_listEdgeLabels.compare_exchange_strong(expected, apache::thrift::detail::si::InvocationType::Coro, std::memory_order_relaxed);
  return co_listEdgeLabels(std::move(p_graph_name));
}
#endif // FOLLY_HAS_COROUTINES

void apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>::async_tm_listEdgeLabels(apache::thrift::HandlerCallbackPtr<std::unique_ptr<::std::vector<::eugraph::thrift::EdgeLabelInfo>>> callback, std::unique_ptr<::std::string> p_graph_name) {
  // It's possible the coroutine versions will delegate to a future-based
  // version. If that happens, we need the RequestParams arguments to be
  // available to the future through the thread-local backchannel, so we create
  // a RAII object that sets up RequestParams and clears them on destruction.
  apache::thrift::detail::si::AsyncTmPrep asyncTmPrep(this, callback.get());
#if FOLLY_HAS_COROUTINES
determineInvocationType:
#endif // FOLLY_HAS_COROUTINES
  auto invocationType = __fbthrift_invocation_listEdgeLabels.load(std::memory_order_relaxed);
  try {
    switch (invocationType) {
      case apache::thrift::detail::si::InvocationType::AsyncTm:
      {
#if FOLLY_HAS_COROUTINES
        __fbthrift_invocation_listEdgeLabels.compare_exchange_strong(invocationType, apache::thrift::detail::si::InvocationType::CoroParam, std::memory_order_relaxed);
        apache::thrift::RequestParams params{callback->getRequestContext(),
          callback->getThreadManager_deprecated(), callback->getEventBase(), callback->getHandlerExecutor()};
        auto task = co_listEdgeLabels(params, std::move(p_graph_name));
        apache::thrift::detail::si::async_tm_coro(std::move(callback), std::move(task));
        return;
#else // FOLLY_HAS_COROUTINES
        __fbthrift_invocation_listEdgeLabels.compare_exchange_strong(invocationType, apache::thrift::detail::si::InvocationType::Future, std::memory_order_relaxed);
        [[fallthrough]];
#endif // FOLLY_HAS_COROUTINES
      }
      case apache::thrift::detail::si::InvocationType::Future:
      {
        auto fut = future_listEdgeLabels(std::move(p_graph_name));
        apache::thrift::detail::si::async_tm_future(std::move(callback), std::move(fut));
        return;
      }
      case apache::thrift::detail::si::InvocationType::SemiFuture:
      {
        auto fut = semifuture_listEdgeLabels(std::move(p_graph_name));
        apache::thrift::detail::si::async_tm_semifuture(std::move(callback), std::move(fut));
        return;
      }
#if FOLLY_HAS_COROUTINES
      case apache::thrift::detail::si::InvocationType::CoroParam:
      {
        apache::thrift::RequestParams params{callback->getRequestContext(),
          callback->getThreadManager_deprecated(), callback->getEventBase(), callback->getHandlerExecutor()};
        auto task = co_listEdgeLabels(params, std::move(p_graph_name));
        apache::thrift::detail::si::async_tm_coro(std::move(callback), std::move(task));
        return;
      }
      case apache::thrift::detail::si::InvocationType::Coro:
      {
        auto task = co_listEdgeLabels(std::move(p_graph_name));
        apache::thrift::detail::si::async_tm_coro(std::move(callback), std::move(task));
        return;
      }
#endif // FOLLY_HAS_COROUTINES
      case apache::thrift::detail::si::InvocationType::Sync:
      {
        ::std::vector<::eugraph::thrift::EdgeLabelInfo> _return;
        sync_listEdgeLabels(_return, std::move(p_graph_name));
        callback->result(std::move(_return));
        return;
      }
      default:
      {
        folly::assume_unreachable();
      }
    }
#if FOLLY_HAS_COROUTINES
  } catch (apache::thrift::detail::si::UnimplementedCoroMethod& ex) {
    std::tie(p_graph_name) = std::move(ex).restoreArgs<std::unique_ptr<::std::string> /*graph_name*/>();
    goto determineInvocationType;
#endif // FOLLY_HAS_COROUTINES
  } catch (...) {
    callback->exception(std::current_exception());
  }
}

::apache::thrift::ResponseAndServerStream<::eugraph::thrift::QueryStreamMeta, ::eugraph::thrift::ResultRowBatch> apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>::executeCypher(std::unique_ptr<::std::string> /*query*/, std::unique_ptr<::std::string> /*graph_name*/, std::unique_ptr<::std::map<::std::string, ::std::string>> /*parameters*/) {
  apache::thrift::detail::si::throw_app_exn_unimplemented("executeCypher");
}

::apache::thrift::ResponseAndServerStream<::eugraph::thrift::QueryStreamMeta, ::eugraph::thrift::ResultRowBatch> apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>::sync_executeCypher(std::unique_ptr<::std::string> p_query, std::unique_ptr<::std::string> p_graph_name, std::unique_ptr<::std::map<::std::string, ::std::string>> p_parameters) {
  return executeCypher(std::move(p_query), std::move(p_graph_name), std::move(p_parameters));
}

folly::SemiFuture<::apache::thrift::ResponseAndServerStream<::eugraph::thrift::QueryStreamMeta, ::eugraph::thrift::ResultRowBatch>> apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>::semifuture_executeCypher(std::unique_ptr<::std::string> p_query, std::unique_ptr<::std::string> p_graph_name, std::unique_ptr<::std::map<::std::string, ::std::string>> p_parameters) {
  auto expected{apache::thrift::detail::si::InvocationType::SemiFuture};
  __fbthrift_invocation_executeCypher.compare_exchange_strong(expected, apache::thrift::detail::si::InvocationType::Sync, std::memory_order_relaxed);
  return sync_executeCypher(std::move(p_query), std::move(p_graph_name), std::move(p_parameters));
}

folly::Future<::apache::thrift::ResponseAndServerStream<::eugraph::thrift::QueryStreamMeta, ::eugraph::thrift::ResultRowBatch>> apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>::future_executeCypher(std::unique_ptr<::std::string> p_query, std::unique_ptr<::std::string> p_graph_name, std::unique_ptr<::std::map<::std::string, ::std::string>> p_parameters) {
  auto expected{apache::thrift::detail::si::InvocationType::Future};
  __fbthrift_invocation_executeCypher.compare_exchange_strong(expected, apache::thrift::detail::si::InvocationType::SemiFuture, std::memory_order_relaxed);
  return apache::thrift::detail::si::future(semifuture_executeCypher(std::move(p_query), std::move(p_graph_name), std::move(p_parameters)), getInternalKeepAlive());
}

#if FOLLY_HAS_COROUTINES
folly::coro::Task<::apache::thrift::ResponseAndServerStream<::eugraph::thrift::QueryStreamMeta, ::eugraph::thrift::ResultRowBatch>> apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>::co_executeCypher(std::unique_ptr<::std::string> p_query, std::unique_ptr<::std::string> p_graph_name, std::unique_ptr<::std::map<::std::string, ::std::string>> p_parameters) {
  auto expected{apache::thrift::detail::si::InvocationType::Coro};
  __fbthrift_invocation_executeCypher.compare_exchange_strong(expected, apache::thrift::detail::si::InvocationType::Future, std::memory_order_relaxed);
  folly::throw_exception(apache::thrift::detail::si::UnimplementedCoroMethod::withCapturedArgs<std::unique_ptr<::std::string> /*query*/, std::unique_ptr<::std::string> /*graph_name*/, std::unique_ptr<::std::map<::std::string, ::std::string>> /*parameters*/>(std::move(p_query), std::move(p_graph_name), std::move(p_parameters)));
}

folly::coro::Task<::apache::thrift::ResponseAndServerStream<::eugraph::thrift::QueryStreamMeta, ::eugraph::thrift::ResultRowBatch>> apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>::co_executeCypher(apache::thrift::RequestParams /* params */, std::unique_ptr<::std::string> p_query, std::unique_ptr<::std::string> p_graph_name, std::unique_ptr<::std::map<::std::string, ::std::string>> p_parameters) {
  auto expected{apache::thrift::detail::si::InvocationType::CoroParam};
  __fbthrift_invocation_executeCypher.compare_exchange_strong(expected, apache::thrift::detail::si::InvocationType::Coro, std::memory_order_relaxed);
  return co_executeCypher(std::move(p_query), std::move(p_graph_name), std::move(p_parameters));
}
#endif // FOLLY_HAS_COROUTINES

void apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>::async_tm_executeCypher(apache::thrift::HandlerCallbackPtr<::apache::thrift::ResponseAndServerStream<::eugraph::thrift::QueryStreamMeta, ::eugraph::thrift::ResultRowBatch>> callback, std::unique_ptr<::std::string> p_query, std::unique_ptr<::std::string> p_graph_name, std::unique_ptr<::std::map<::std::string, ::std::string>> p_parameters) {
  // It's possible the coroutine versions will delegate to a future-based
  // version. If that happens, we need the RequestParams arguments to be
  // available to the future through the thread-local backchannel, so we create
  // a RAII object that sets up RequestParams and clears them on destruction.
  apache::thrift::detail::si::AsyncTmPrep asyncTmPrep(this, callback.get());
#if FOLLY_HAS_COROUTINES
determineInvocationType:
#endif // FOLLY_HAS_COROUTINES
  auto invocationType = __fbthrift_invocation_executeCypher.load(std::memory_order_relaxed);
  try {
    switch (invocationType) {
      case apache::thrift::detail::si::InvocationType::AsyncTm:
      {
#if FOLLY_HAS_COROUTINES
        __fbthrift_invocation_executeCypher.compare_exchange_strong(invocationType, apache::thrift::detail::si::InvocationType::CoroParam, std::memory_order_relaxed);
        apache::thrift::RequestParams params{callback->getRequestContext(),
          callback->getThreadManager_deprecated(), callback->getEventBase(), callback->getHandlerExecutor()};
        auto task = co_executeCypher(params, std::move(p_query), std::move(p_graph_name), std::move(p_parameters));
        apache::thrift::detail::si::async_tm_coro(std::move(callback), std::move(task));
        return;
#else // FOLLY_HAS_COROUTINES
        __fbthrift_invocation_executeCypher.compare_exchange_strong(invocationType, apache::thrift::detail::si::InvocationType::Future, std::memory_order_relaxed);
        [[fallthrough]];
#endif // FOLLY_HAS_COROUTINES
      }
      case apache::thrift::detail::si::InvocationType::Future:
      {
        auto fut = future_executeCypher(std::move(p_query), std::move(p_graph_name), std::move(p_parameters));
        apache::thrift::detail::si::async_tm_future(std::move(callback), std::move(fut));
        return;
      }
      case apache::thrift::detail::si::InvocationType::SemiFuture:
      {
        auto fut = semifuture_executeCypher(std::move(p_query), std::move(p_graph_name), std::move(p_parameters));
        apache::thrift::detail::si::async_tm_semifuture(std::move(callback), std::move(fut));
        return;
      }
#if FOLLY_HAS_COROUTINES
      case apache::thrift::detail::si::InvocationType::CoroParam:
      {
        apache::thrift::RequestParams params{callback->getRequestContext(),
          callback->getThreadManager_deprecated(), callback->getEventBase(), callback->getHandlerExecutor()};
        auto task = co_executeCypher(params, std::move(p_query), std::move(p_graph_name), std::move(p_parameters));
        apache::thrift::detail::si::async_tm_coro(std::move(callback), std::move(task));
        return;
      }
      case apache::thrift::detail::si::InvocationType::Coro:
      {
        auto task = co_executeCypher(std::move(p_query), std::move(p_graph_name), std::move(p_parameters));
        apache::thrift::detail::si::async_tm_coro(std::move(callback), std::move(task));
        return;
      }
#endif // FOLLY_HAS_COROUTINES
      case apache::thrift::detail::si::InvocationType::Sync:
      {
        callback->result(sync_executeCypher(std::move(p_query), std::move(p_graph_name), std::move(p_parameters)));
        return;
      }
      default:
      {
        folly::assume_unreachable();
      }
    }
#if FOLLY_HAS_COROUTINES
  } catch (apache::thrift::detail::si::UnimplementedCoroMethod& ex) {
    std::tie(p_query, p_graph_name, p_parameters) = std::move(ex).restoreArgs<std::unique_ptr<::std::string> /*query*/, std::unique_ptr<::std::string> /*graph_name*/, std::unique_ptr<::std::map<::std::string, ::std::string>> /*parameters*/>();
    goto determineInvocationType;
#endif // FOLLY_HAS_COROUTINES
  } catch (...) {
    callback->exception(std::current_exception());
  }
}

void apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>::batchInsertVertices(::eugraph::thrift::BatchInsertVerticesResult& /*_return*/, std::unique_ptr<::std::string> /*label_name*/, std::unique_ptr<::std::vector<::eugraph::thrift::VertexRecord>> /*records*/, std::unique_ptr<::std::string> /*graph_name*/) {
  apache::thrift::detail::si::throw_app_exn_unimplemented("batchInsertVertices");
}

void apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>::sync_batchInsertVertices(::eugraph::thrift::BatchInsertVerticesResult& _return, std::unique_ptr<::std::string> p_label_name, std::unique_ptr<::std::vector<::eugraph::thrift::VertexRecord>> p_records, std::unique_ptr<::std::string> p_graph_name) {
  return batchInsertVertices(_return, std::move(p_label_name), std::move(p_records), std::move(p_graph_name));
}

folly::SemiFuture<std::unique_ptr<::eugraph::thrift::BatchInsertVerticesResult>> apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>::semifuture_batchInsertVertices(std::unique_ptr<::std::string> p_label_name, std::unique_ptr<::std::vector<::eugraph::thrift::VertexRecord>> p_records, std::unique_ptr<::std::string> p_graph_name) {
  auto expected{apache::thrift::detail::si::InvocationType::SemiFuture};
  __fbthrift_invocation_batchInsertVertices.compare_exchange_strong(expected, apache::thrift::detail::si::InvocationType::Sync, std::memory_order_relaxed);
  auto ret = std::make_unique<::eugraph::thrift::BatchInsertVerticesResult>();
  sync_batchInsertVertices(*ret, std::move(p_label_name), std::move(p_records), std::move(p_graph_name));
  return folly::makeSemiFuture(std::move(ret));
}

folly::Future<std::unique_ptr<::eugraph::thrift::BatchInsertVerticesResult>> apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>::future_batchInsertVertices(std::unique_ptr<::std::string> p_label_name, std::unique_ptr<::std::vector<::eugraph::thrift::VertexRecord>> p_records, std::unique_ptr<::std::string> p_graph_name) {
  auto expected{apache::thrift::detail::si::InvocationType::Future};
  __fbthrift_invocation_batchInsertVertices.compare_exchange_strong(expected, apache::thrift::detail::si::InvocationType::SemiFuture, std::memory_order_relaxed);
  return apache::thrift::detail::si::future(semifuture_batchInsertVertices(std::move(p_label_name), std::move(p_records), std::move(p_graph_name)), getInternalKeepAlive());
}

#if FOLLY_HAS_COROUTINES
folly::coro::Task<std::unique_ptr<::eugraph::thrift::BatchInsertVerticesResult>> apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>::co_batchInsertVertices(std::unique_ptr<::std::string> p_label_name, std::unique_ptr<::std::vector<::eugraph::thrift::VertexRecord>> p_records, std::unique_ptr<::std::string> p_graph_name) {
  auto expected{apache::thrift::detail::si::InvocationType::Coro};
  __fbthrift_invocation_batchInsertVertices.compare_exchange_strong(expected, apache::thrift::detail::si::InvocationType::Future, std::memory_order_relaxed);
  folly::throw_exception(apache::thrift::detail::si::UnimplementedCoroMethod::withCapturedArgs<std::unique_ptr<::std::string> /*label_name*/, std::unique_ptr<::std::vector<::eugraph::thrift::VertexRecord>> /*records*/, std::unique_ptr<::std::string> /*graph_name*/>(std::move(p_label_name), std::move(p_records), std::move(p_graph_name)));
}

folly::coro::Task<std::unique_ptr<::eugraph::thrift::BatchInsertVerticesResult>> apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>::co_batchInsertVertices(apache::thrift::RequestParams /* params */, std::unique_ptr<::std::string> p_label_name, std::unique_ptr<::std::vector<::eugraph::thrift::VertexRecord>> p_records, std::unique_ptr<::std::string> p_graph_name) {
  auto expected{apache::thrift::detail::si::InvocationType::CoroParam};
  __fbthrift_invocation_batchInsertVertices.compare_exchange_strong(expected, apache::thrift::detail::si::InvocationType::Coro, std::memory_order_relaxed);
  return co_batchInsertVertices(std::move(p_label_name), std::move(p_records), std::move(p_graph_name));
}
#endif // FOLLY_HAS_COROUTINES

void apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>::async_tm_batchInsertVertices(apache::thrift::HandlerCallbackPtr<std::unique_ptr<::eugraph::thrift::BatchInsertVerticesResult>> callback, std::unique_ptr<::std::string> p_label_name, std::unique_ptr<::std::vector<::eugraph::thrift::VertexRecord>> p_records, std::unique_ptr<::std::string> p_graph_name) {
  // It's possible the coroutine versions will delegate to a future-based
  // version. If that happens, we need the RequestParams arguments to be
  // available to the future through the thread-local backchannel, so we create
  // a RAII object that sets up RequestParams and clears them on destruction.
  apache::thrift::detail::si::AsyncTmPrep asyncTmPrep(this, callback.get());
#if FOLLY_HAS_COROUTINES
determineInvocationType:
#endif // FOLLY_HAS_COROUTINES
  auto invocationType = __fbthrift_invocation_batchInsertVertices.load(std::memory_order_relaxed);
  try {
    switch (invocationType) {
      case apache::thrift::detail::si::InvocationType::AsyncTm:
      {
#if FOLLY_HAS_COROUTINES
        __fbthrift_invocation_batchInsertVertices.compare_exchange_strong(invocationType, apache::thrift::detail::si::InvocationType::CoroParam, std::memory_order_relaxed);
        apache::thrift::RequestParams params{callback->getRequestContext(),
          callback->getThreadManager_deprecated(), callback->getEventBase(), callback->getHandlerExecutor()};
        auto task = co_batchInsertVertices(params, std::move(p_label_name), std::move(p_records), std::move(p_graph_name));
        apache::thrift::detail::si::async_tm_coro(std::move(callback), std::move(task));
        return;
#else // FOLLY_HAS_COROUTINES
        __fbthrift_invocation_batchInsertVertices.compare_exchange_strong(invocationType, apache::thrift::detail::si::InvocationType::Future, std::memory_order_relaxed);
        [[fallthrough]];
#endif // FOLLY_HAS_COROUTINES
      }
      case apache::thrift::detail::si::InvocationType::Future:
      {
        auto fut = future_batchInsertVertices(std::move(p_label_name), std::move(p_records), std::move(p_graph_name));
        apache::thrift::detail::si::async_tm_future(std::move(callback), std::move(fut));
        return;
      }
      case apache::thrift::detail::si::InvocationType::SemiFuture:
      {
        auto fut = semifuture_batchInsertVertices(std::move(p_label_name), std::move(p_records), std::move(p_graph_name));
        apache::thrift::detail::si::async_tm_semifuture(std::move(callback), std::move(fut));
        return;
      }
#if FOLLY_HAS_COROUTINES
      case apache::thrift::detail::si::InvocationType::CoroParam:
      {
        apache::thrift::RequestParams params{callback->getRequestContext(),
          callback->getThreadManager_deprecated(), callback->getEventBase(), callback->getHandlerExecutor()};
        auto task = co_batchInsertVertices(params, std::move(p_label_name), std::move(p_records), std::move(p_graph_name));
        apache::thrift::detail::si::async_tm_coro(std::move(callback), std::move(task));
        return;
      }
      case apache::thrift::detail::si::InvocationType::Coro:
      {
        auto task = co_batchInsertVertices(std::move(p_label_name), std::move(p_records), std::move(p_graph_name));
        apache::thrift::detail::si::async_tm_coro(std::move(callback), std::move(task));
        return;
      }
#endif // FOLLY_HAS_COROUTINES
      case apache::thrift::detail::si::InvocationType::Sync:
      {
        ::eugraph::thrift::BatchInsertVerticesResult _return;
        sync_batchInsertVertices(_return, std::move(p_label_name), std::move(p_records), std::move(p_graph_name));
        callback->result(std::move(_return));
        return;
      }
      default:
      {
        folly::assume_unreachable();
      }
    }
#if FOLLY_HAS_COROUTINES
  } catch (apache::thrift::detail::si::UnimplementedCoroMethod& ex) {
    std::tie(p_label_name, p_records, p_graph_name) = std::move(ex).restoreArgs<std::unique_ptr<::std::string> /*label_name*/, std::unique_ptr<::std::vector<::eugraph::thrift::VertexRecord>> /*records*/, std::unique_ptr<::std::string> /*graph_name*/>();
    goto determineInvocationType;
#endif // FOLLY_HAS_COROUTINES
  } catch (...) {
    callback->exception(std::current_exception());
  }
}

::std::int32_t apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>::batchInsertEdges(std::unique_ptr<::std::string> /*edge_label_name*/, std::unique_ptr<::std::vector<::eugraph::thrift::EdgeRecord>> /*records*/, std::unique_ptr<::std::string> /*graph_name*/) {
  apache::thrift::detail::si::throw_app_exn_unimplemented("batchInsertEdges");
}

::std::int32_t apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>::sync_batchInsertEdges(std::unique_ptr<::std::string> p_edge_label_name, std::unique_ptr<::std::vector<::eugraph::thrift::EdgeRecord>> p_records, std::unique_ptr<::std::string> p_graph_name) {
  return batchInsertEdges(std::move(p_edge_label_name), std::move(p_records), std::move(p_graph_name));
}

folly::SemiFuture<::std::int32_t> apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>::semifuture_batchInsertEdges(std::unique_ptr<::std::string> p_edge_label_name, std::unique_ptr<::std::vector<::eugraph::thrift::EdgeRecord>> p_records, std::unique_ptr<::std::string> p_graph_name) {
  auto expected{apache::thrift::detail::si::InvocationType::SemiFuture};
  __fbthrift_invocation_batchInsertEdges.compare_exchange_strong(expected, apache::thrift::detail::si::InvocationType::Sync, std::memory_order_relaxed);
  return sync_batchInsertEdges(std::move(p_edge_label_name), std::move(p_records), std::move(p_graph_name));
}

folly::Future<::std::int32_t> apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>::future_batchInsertEdges(std::unique_ptr<::std::string> p_edge_label_name, std::unique_ptr<::std::vector<::eugraph::thrift::EdgeRecord>> p_records, std::unique_ptr<::std::string> p_graph_name) {
  auto expected{apache::thrift::detail::si::InvocationType::Future};
  __fbthrift_invocation_batchInsertEdges.compare_exchange_strong(expected, apache::thrift::detail::si::InvocationType::SemiFuture, std::memory_order_relaxed);
  return apache::thrift::detail::si::future(semifuture_batchInsertEdges(std::move(p_edge_label_name), std::move(p_records), std::move(p_graph_name)), getInternalKeepAlive());
}

#if FOLLY_HAS_COROUTINES
folly::coro::Task<::std::int32_t> apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>::co_batchInsertEdges(std::unique_ptr<::std::string> p_edge_label_name, std::unique_ptr<::std::vector<::eugraph::thrift::EdgeRecord>> p_records, std::unique_ptr<::std::string> p_graph_name) {
  auto expected{apache::thrift::detail::si::InvocationType::Coro};
  __fbthrift_invocation_batchInsertEdges.compare_exchange_strong(expected, apache::thrift::detail::si::InvocationType::Future, std::memory_order_relaxed);
  folly::throw_exception(apache::thrift::detail::si::UnimplementedCoroMethod::withCapturedArgs<std::unique_ptr<::std::string> /*edge_label_name*/, std::unique_ptr<::std::vector<::eugraph::thrift::EdgeRecord>> /*records*/, std::unique_ptr<::std::string> /*graph_name*/>(std::move(p_edge_label_name), std::move(p_records), std::move(p_graph_name)));
}

folly::coro::Task<::std::int32_t> apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>::co_batchInsertEdges(apache::thrift::RequestParams /* params */, std::unique_ptr<::std::string> p_edge_label_name, std::unique_ptr<::std::vector<::eugraph::thrift::EdgeRecord>> p_records, std::unique_ptr<::std::string> p_graph_name) {
  auto expected{apache::thrift::detail::si::InvocationType::CoroParam};
  __fbthrift_invocation_batchInsertEdges.compare_exchange_strong(expected, apache::thrift::detail::si::InvocationType::Coro, std::memory_order_relaxed);
  return co_batchInsertEdges(std::move(p_edge_label_name), std::move(p_records), std::move(p_graph_name));
}
#endif // FOLLY_HAS_COROUTINES

void apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>::async_tm_batchInsertEdges(apache::thrift::HandlerCallbackPtr<::std::int32_t> callback, std::unique_ptr<::std::string> p_edge_label_name, std::unique_ptr<::std::vector<::eugraph::thrift::EdgeRecord>> p_records, std::unique_ptr<::std::string> p_graph_name) {
  // It's possible the coroutine versions will delegate to a future-based
  // version. If that happens, we need the RequestParams arguments to be
  // available to the future through the thread-local backchannel, so we create
  // a RAII object that sets up RequestParams and clears them on destruction.
  apache::thrift::detail::si::AsyncTmPrep asyncTmPrep(this, callback.get());
#if FOLLY_HAS_COROUTINES
determineInvocationType:
#endif // FOLLY_HAS_COROUTINES
  auto invocationType = __fbthrift_invocation_batchInsertEdges.load(std::memory_order_relaxed);
  try {
    switch (invocationType) {
      case apache::thrift::detail::si::InvocationType::AsyncTm:
      {
#if FOLLY_HAS_COROUTINES
        __fbthrift_invocation_batchInsertEdges.compare_exchange_strong(invocationType, apache::thrift::detail::si::InvocationType::CoroParam, std::memory_order_relaxed);
        apache::thrift::RequestParams params{callback->getRequestContext(),
          callback->getThreadManager_deprecated(), callback->getEventBase(), callback->getHandlerExecutor()};
        auto task = co_batchInsertEdges(params, std::move(p_edge_label_name), std::move(p_records), std::move(p_graph_name));
        apache::thrift::detail::si::async_tm_coro(std::move(callback), std::move(task));
        return;
#else // FOLLY_HAS_COROUTINES
        __fbthrift_invocation_batchInsertEdges.compare_exchange_strong(invocationType, apache::thrift::detail::si::InvocationType::Future, std::memory_order_relaxed);
        [[fallthrough]];
#endif // FOLLY_HAS_COROUTINES
      }
      case apache::thrift::detail::si::InvocationType::Future:
      {
        auto fut = future_batchInsertEdges(std::move(p_edge_label_name), std::move(p_records), std::move(p_graph_name));
        apache::thrift::detail::si::async_tm_future(std::move(callback), std::move(fut));
        return;
      }
      case apache::thrift::detail::si::InvocationType::SemiFuture:
      {
        auto fut = semifuture_batchInsertEdges(std::move(p_edge_label_name), std::move(p_records), std::move(p_graph_name));
        apache::thrift::detail::si::async_tm_semifuture(std::move(callback), std::move(fut));
        return;
      }
#if FOLLY_HAS_COROUTINES
      case apache::thrift::detail::si::InvocationType::CoroParam:
      {
        apache::thrift::RequestParams params{callback->getRequestContext(),
          callback->getThreadManager_deprecated(), callback->getEventBase(), callback->getHandlerExecutor()};
        auto task = co_batchInsertEdges(params, std::move(p_edge_label_name), std::move(p_records), std::move(p_graph_name));
        apache::thrift::detail::si::async_tm_coro(std::move(callback), std::move(task));
        return;
      }
      case apache::thrift::detail::si::InvocationType::Coro:
      {
        auto task = co_batchInsertEdges(std::move(p_edge_label_name), std::move(p_records), std::move(p_graph_name));
        apache::thrift::detail::si::async_tm_coro(std::move(callback), std::move(task));
        return;
      }
#endif // FOLLY_HAS_COROUTINES
      case apache::thrift::detail::si::InvocationType::Sync:
      {
        callback->result(sync_batchInsertEdges(std::move(p_edge_label_name), std::move(p_records), std::move(p_graph_name)));
        return;
      }
      default:
      {
        folly::assume_unreachable();
      }
    }
#if FOLLY_HAS_COROUTINES
  } catch (apache::thrift::detail::si::UnimplementedCoroMethod& ex) {
    std::tie(p_edge_label_name, p_records, p_graph_name) = std::move(ex).restoreArgs<std::unique_ptr<::std::string> /*edge_label_name*/, std::unique_ptr<::std::vector<::eugraph::thrift::EdgeRecord>> /*records*/, std::unique_ptr<::std::string> /*graph_name*/>();
    goto determineInvocationType;
#endif // FOLLY_HAS_COROUTINES
  } catch (...) {
    callback->exception(std::current_exception());
  }
}


namespace eugraph::thrift {

void EuGraphServiceSvNull::createGraph(::eugraph::thrift::GraphInfo& /*_return*/, std::unique_ptr<::std::string> /*name*/) {  }

bool EuGraphServiceSvNull::dropGraph(std::unique_ptr<::std::string> /*name*/) { 
  return 0;
}

void EuGraphServiceSvNull::listGraphs(::std::vector<::eugraph::thrift::GraphInfo>& /*_return*/) {  }

void EuGraphServiceSvNull::createLabel(::eugraph::thrift::LabelInfo& /*_return*/, std::unique_ptr<::std::string> /*name*/, std::unique_ptr<::std::vector<::eugraph::thrift::PropertyDefThrift>> /*properties*/, std::unique_ptr<::std::string> /*graph_name*/) {  }

void EuGraphServiceSvNull::listLabels(::std::vector<::eugraph::thrift::LabelInfo>& /*_return*/, std::unique_ptr<::std::string> /*graph_name*/) {  }

void EuGraphServiceSvNull::createEdgeLabel(::eugraph::thrift::EdgeLabelInfo& /*_return*/, std::unique_ptr<::std::string> /*name*/, std::unique_ptr<::std::vector<::eugraph::thrift::PropertyDefThrift>> /*properties*/, std::unique_ptr<::std::string> /*graph_name*/) {  }

void EuGraphServiceSvNull::listEdgeLabels(::std::vector<::eugraph::thrift::EdgeLabelInfo>& /*_return*/, std::unique_ptr<::std::string> /*graph_name*/) {  }

void EuGraphServiceSvNull::batchInsertVertices(::eugraph::thrift::BatchInsertVerticesResult& /*_return*/, std::unique_ptr<::std::string> /*label_name*/, std::unique_ptr<::std::vector<::eugraph::thrift::VertexRecord>> /*records*/, std::unique_ptr<::std::string> /*graph_name*/) {  }

::std::int32_t EuGraphServiceSvNull::batchInsertEdges(std::unique_ptr<::std::string> /*edge_label_name*/, std::unique_ptr<::std::vector<::eugraph::thrift::EdgeRecord>> /*records*/, std::unique_ptr<::std::string> /*graph_name*/) { 
  return 0;
}


const char* EuGraphServiceAsyncProcessor::getServiceName() {
  return "EuGraphService";
}

void EuGraphServiceAsyncProcessor::getServiceMetadata(apache::thrift::metadata::ThriftServiceMetadataResponse& response) {
  ::apache::thrift::detail::md::ServiceMetadata<::apache::thrift::ServiceHandler<::eugraph::thrift::EuGraphService>>::gen(response);
}

void EuGraphServiceAsyncProcessor::processSerializedCompressedRequestWithMetadata(apache::thrift::ResponseChannelRequest::UniquePtr req, apache::thrift::SerializedCompressedRequest&& serializedRequest, const apache::thrift::AsyncProcessorFactory::MethodMetadata& methodMetadata, apache::thrift::protocol::PROTOCOL_TYPES protType, apache::thrift::Cpp2RequestContext* context, folly::EventBase* eb, apache::thrift::concurrency::ThreadManager* tm) {
  apache::thrift::detail::ap::process(this, iface_, std::move(req), std::move(serializedRequest), methodMetadata, protType, context, eb, tm);
}

void EuGraphServiceAsyncProcessor::executeRequest(apache::thrift::ServerRequest&& request, const apache::thrift::AsyncProcessorFactory::MethodMetadata& methodMetadata) {
  apache::thrift::detail::ap::execute(this, std::move(request), apache::thrift::detail::ServerRequestHelper::protocol(request), methodMetadata);
}

const EuGraphServiceAsyncProcessor::ProcessMap& EuGraphServiceAsyncProcessor::getOwnProcessMap() {
  return kOwnProcessMap_;
}

const EuGraphServiceAsyncProcessor::ProcessMap EuGraphServiceAsyncProcessor::kOwnProcessMap_ {
  {"createGraph",
    {&EuGraphServiceAsyncProcessor::setUpAndProcess_createGraph<apache::thrift::CompactProtocolReader, apache::thrift::CompactProtocolWriter>,
     &EuGraphServiceAsyncProcessor::setUpAndProcess_createGraph<apache::thrift::BinaryProtocolReader, apache::thrift::BinaryProtocolWriter>,
     &EuGraphServiceAsyncProcessor::executeRequest_createGraph<apache::thrift::CompactProtocolReader, apache::thrift::CompactProtocolWriter>,
     &EuGraphServiceAsyncProcessor::executeRequest_createGraph<apache::thrift::BinaryProtocolReader, apache::thrift::BinaryProtocolWriter>}},
  {"dropGraph",
    {&EuGraphServiceAsyncProcessor::setUpAndProcess_dropGraph<apache::thrift::CompactProtocolReader, apache::thrift::CompactProtocolWriter>,
     &EuGraphServiceAsyncProcessor::setUpAndProcess_dropGraph<apache::thrift::BinaryProtocolReader, apache::thrift::BinaryProtocolWriter>,
     &EuGraphServiceAsyncProcessor::executeRequest_dropGraph<apache::thrift::CompactProtocolReader, apache::thrift::CompactProtocolWriter>,
     &EuGraphServiceAsyncProcessor::executeRequest_dropGraph<apache::thrift::BinaryProtocolReader, apache::thrift::BinaryProtocolWriter>}},
  {"listGraphs",
    {&EuGraphServiceAsyncProcessor::setUpAndProcess_listGraphs<apache::thrift::CompactProtocolReader, apache::thrift::CompactProtocolWriter>,
     &EuGraphServiceAsyncProcessor::setUpAndProcess_listGraphs<apache::thrift::BinaryProtocolReader, apache::thrift::BinaryProtocolWriter>,
     &EuGraphServiceAsyncProcessor::executeRequest_listGraphs<apache::thrift::CompactProtocolReader, apache::thrift::CompactProtocolWriter>,
     &EuGraphServiceAsyncProcessor::executeRequest_listGraphs<apache::thrift::BinaryProtocolReader, apache::thrift::BinaryProtocolWriter>}},
  {"createLabel",
    {&EuGraphServiceAsyncProcessor::setUpAndProcess_createLabel<apache::thrift::CompactProtocolReader, apache::thrift::CompactProtocolWriter>,
     &EuGraphServiceAsyncProcessor::setUpAndProcess_createLabel<apache::thrift::BinaryProtocolReader, apache::thrift::BinaryProtocolWriter>,
     &EuGraphServiceAsyncProcessor::executeRequest_createLabel<apache::thrift::CompactProtocolReader, apache::thrift::CompactProtocolWriter>,
     &EuGraphServiceAsyncProcessor::executeRequest_createLabel<apache::thrift::BinaryProtocolReader, apache::thrift::BinaryProtocolWriter>}},
  {"listLabels",
    {&EuGraphServiceAsyncProcessor::setUpAndProcess_listLabels<apache::thrift::CompactProtocolReader, apache::thrift::CompactProtocolWriter>,
     &EuGraphServiceAsyncProcessor::setUpAndProcess_listLabels<apache::thrift::BinaryProtocolReader, apache::thrift::BinaryProtocolWriter>,
     &EuGraphServiceAsyncProcessor::executeRequest_listLabels<apache::thrift::CompactProtocolReader, apache::thrift::CompactProtocolWriter>,
     &EuGraphServiceAsyncProcessor::executeRequest_listLabels<apache::thrift::BinaryProtocolReader, apache::thrift::BinaryProtocolWriter>}},
  {"createEdgeLabel",
    {&EuGraphServiceAsyncProcessor::setUpAndProcess_createEdgeLabel<apache::thrift::CompactProtocolReader, apache::thrift::CompactProtocolWriter>,
     &EuGraphServiceAsyncProcessor::setUpAndProcess_createEdgeLabel<apache::thrift::BinaryProtocolReader, apache::thrift::BinaryProtocolWriter>,
     &EuGraphServiceAsyncProcessor::executeRequest_createEdgeLabel<apache::thrift::CompactProtocolReader, apache::thrift::CompactProtocolWriter>,
     &EuGraphServiceAsyncProcessor::executeRequest_createEdgeLabel<apache::thrift::BinaryProtocolReader, apache::thrift::BinaryProtocolWriter>}},
  {"listEdgeLabels",
    {&EuGraphServiceAsyncProcessor::setUpAndProcess_listEdgeLabels<apache::thrift::CompactProtocolReader, apache::thrift::CompactProtocolWriter>,
     &EuGraphServiceAsyncProcessor::setUpAndProcess_listEdgeLabels<apache::thrift::BinaryProtocolReader, apache::thrift::BinaryProtocolWriter>,
     &EuGraphServiceAsyncProcessor::executeRequest_listEdgeLabels<apache::thrift::CompactProtocolReader, apache::thrift::CompactProtocolWriter>,
     &EuGraphServiceAsyncProcessor::executeRequest_listEdgeLabels<apache::thrift::BinaryProtocolReader, apache::thrift::BinaryProtocolWriter>}},
  {"executeCypher",
    {&EuGraphServiceAsyncProcessor::setUpAndProcess_executeCypher<apache::thrift::CompactProtocolReader, apache::thrift::CompactProtocolWriter>,
     &EuGraphServiceAsyncProcessor::setUpAndProcess_executeCypher<apache::thrift::BinaryProtocolReader, apache::thrift::BinaryProtocolWriter>,
     &EuGraphServiceAsyncProcessor::executeRequest_executeCypher<apache::thrift::CompactProtocolReader, apache::thrift::CompactProtocolWriter>,
     &EuGraphServiceAsyncProcessor::executeRequest_executeCypher<apache::thrift::BinaryProtocolReader, apache::thrift::BinaryProtocolWriter>}},
  {"batchInsertVertices",
    {&EuGraphServiceAsyncProcessor::setUpAndProcess_batchInsertVertices<apache::thrift::CompactProtocolReader, apache::thrift::CompactProtocolWriter>,
     &EuGraphServiceAsyncProcessor::setUpAndProcess_batchInsertVertices<apache::thrift::BinaryProtocolReader, apache::thrift::BinaryProtocolWriter>,
     &EuGraphServiceAsyncProcessor::executeRequest_batchInsertVertices<apache::thrift::CompactProtocolReader, apache::thrift::CompactProtocolWriter>,
     &EuGraphServiceAsyncProcessor::executeRequest_batchInsertVertices<apache::thrift::BinaryProtocolReader, apache::thrift::BinaryProtocolWriter>}},
  {"batchInsertEdges",
    {&EuGraphServiceAsyncProcessor::setUpAndProcess_batchInsertEdges<apache::thrift::CompactProtocolReader, apache::thrift::CompactProtocolWriter>,
     &EuGraphServiceAsyncProcessor::setUpAndProcess_batchInsertEdges<apache::thrift::BinaryProtocolReader, apache::thrift::BinaryProtocolWriter>,
     &EuGraphServiceAsyncProcessor::executeRequest_batchInsertEdges<apache::thrift::CompactProtocolReader, apache::thrift::CompactProtocolWriter>,
     &EuGraphServiceAsyncProcessor::executeRequest_batchInsertEdges<apache::thrift::BinaryProtocolReader, apache::thrift::BinaryProtocolWriter>}},
};

apache::thrift::ServiceRequestInfoMap const& EuGraphServiceServiceInfoHolder::requestInfoMap() const {
  static folly::Indestructible<apache::thrift::ServiceRequestInfoMap> requestInfoMap{staticRequestInfoMap()};
  return *requestInfoMap;
}

apache::thrift::ServiceRequestInfoMap EuGraphServiceServiceInfoHolder::staticRequestInfoMap() {
  apache::thrift::ServiceRequestInfoMap requestInfoMap = {
  {"createGraph",
    { false,
     apache::thrift::RpcKind::SINGLE_REQUEST_SINGLE_RESPONSE,
     "EuGraphService.createGraph",
     std::nullopt,
     apache::thrift::concurrency::NORMAL,
     std::nullopt}},
  {"dropGraph",
    { false,
     apache::thrift::RpcKind::SINGLE_REQUEST_SINGLE_RESPONSE,
     "EuGraphService.dropGraph",
     std::nullopt,
     apache::thrift::concurrency::NORMAL,
     std::nullopt}},
  {"listGraphs",
    { false,
     apache::thrift::RpcKind::SINGLE_REQUEST_SINGLE_RESPONSE,
     "EuGraphService.listGraphs",
     std::nullopt,
     apache::thrift::concurrency::NORMAL,
     std::nullopt}},
  {"createLabel",
    { false,
     apache::thrift::RpcKind::SINGLE_REQUEST_SINGLE_RESPONSE,
     "EuGraphService.createLabel",
     std::nullopt,
     apache::thrift::concurrency::NORMAL,
     std::nullopt}},
  {"listLabels",
    { false,
     apache::thrift::RpcKind::SINGLE_REQUEST_SINGLE_RESPONSE,
     "EuGraphService.listLabels",
     std::nullopt,
     apache::thrift::concurrency::NORMAL,
     std::nullopt}},
  {"createEdgeLabel",
    { false,
     apache::thrift::RpcKind::SINGLE_REQUEST_SINGLE_RESPONSE,
     "EuGraphService.createEdgeLabel",
     std::nullopt,
     apache::thrift::concurrency::NORMAL,
     std::nullopt}},
  {"listEdgeLabels",
    { false,
     apache::thrift::RpcKind::SINGLE_REQUEST_SINGLE_RESPONSE,
     "EuGraphService.listEdgeLabels",
     std::nullopt,
     apache::thrift::concurrency::NORMAL,
     std::nullopt}},
  {"executeCypher",
    { false,
     apache::thrift::RpcKind::SINGLE_REQUEST_STREAMING_RESPONSE,
     "EuGraphService.executeCypher",
     std::nullopt,
     apache::thrift::concurrency::NORMAL,
     std::nullopt}},
  {"batchInsertVertices",
    { false,
     apache::thrift::RpcKind::SINGLE_REQUEST_SINGLE_RESPONSE,
     "EuGraphService.batchInsertVertices",
     std::nullopt,
     apache::thrift::concurrency::NORMAL,
     std::nullopt}},
  {"batchInsertEdges",
    { false,
     apache::thrift::RpcKind::SINGLE_REQUEST_SINGLE_RESPONSE,
     "EuGraphService.batchInsertEdges",
     std::nullopt,
     apache::thrift::concurrency::NORMAL,
     std::nullopt}},
  };

  return requestInfoMap;
}
} // namespace eugraph::thrift

namespace apache::thrift::detail {
::folly::Range<const ::std::string_view*>(*TSchemaAssociation<::eugraph::thrift::EuGraphService, false>::bundle)() =
    nullptr;
}
