/**
 * Autogenerated by Thrift for proto/eugraph.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated @nocommit
 */
#pragma once

#include <vector>

#include <thrift/lib/cpp2/gen/module_metadata_h.h>
#include "./service/thrift/gen-cpp2/eugraph_types.h"

namespace eugraph::thrift_service {
class EuGraphService;
} // namespace eugraph::thrift_service

namespace apache {
namespace thrift {
namespace detail {
namespace md {

template <>
class EnumMetadata<::eugraph::thrift_service::PropertyType> {
 public:
  static void gen(ThriftMetadata& metadata);
};
template <>
class EnumMetadata<::eugraph::thrift_service::DateTimeKind> {
 public:
  static void gen(ThriftMetadata& metadata);
};
template <>
class EnumMetadata<::eugraph::thrift_service::TimeKind> {
 public:
  static void gen(ThriftMetadata& metadata);
};
template <>
class StructMetadata<::eugraph::thrift_service::PropertyDefThrift> {
 public:
  static const ::apache::thrift::metadata::ThriftStruct& gen(ThriftMetadata& metadata);
};
template <>
class StructMetadata<::eugraph::thrift_service::DateTimeValueThrift> {
 public:
  static const ::apache::thrift::metadata::ThriftStruct& gen(ThriftMetadata& metadata);
};
template <>
class StructMetadata<::eugraph::thrift_service::TimeValueThrift> {
 public:
  static const ::apache::thrift::metadata::ThriftStruct& gen(ThriftMetadata& metadata);
};
template <>
class StructMetadata<::eugraph::thrift_service::DurationValueThrift> {
 public:
  static const ::apache::thrift::metadata::ThriftStruct& gen(ThriftMetadata& metadata);
};
template <>
class StructMetadata<::eugraph::thrift_service::PropertyValueThrift> {
 public:
  static const ::apache::thrift::metadata::ThriftStruct& gen(ThriftMetadata& metadata);
};
template <>
class StructMetadata<::eugraph::thrift_service::LabelInfo> {
 public:
  static const ::apache::thrift::metadata::ThriftStruct& gen(ThriftMetadata& metadata);
};
template <>
class StructMetadata<::eugraph::thrift_service::EdgeLabelInfo> {
 public:
  static const ::apache::thrift::metadata::ThriftStruct& gen(ThriftMetadata& metadata);
};
template <>
class StructMetadata<::eugraph::thrift_service::VertexRecord> {
 public:
  static const ::apache::thrift::metadata::ThriftStruct& gen(ThriftMetadata& metadata);
};
template <>
class StructMetadata<::eugraph::thrift_service::EdgeRecord> {
 public:
  static const ::apache::thrift::metadata::ThriftStruct& gen(ThriftMetadata& metadata);
};
template <>
class StructMetadata<::eugraph::thrift_service::BatchInsertVerticesResult> {
 public:
  static const ::apache::thrift::metadata::ThriftStruct& gen(ThriftMetadata& metadata);
};
template <>
class StructMetadata<::eugraph::thrift_service::ResultValue> {
 public:
  static const ::apache::thrift::metadata::ThriftStruct& gen(ThriftMetadata& metadata);
};
template <>
class StructMetadata<::eugraph::thrift_service::ResultRow> {
 public:
  static const ::apache::thrift::metadata::ThriftStruct& gen(ThriftMetadata& metadata);
};
template <>
class StructMetadata<::eugraph::thrift_service::QueryStreamMeta> {
 public:
  static const ::apache::thrift::metadata::ThriftStruct& gen(ThriftMetadata& metadata);
};
template <>
class StructMetadata<::eugraph::thrift_service::ResultRowBatch> {
 public:
  static const ::apache::thrift::metadata::ThriftStruct& gen(ThriftMetadata& metadata);
};
template <>
class StructMetadata<::eugraph::thrift_service::GraphInfo> {
 public:
  static const ::apache::thrift::metadata::ThriftStruct& gen(ThriftMetadata& metadata);
};
template <>
class ServiceMetadata<::apache::thrift::ServiceHandler<::eugraph::thrift_service::EuGraphService>> {
 public:
  static void gen(ThriftServiceMetadataResponse& response);
 private:
  static const ThriftServiceContextRef* genRecurse(ThriftMetadata& metadata, std::vector<ThriftServiceContextRef>& services);

  template <typename T>
  friend class ServiceMetadata;

  static void gen_createGraph(ThriftMetadata& metadata, ThriftService& context);
  static void gen_dropGraph(ThriftMetadata& metadata, ThriftService& context);
  static void gen_listGraphs(ThriftMetadata& metadata, ThriftService& context);
  static void gen_createLabel(ThriftMetadata& metadata, ThriftService& context);
  static void gen_listLabels(ThriftMetadata& metadata, ThriftService& context);
  static void gen_createEdgeLabel(ThriftMetadata& metadata, ThriftService& context);
  static void gen_listEdgeLabels(ThriftMetadata& metadata, ThriftService& context);
  static void gen_executeCypher(ThriftMetadata& metadata, ThriftService& context);
  static void gen_batchInsertVertices(ThriftMetadata& metadata, ThriftService& context);
  static void gen_batchInsertEdges(ThriftMetadata& metadata, ThriftService& context);
};
} // namespace md
} // namespace detail
} // namespace thrift
} // namespace apache
