/**
 * Autogenerated by Thrift for proto/eugraph.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated @nocommit
 */

#include "./service/thrift/gen-cpp2/eugraph_data.h"
#include "./service/thrift/gen-cpp2/eugraph_constants.h"

#include <thrift/lib/cpp2/gen/module_data_cpp.h>

namespace apache::thrift {

THRIFT_DATA_MEMBER const std::string_view TStructDataStorage<::eugraph::thrift_service::PropertyDefThrift>::name = "PropertyDefThrift";
THRIFT_DATA_MEMBER const std::array<std::string_view, 3> TStructDataStorage<::eugraph::thrift_service::PropertyDefThrift>::fields_names = { {
  "name"sv,
  "type"sv,
  "is_required"sv,
}};
THRIFT_DATA_MEMBER const std::array<int16_t, 3> TStructDataStorage<::eugraph::thrift_service::PropertyDefThrift>::fields_ids = { {
  1,
  2,
  3,
}};
THRIFT_DATA_MEMBER const std::array<protocol::TType, 3> TStructDataStorage<::eugraph::thrift_service::PropertyDefThrift>::fields_types = { {
  TType::T_STRING,
  TType::T_I32,
  TType::T_BOOL,
}};
THRIFT_DATA_MEMBER const std::array<int, 3> TStructDataStorage<::eugraph::thrift_service::PropertyDefThrift>::isset_indexes = { {
  0,
  1,
  2,
}};

THRIFT_DATA_MEMBER const std::string_view TStructDataStorage<::eugraph::thrift_service::DateTimeValueThrift>::name = "DateTimeValueThrift";
THRIFT_DATA_MEMBER const std::array<std::string_view, 10> TStructDataStorage<::eugraph::thrift_service::DateTimeValueThrift>::fields_names = { {
  "kind"sv,
  "year"sv,
  "month"sv,
  "day"sv,
  "hour"sv,
  "minute"sv,
  "second"sv,
  "nanos"sv,
  "tz_offset_min"sv,
  "tz_name"sv,
}};
THRIFT_DATA_MEMBER const std::array<int16_t, 10> TStructDataStorage<::eugraph::thrift_service::DateTimeValueThrift>::fields_ids = { {
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
}};
THRIFT_DATA_MEMBER const std::array<protocol::TType, 10> TStructDataStorage<::eugraph::thrift_service::DateTimeValueThrift>::fields_types = { {
  TType::T_I32,
  TType::T_I64,
  TType::T_I64,
  TType::T_I64,
  TType::T_I64,
  TType::T_I64,
  TType::T_I64,
  TType::T_I64,
  TType::T_I32,
  TType::T_STRING,
}};
THRIFT_DATA_MEMBER const std::array<int, 10> TStructDataStorage<::eugraph::thrift_service::DateTimeValueThrift>::isset_indexes = { {
  0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
}};

THRIFT_DATA_MEMBER const std::string_view TStructDataStorage<::eugraph::thrift_service::TimeValueThrift>::name = "TimeValueThrift";
THRIFT_DATA_MEMBER const std::array<std::string_view, 7> TStructDataStorage<::eugraph::thrift_service::TimeValueThrift>::fields_names = { {
  "kind"sv,
  "hour"sv,
  "minute"sv,
  "second"sv,
  "nanos"sv,
  "tz_offset_min"sv,
  "tz_name"sv,
}};
THRIFT_DATA_MEMBER const std::array<int16_t, 7> TStructDataStorage<::eugraph::thrift_service::TimeValueThrift>::fields_ids = { {
  1,
  2,
  3,
  4,
  5,
  6,
  7,
}};
THRIFT_DATA_MEMBER const std::array<protocol::TType, 7> TStructDataStorage<::eugraph::thrift_service::TimeValueThrift>::fields_types = { {
  TType::T_I32,
  TType::T_I64,
  TType::T_I64,
  TType::T_I64,
  TType::T_I64,
  TType::T_I32,
  TType::T_STRING,
}};
THRIFT_DATA_MEMBER const std::array<int, 7> TStructDataStorage<::eugraph::thrift_service::TimeValueThrift>::isset_indexes = { {
  0,
  1,
  2,
  3,
  4,
  5,
  6,
}};

THRIFT_DATA_MEMBER const std::string_view TStructDataStorage<::eugraph::thrift_service::DurationValueThrift>::name = "DurationValueThrift";
THRIFT_DATA_MEMBER const std::array<std::string_view, 4> TStructDataStorage<::eugraph::thrift_service::DurationValueThrift>::fields_names = { {
  "months"sv,
  "days"sv,
  "seconds"sv,
  "nanos"sv,
}};
THRIFT_DATA_MEMBER const std::array<int16_t, 4> TStructDataStorage<::eugraph::thrift_service::DurationValueThrift>::fields_ids = { {
  1,
  2,
  3,
  4,
}};
THRIFT_DATA_MEMBER const std::array<protocol::TType, 4> TStructDataStorage<::eugraph::thrift_service::DurationValueThrift>::fields_types = { {
  TType::T_I64,
  TType::T_I64,
  TType::T_I64,
  TType::T_I64,
}};
THRIFT_DATA_MEMBER const std::array<int, 4> TStructDataStorage<::eugraph::thrift_service::DurationValueThrift>::isset_indexes = { {
  0,
  1,
  2,
  3,
}};

THRIFT_DATA_MEMBER const std::string_view TStructDataStorage<::eugraph::thrift_service::PropertyValueThrift>::name = "PropertyValueThrift";
THRIFT_DATA_MEMBER const std::array<std::string_view, 13> TStructDataStorage<::eugraph::thrift_service::PropertyValueThrift>::fields_names = { {
  "bool_val"sv,
  "int_val"sv,
  "double_val"sv,
  "string_val"sv,
  "int_array"sv,
  "double_array"sv,
  "string_array"sv,
  "datetime_val"sv,
  "time_val"sv,
  "duration_val"sv,
  "datetime_array"sv,
  "time_array"sv,
  "duration_array"sv,
}};
THRIFT_DATA_MEMBER const std::array<int16_t, 13> TStructDataStorage<::eugraph::thrift_service::PropertyValueThrift>::fields_ids = { {
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
}};
THRIFT_DATA_MEMBER const std::array<protocol::TType, 13> TStructDataStorage<::eugraph::thrift_service::PropertyValueThrift>::fields_types = { {
  TType::T_BOOL,
  TType::T_I64,
  TType::T_DOUBLE,
  TType::T_STRING,
  TType::T_LIST,
  TType::T_LIST,
  TType::T_LIST,
  TType::T_STRUCT,
  TType::T_STRUCT,
  TType::T_STRUCT,
  TType::T_LIST,
  TType::T_LIST,
  TType::T_LIST,
}};
THRIFT_DATA_MEMBER const std::array<int, 13> TStructDataStorage<::eugraph::thrift_service::PropertyValueThrift>::isset_indexes = { {
  0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
}};

THRIFT_DATA_MEMBER const std::string_view TStructDataStorage<::eugraph::thrift_service::LabelInfo>::name = "LabelInfo";
THRIFT_DATA_MEMBER const std::array<std::string_view, 3> TStructDataStorage<::eugraph::thrift_service::LabelInfo>::fields_names = { {
  "id"sv,
  "name"sv,
  "properties"sv,
}};
THRIFT_DATA_MEMBER const std::array<int16_t, 3> TStructDataStorage<::eugraph::thrift_service::LabelInfo>::fields_ids = { {
  1,
  2,
  3,
}};
THRIFT_DATA_MEMBER const std::array<protocol::TType, 3> TStructDataStorage<::eugraph::thrift_service::LabelInfo>::fields_types = { {
  TType::T_I16,
  TType::T_STRING,
  TType::T_LIST,
}};
THRIFT_DATA_MEMBER const std::array<int, 3> TStructDataStorage<::eugraph::thrift_service::LabelInfo>::isset_indexes = { {
  0,
  1,
  2,
}};

THRIFT_DATA_MEMBER const std::string_view TStructDataStorage<::eugraph::thrift_service::EdgeLabelInfo>::name = "EdgeLabelInfo";
THRIFT_DATA_MEMBER const std::array<std::string_view, 4> TStructDataStorage<::eugraph::thrift_service::EdgeLabelInfo>::fields_names = { {
  "id"sv,
  "name"sv,
  "properties"sv,
  "directed"sv,
}};
THRIFT_DATA_MEMBER const std::array<int16_t, 4> TStructDataStorage<::eugraph::thrift_service::EdgeLabelInfo>::fields_ids = { {
  1,
  2,
  3,
  4,
}};
THRIFT_DATA_MEMBER const std::array<protocol::TType, 4> TStructDataStorage<::eugraph::thrift_service::EdgeLabelInfo>::fields_types = { {
  TType::T_I16,
  TType::T_STRING,
  TType::T_LIST,
  TType::T_BOOL,
}};
THRIFT_DATA_MEMBER const std::array<int, 4> TStructDataStorage<::eugraph::thrift_service::EdgeLabelInfo>::isset_indexes = { {
  0,
  1,
  2,
  3,
}};

THRIFT_DATA_MEMBER const std::string_view TStructDataStorage<::eugraph::thrift_service::VertexRecord>::name = "VertexRecord";
THRIFT_DATA_MEMBER const std::array<std::string_view, 1> TStructDataStorage<::eugraph::thrift_service::VertexRecord>::fields_names = { {
  "properties"sv,
}};
THRIFT_DATA_MEMBER const std::array<int16_t, 1> TStructDataStorage<::eugraph::thrift_service::VertexRecord>::fields_ids = { {
  1,
}};
THRIFT_DATA_MEMBER const std::array<protocol::TType, 1> TStructDataStorage<::eugraph::thrift_service::VertexRecord>::fields_types = { {
  TType::T_LIST,
}};
THRIFT_DATA_MEMBER const std::array<int, 1> TStructDataStorage<::eugraph::thrift_service::VertexRecord>::isset_indexes = { {
  0,
}};

THRIFT_DATA_MEMBER const std::string_view TStructDataStorage<::eugraph::thrift_service::EdgeRecord>::name = "EdgeRecord";
THRIFT_DATA_MEMBER const std::array<std::string_view, 3> TStructDataStorage<::eugraph::thrift_service::EdgeRecord>::fields_names = { {
  "src_vertex_id"sv,
  "dst_vertex_id"sv,
  "properties"sv,
}};
THRIFT_DATA_MEMBER const std::array<int16_t, 3> TStructDataStorage<::eugraph::thrift_service::EdgeRecord>::fields_ids = { {
  1,
  2,
  3,
}};
THRIFT_DATA_MEMBER const std::array<protocol::TType, 3> TStructDataStorage<::eugraph::thrift_service::EdgeRecord>::fields_types = { {
  TType::T_I64,
  TType::T_I64,
  TType::T_LIST,
}};
THRIFT_DATA_MEMBER const std::array<int, 3> TStructDataStorage<::eugraph::thrift_service::EdgeRecord>::isset_indexes = { {
  0,
  1,
  2,
}};

THRIFT_DATA_MEMBER const std::string_view TStructDataStorage<::eugraph::thrift_service::BatchInsertVerticesResult>::name = "BatchInsertVerticesResult";
THRIFT_DATA_MEMBER const std::array<std::string_view, 2> TStructDataStorage<::eugraph::thrift_service::BatchInsertVerticesResult>::fields_names = { {
  "vertex_ids"sv,
  "count"sv,
}};
THRIFT_DATA_MEMBER const std::array<int16_t, 2> TStructDataStorage<::eugraph::thrift_service::BatchInsertVerticesResult>::fields_ids = { {
  1,
  2,
}};
THRIFT_DATA_MEMBER const std::array<protocol::TType, 2> TStructDataStorage<::eugraph::thrift_service::BatchInsertVerticesResult>::fields_types = { {
  TType::T_LIST,
  TType::T_I32,
}};
THRIFT_DATA_MEMBER const std::array<int, 2> TStructDataStorage<::eugraph::thrift_service::BatchInsertVerticesResult>::isset_indexes = { {
  0,
  1,
}};

THRIFT_DATA_MEMBER const std::string_view TStructDataStorage<::eugraph::thrift_service::ResultValue>::name = "ResultValue";
THRIFT_DATA_MEMBER const std::array<std::string_view, 9> TStructDataStorage<::eugraph::thrift_service::ResultValue>::fields_names = { {
  "bool_val"sv,
  "int_val"sv,
  "double_val"sv,
  "string_val"sv,
  "vertex_json"sv,
  "edge_json"sv,
  "path_json"sv,
  "list_json"sv,
  "map_json"sv,
}};
THRIFT_DATA_MEMBER const std::array<int16_t, 9> TStructDataStorage<::eugraph::thrift_service::ResultValue>::fields_ids = { {
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
}};
THRIFT_DATA_MEMBER const std::array<protocol::TType, 9> TStructDataStorage<::eugraph::thrift_service::ResultValue>::fields_types = { {
  TType::T_BOOL,
  TType::T_I64,
  TType::T_DOUBLE,
  TType::T_STRING,
  TType::T_STRING,
  TType::T_STRING,
  TType::T_STRING,
  TType::T_STRING,
  TType::T_STRING,
}};
THRIFT_DATA_MEMBER const std::array<int, 9> TStructDataStorage<::eugraph::thrift_service::ResultValue>::isset_indexes = { {
  0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
}};

THRIFT_DATA_MEMBER const std::string_view TStructDataStorage<::eugraph::thrift_service::ResultRow>::name = "ResultRow";
THRIFT_DATA_MEMBER const std::array<std::string_view, 1> TStructDataStorage<::eugraph::thrift_service::ResultRow>::fields_names = { {
  "values"sv,
}};
THRIFT_DATA_MEMBER const std::array<int16_t, 1> TStructDataStorage<::eugraph::thrift_service::ResultRow>::fields_ids = { {
  1,
}};
THRIFT_DATA_MEMBER const std::array<protocol::TType, 1> TStructDataStorage<::eugraph::thrift_service::ResultRow>::fields_types = { {
  TType::T_LIST,
}};
THRIFT_DATA_MEMBER const std::array<int, 1> TStructDataStorage<::eugraph::thrift_service::ResultRow>::isset_indexes = { {
  0,
}};

THRIFT_DATA_MEMBER const std::string_view TStructDataStorage<::eugraph::thrift_service::QueryStreamMeta>::name = "QueryStreamMeta";
THRIFT_DATA_MEMBER const std::array<std::string_view, 1> TStructDataStorage<::eugraph::thrift_service::QueryStreamMeta>::fields_names = { {
  "columns"sv,
}};
THRIFT_DATA_MEMBER const std::array<int16_t, 1> TStructDataStorage<::eugraph::thrift_service::QueryStreamMeta>::fields_ids = { {
  1,
}};
THRIFT_DATA_MEMBER const std::array<protocol::TType, 1> TStructDataStorage<::eugraph::thrift_service::QueryStreamMeta>::fields_types = { {
  TType::T_LIST,
}};
THRIFT_DATA_MEMBER const std::array<int, 1> TStructDataStorage<::eugraph::thrift_service::QueryStreamMeta>::isset_indexes = { {
  0,
}};

THRIFT_DATA_MEMBER const std::string_view TStructDataStorage<::eugraph::thrift_service::ResultRowBatch>::name = "ResultRowBatch";
THRIFT_DATA_MEMBER const std::array<std::string_view, 1> TStructDataStorage<::eugraph::thrift_service::ResultRowBatch>::fields_names = { {
  "rows"sv,
}};
THRIFT_DATA_MEMBER const std::array<int16_t, 1> TStructDataStorage<::eugraph::thrift_service::ResultRowBatch>::fields_ids = { {
  1,
}};
THRIFT_DATA_MEMBER const std::array<protocol::TType, 1> TStructDataStorage<::eugraph::thrift_service::ResultRowBatch>::fields_types = { {
  TType::T_LIST,
}};
THRIFT_DATA_MEMBER const std::array<int, 1> TStructDataStorage<::eugraph::thrift_service::ResultRowBatch>::isset_indexes = { {
  0,
}};

THRIFT_DATA_MEMBER const std::string_view TStructDataStorage<::eugraph::thrift_service::GraphInfo>::name = "GraphInfo";
THRIFT_DATA_MEMBER const std::array<std::string_view, 3> TStructDataStorage<::eugraph::thrift_service::GraphInfo>::fields_names = { {
  "graph_id"sv,
  "name"sv,
  "created_at"sv,
}};
THRIFT_DATA_MEMBER const std::array<int16_t, 3> TStructDataStorage<::eugraph::thrift_service::GraphInfo>::fields_ids = { {
  1,
  2,
  3,
}};
THRIFT_DATA_MEMBER const std::array<protocol::TType, 3> TStructDataStorage<::eugraph::thrift_service::GraphInfo>::fields_types = { {
  TType::T_I32,
  TType::T_STRING,
  TType::T_I64,
}};
THRIFT_DATA_MEMBER const std::array<int, 3> TStructDataStorage<::eugraph::thrift_service::GraphInfo>::isset_indexes = { {
  0,
  1,
  2,
}};

namespace detail {

::folly::Range<const ::std::string_view*>(*TSchemaAssociation<::eugraph::thrift_service::PropertyDefThrift, false>::bundle)() =
    nullptr;

::folly::Range<const ::std::string_view*>(*TSchemaAssociation<::eugraph::thrift_service::DateTimeValueThrift, false>::bundle)() =
    nullptr;

::folly::Range<const ::std::string_view*>(*TSchemaAssociation<::eugraph::thrift_service::TimeValueThrift, false>::bundle)() =
    nullptr;

::folly::Range<const ::std::string_view*>(*TSchemaAssociation<::eugraph::thrift_service::DurationValueThrift, false>::bundle)() =
    nullptr;

::folly::Range<const ::std::string_view*>(*TSchemaAssociation<::eugraph::thrift_service::PropertyValueThrift, false>::bundle)() =
    nullptr;

::folly::Range<const ::std::string_view*>(*TSchemaAssociation<::eugraph::thrift_service::LabelInfo, false>::bundle)() =
    nullptr;

::folly::Range<const ::std::string_view*>(*TSchemaAssociation<::eugraph::thrift_service::EdgeLabelInfo, false>::bundle)() =
    nullptr;

::folly::Range<const ::std::string_view*>(*TSchemaAssociation<::eugraph::thrift_service::VertexRecord, false>::bundle)() =
    nullptr;

::folly::Range<const ::std::string_view*>(*TSchemaAssociation<::eugraph::thrift_service::EdgeRecord, false>::bundle)() =
    nullptr;

::folly::Range<const ::std::string_view*>(*TSchemaAssociation<::eugraph::thrift_service::BatchInsertVerticesResult, false>::bundle)() =
    nullptr;

::folly::Range<const ::std::string_view*>(*TSchemaAssociation<::eugraph::thrift_service::ResultValue, false>::bundle)() =
    nullptr;

::folly::Range<const ::std::string_view*>(*TSchemaAssociation<::eugraph::thrift_service::ResultRow, false>::bundle)() =
    nullptr;

::folly::Range<const ::std::string_view*>(*TSchemaAssociation<::eugraph::thrift_service::QueryStreamMeta, false>::bundle)() =
    nullptr;

::folly::Range<const ::std::string_view*>(*TSchemaAssociation<::eugraph::thrift_service::ResultRowBatch, false>::bundle)() =
    nullptr;

::folly::Range<const ::std::string_view*>(*TSchemaAssociation<::eugraph::thrift_service::GraphInfo, false>::bundle)() =
    nullptr;

::folly::Range<const ::std::string_view*>(*TSchemaAssociation<::eugraph::thrift_service::PropertyType, true>::bundle)() =
    nullptr;

::folly::Range<const ::std::string_view*>(*TSchemaAssociation<::eugraph::thrift_service::DateTimeKind, true>::bundle)() =
    nullptr;

::folly::Range<const ::std::string_view*>(*TSchemaAssociation<::eugraph::thrift_service::TimeKind, true>::bundle)() =
    nullptr;

} // namespace detail
} // namespace apache::thrift
