/**
 * Autogenerated by Thrift for proto/eugraph.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated @nocommit
 */

#include "./service/thrift/gen-cpp2/EuGraphService.h"
#include "./service/thrift/gen-cpp2/EuGraphService.tcc"

namespace eugraph::thrift_service {
} // namespace eugraph::thrift_service
