/**
 * Autogenerated by Thrift for proto/eugraph.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated @nocommit
 */
#pragma once

#include <thrift/lib/cpp2/gen/module_constants_h.h>

#include "./service/thrift/gen-cpp2/eugraph_types.h"

namespace eugraph::thrift_service {
/** Glean {"file": "proto/eugraph.thrift"} */
namespace eugraph_constants {

  FOLLY_EXPORT ::std::string_view _fbthrift_schema_6931b329c71b5944();
  FOLLY_EXPORT ::folly::Range<const ::std::string_view*> _fbthrift_schema_6931b329c71b5944_includes();

} // namespace eugraph_constants
} // namespace eugraph::thrift_service
