#pragma once

#include "compute_service/physical_plan/operator/aggregate_physical_op.hpp"
#include "compute_service/physical_plan/operator/all_node_scan_physical_op.hpp"
#include "compute_service/physical_plan/operator/create_edge_physical_op.hpp"
#include "compute_service/physical_plan/operator/create_node_physical_op.hpp"
#include "compute_service/physical_plan/operator/distinct_physical_op.hpp"
#include "compute_service/physical_plan/operator/expand_physical_op.hpp"
#include "compute_service/physical_plan/operator/filter_physical_op.hpp"
#include "compute_service/physical_plan/operator/index_scan_physical_op.hpp"
#include "compute_service/physical_plan/operator/label_scan_physical_op.hpp"
#include "compute_service/physical_plan/operator/limit_physical_op.hpp"
#include "compute_service/physical_plan/operator/project_physical_op.hpp"
#include "compute_service/physical_plan/operator/skip_physical_op.hpp"
#include "compute_service/physical_plan/operator/sort_physical_op.hpp"
#include "compute_service/physical_plan/physical_operator_base.hpp"
